-- 272 to 273 --
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.IMPANNO TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.PUNTICON TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.V_IMPR_SOGGETTI TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.G_NOTEAVVISI TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9DELEGHE TO USER SITATSA;
