-- 270 to 271 --
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9CF_MACROFASI TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9CF_REGPERMESSI TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9CF_MODPERMESSI_SA TO USER SITATSA;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9PERMESSI TO USER SITATSA;
GRANT SELECT ON TABLE SITATSA.V_W9PERMESSI TO USER SITATSA;
GRANT SELECT ON TABLE SITATSA.V_RUOLOTECNICO TO USER SITATSA;
