------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------

--------------------------
-- SITATSA 2.5.0
--------------------------

ALTER TABLE SITATSA.W9CANT ADD COLUMN CIVICO VARCHAR(6);
ALTER TABLE SITATSA.W9CANT ADD COLUMN COMUNE VARCHAR(9);
ALTER TABLE SITATSA.W9CANT ADD COLUMN PROV VARCHAR(2);
ALTER TABLE SITATSA.W9CANT ADD COLUMN COORD_X NUMERIC(7);
ALTER TABLE SITATSA.W9CANT ADD COLUMN COORD_Y NUMERIC(7);
ALTER TABLE SITATSA.W9CANT ADD COLUMN LATIT NUMERIC(6,3);
ALTER TABLE SITATSA.W9CANT ADD COLUMN LONGIT NUMERIC(6,3);
ALTER TABLE SITATSA.W9CANT ADD COLUMN NUMLAV NUMERIC(6);
ALTER TABLE SITATSA.W9CANT ADD COLUMN NUMIMP NUMERIC(6);
ALTER TABLE SITATSA.W9CANT ADD COLUMN LAVAUT NUMERIC(6);
ALTER TABLE SITATSA.W9CANT ADD COLUMN IDSISPC NUMERIC(10);
ALTER TABLE SITATSA.W9CANT ADD COLUMN IDCANT NUMERIC(10);
ALTER TABLE SITATSA.W9CANT ADD COLUMN VERSNOT NUMERIC(3);
ALTER TABLE SITATSA.W9CANT ADD COLUMN DAEXPORT VARCHAR(1);
REORG TABLE SITATSA.W9CANT;

INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','CIVICO.W9CANT.W9','W9CACIVICO','Numero civico cantiere','Numero civico','A6',NULL,'Numero civico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','COMUNE.W9CANT.W9','W9CACOMUNE','Codice ISTAT del comune del cantiere','Comune','A9',NULL,'Comune');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','PROV.W9CANT.W9','W9CAPROV','Provincia del cantiere','Provincia','A40','Agx15','Provincia');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','COORD_X.W9CANT.W9','W9CACOORD_X','Coordinata Gauss Boaga X cantiere','Coordinata X','N7',NULL,'Coordinata Gauss Boaga X');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','COORD_Y.W9CANT.W9','W9CACOORD_Y','Coordinata Gauss Boaga Y cantiere','Coordinata Y','N7',NULL,'Coordinata Gauss Boaga Y');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','LATIT.W9CANT.W9','W9CALATIT','Coordinata WGS84 latitudine cantiere','Latitudine','F6.3',NULL,'Coordinata WGS84 latitudine');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','LONGIT.W9CANT.W9','W9CALONGIT','Coordinata WGS84 longitudine cantiere','Longitudine','F6.3',NULL,'Coordinata WGS84 longitudine');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','NUMLAV.W9CANT.W9','W9CANUMLAV','Numero massimo dei lavoratori','N. max lavoratori','N6',NULL,'Numero massimo dei lavoratori');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','NUMIMP.W9CANT.W9','W9CANUMIMP','Numero presunto di imprese','N. imprese','N6',NULL,'Numero presunto di imprese');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','LAVAUT.W9CANT.W9','W9CALAVAUT','Numero presunto di lavoratori autonomi in cantiere','N. lav. autonomi','N6',NULL,'Numero presunto di lavoratori autonomi');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','IDSISPC.W9CANT.W9','W9CAIDSISPC','ID della notifica preliminare nel sistema SISPC','ID SISPC','N10',NULL,'ID SISPC');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','IDCANT.W9CANT.W9','W9CAIDCANT','ID del cantiere nel sistema SISPC','ID cantiere','N10',NULL,'ID cantiere');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DES_WEB) VALUES(0,'E','VERSNOT.W9CANT.W9','W9CAVERSNOT','Versione della notifica preliminare','Vers. notifica','N3',NULL,'Versione della notifica preliminare');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,COC_DOM,COC_DES_WEB)  VALUES(0,'E','DAEXPORT.W9CANT.W9','W9CADAEXP','Notifica preliminare da esportare?','Da esportare?','A2','SN','Notifica da esportare?');

CREATE TABLE SITATSA.W9CANTDEST 
   (	CODGARA NUMERIC(10) NOT NULL,
	CODLOTT NUMERIC(10) NOT NULL,
	NUM_CANT NUMERIC(3) NOT NULL,
	DEST NUMERIC(3) NOT NULL
   ) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
ALTER TABLE SITATSA.W9CANTDEST ADD CONSTRAINT W9CANTDEST_PK PRIMARY KEY ( CODGARA, CODLOTT, NUM_CANT,DEST );
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9CANTDEST TO USER SITATSA;


INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODGARA.W9CANTDEST.W9','W9DECODGAR','Codice della gara','Cod. gara','N10',null,null,'Codice della gara');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODLOTT.W9CANTDEST.W9','W9DENUMLOT','Numero del lotto','Num. lotto','N10',null,null,'Numero del lotto');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUM_CANT.W9CANTDEST.W9','W9DENUMCAN','Numero progressivo cantiere','Numero cantiere','N3',null,null,'Numero progressivo cantiere');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','DEST.W9CANTDEST.W9','W9DEDEST','Destinatario','Destinatario','A50','W9008',null,'Destinatario');
INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,COE_FRM_RE) values ('W9CANTDEST.W9',80011150,'E','DESTIN','Destinatari delle notifiche preliminari','CODGARA.W9CANTDEST.W9,CODLOTT.W9CANTDEST.W9,NUM_CANT.W9CANTDEST','W9CANT.W9','CODGARA.W9CANT.W9,CODLOTT.W9CANT.W9,NUM_CANT.W9CANT','w9_cantdes');


CREATE TABLE SITATSA.W9CANTIMP 
   (	CODGARA NUMERIC(10) NOT NULL,
			CODLOTT NUMERIC(10) NOT NULL,
			NUM_CANT NUMERIC(3) NOT NULL,
			NUM_IMP NUMERIC(3) NOT NULL,
			CODIMP VARCHAR(10),
			CIPDURC VARCHAR(14),
			PROTDURC VARCHAR(8),
			DATDURC TIMESTAMP
   ) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
ALTER TABLE SITATSA.W9CANTIMP ADD CONSTRAINT W9CANTIMP_PK PRIMARY KEY (CODGARA,CODLOTT,NUM_CANT,NUM_IMP);
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9CANTIMP TO USER SITATSA;


INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODGARA.W9CANTIMP.W9','W9CICODGAR','Codice della gara','Cod. gara','N10',null,null,'Codice della gara');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODLOTT.W9CANTIMP.W9','W9CINUMLOT','Numero del lotto','Num. lotto','N10',null,null,'Numero del lotto');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUM_CANT.W9CANTIMP.W9','W9CINUMCAN','Numero progressivo cantiere','Numero cantiere','N3',null,null,'Numero progressivo cantiere');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUM_IMP.W9CANTIMP.W9','W9CINUMIMP','Numero progressivo impresa','Numero impresa','N3',null,null,'Numero progressivo impresa');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'CODIMP.W9CANTIMP.W9','W9CICODIMP','Codice impresa','Codice impresa','A10',null,null,'Codice impresa');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'CIPDURC.W9CANTIMP.W9','W9CICIPDURC','Codice identificativo pratica DURC','Codice DURC','A14',null,null,'Codice identificativo pratica DURC');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'PROTDURC.W9CANTIMP.W9','W9CIPROTDURC','Protocollo pratica DURC','Protocollo DURC','A8',null,null,'Protocollo pratica DURC');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DATDURC.W9CANTIMP.W9','W9CIDATDURC','Data emissione DURC','Data DURC','A10',null,'DATA_ELDA','Data emissione DURC');

INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,COE_FRM_RE) values ('W9CANTIMP.W9',80011170,'E','CANTIMP','Imprese nel cantiere','CODGARA.W9CANTIMP.W9,CODLOTT.W9CANTIMP.W9,NUM_CANT.W9CANTIMP','W9CANT.W9','CODGARA.W9CANT.W9,CODLOTT.W9CANT.W9,NUM_CANT.W9CANT','w9_cantimp');

INSERT INTO SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W9008', 1, 'DPL');
INSERT INTO SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W9008', 2, 'Comune');
INSERT INTO SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W9008', 3, 'Casse edili');
INSERT INTO SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W9008', 4, 'INAIL');
INSERT INTO SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W9008', 5, 'INPS');

UPDATE SITATSA.ELDAVER SET NUMVER='2.5.0' WHERE CODAPP='W9';

