------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------


ALTER TABLE SITATSA.W9ESITO ADD COLUMN DATA_VERB_AGGIUDICAZIONE TIMESTAMP;
ALTER TABLE SITATSA.W9ESITO ADD COLUMN IMPORTO_AGGIUDICAZIONE NUMERIC(24,5);
REORG TABLE SITATSA.W9ESITO;

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DATA_VERB_AGGIUDICAZIONE.W9ESITO.W9','W3ESDVERB','Data di aggiudicazione definitiva','Data aggiudicazione','A10',null,'DATA_ELDA','Data aggiudicazione definitiva');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'IMPORTO_AGGIUDICAZIONE.W9ESITO.W9','W3ESIMP_AGGI','Importo di aggiudicazione','Imp. aggiudicazione','F15',null,'MONEY','Importo di aggiudicazione');




Update SITATSA.W9ESITO e SET DATA_VERB_AGGIUDICAZIONE=(Select DATA_VERB_AGGIUDICAZIONE from SITATSA.W9APPA a WHERE e.CODGARA=a.CODGARA and e.CODLOTT=a.CODLOTT and NUM_APPA=1);
Update SITATSA.W9ESITO e SET IMPORTO_AGGIUDICAZIONE=(Select IMPORTO_AGGIUDICAZIONE from SITATSA.W9APPA a WHERE e.CODGARA=a.CODGARA and e.CODLOTT=a.CODLOTT and NUM_APPA=1);


UPDATE SITATSA.ELDAVER Set numver='2.1.1' where codapp='W9';

