------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------
-- GENE 1.4.49
------------------------------

-- 1.4.47 --> 1.4.48 
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_011',2,'0  ([1] solo CF; [2] solo PI; [3] CF e PI) (config. per anagrafica Impresa WEB)');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_011',3,'0  ([1] solo CF; [2] solo PI; [3] CF e PI) (config. per anagrafica Tecnici WEB)');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_011',4,'0  ([1] solo CF; [2] solo PI; [3] CF e PI) (config. per anagrafica Tecnici impresa WEB)');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_011',5,'0  ([1] solo CF; [2] solo PI; [3] CF e PI) (config. per anagrafica Uff.intestatari WEB)');


Delete from SITATSA.TAB1 where TAB1COD='Ag021';
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',1,'3A - PARCO TECNOLOGICO AGROALIMENTARE DELL''UMBRIA s.c.a r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',2,'AB CERTIFICAZIONE S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',3,'ABICERT S.a.s. di Bianco Antonio & C.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',4,'ACCERTA S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',5,'AGIQUALITAS S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',6,'AGROQUALIT+ S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',7,'ANCCP S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',8,'ANCIS S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',9,'ASACERT S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',10,'Bureau Veritas Italia S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',11,'C.D.Q. ITALIA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',12,'CDQ ALBANIA Sh.p.k.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',13,'CENTRO CERTIFICAZIONE QUALITA'' - C.C.Q. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',14,'CERMET Soc. Cons. a r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',15,'CERSA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',16,'CERSIST S.R.L.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',17,'CERTIEURO S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',18,'Certification Europe Italia S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',19,'CERTIQUALITY S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',20,'CERTITALIA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',21,'CERTO S.u.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',22,'CERTY CEQ S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',23,'CHECK FRUIT S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',24,'CICPND');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',25,'CMI ITALY S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',26,'CNIM S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',27,'CSI S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',28,'CSQA Certificazioni S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',29,'DASA R-GISTER S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',30,'DEKRA Certification S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',31,'Det Norske Veritas Italia S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',32,'DI.QU. S.p.a.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',33,'DIMITTO Italia srl');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',34,'E.L.T.I. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',35,'ECO European Certifying Organization S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',36,'ERGO SocietÓ di Certificazione e Validazione S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',37,'G2S S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',38,'GCERTI Co. Ltd');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',39,'I.CE.C.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',40,'I.E.C. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',41,'ICB QualitÓ S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',42,'ICIC');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',43,'ICILA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',44,'ICIM S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',45,'ICMQ S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',46,'IGQ');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',47,'IIS CERT Srl');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',48,'IMQ S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',49,'IS.E.CERT Istituto Europeo di Certificazione S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',50,'IS.ME.CERT S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',51,'ISTITUTO DEMING S.R.L.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',52,'Istituto di Ricerche e Collaudi M. MASINI S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',53,'Istituto Giordano S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',54,'Istituto Italiano dei Plastici S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',55,'Istituto Mediterraneo di Certificazione S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',56,'Istituto Meridiana S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',57,'ISTITUTO NAZIONALE DELLA QUALITA'' S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',58,'ITA.C.A. Italiana Certificazioni Aziende S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',59,'ITALCERT S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',60,'KIWA ITALIA S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',61,'LLOYD''S Register Quality Assurance Italy S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',62,'M.E.C. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',63,'Moody International Certification S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',64,'MSCERT- MANAGEMENT SYSTEMS CERT S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',65,'NEXOS S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',66,'O.C.E. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',67,'OBIETTIVO QUALITA'' S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',68,'Perry Johnson Registrars, Inc.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',69,'PLC S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',70,'Q - AID S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',71,'Q GEST S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',72,'Q.C.B. ITALIA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',73,'Qluce S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',74,'QUALITAL');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',75,'QUALITY ITALIA S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',76,'QUASER CERTIFICAZIONI S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',77,'RINA Services S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',78,'S.C. ALL CERT SYSTEMS S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',79,'S.I.C.I.V. S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',80,'SGS Italia S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',81,'SICI');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',82,'SMC SocietÓ Mediterranea Certificazioni S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',83,'Star Quality Services Italia S.p.A.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',84,'TECNOPROVE S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',85,'Test-St. Petersburg Company Limited');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',86,'T_V Italia S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',87,'T_V Rheinland Italia S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',88,'UNAVIAcert S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',89,'UNITER S.r.l.');
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('Ag021',90,'VALORITALIA S.r.l.');


ALTER TABLE SITATSA.C0OGGASS ADD C0ATIPO VARCHAR(5);
ALTER TABLE SITATSA.C0OGGASS ADD C0ASCAD TIMESTAMP;
REORG TABLE SITATSA.C0OGGASS;

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM) values (0,'C',null,'C0ATIPO.C0OGGASS.GENE','C0A_TIPO','Tipo documento','Tipo documento','A100','AgzC5',NULL);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM) values (0,'C',null,'C0ASCAD.C0OGGASS.GENE','C0A_SCAD','Data scadenza documento','Data scadenza','A10',NULL,'DATA_ELDA');

-- 1.4.48 --> 1.4.49

ALTER TABLE SITATSA.IMPR ADD TIPRTI NUMERIC(7);
ALTER TABLE SITATSA.IMPR ADD INCTEC NUMERIC(7);
ALTER TABLE SITATSA.IMPR ADD TIPALB NUMERIC(7);
ALTER TABLE SITATSA.IMPR ADD ALBTEC VARCHAR(10);
ALTER TABLE SITATSA.IMPR ADD DATALB TIMESTAMP;
ALTER TABLE SITATSA.IMPR ADD PROALB VARCHAR(6);
ALTER TABLE SITATSA.IMPR ADD TCAPRE NUMERIC(7);
ALTER TABLE SITATSA.IMPR ADD NCAPRE VARCHAR(16);
ALTER TABLE SITATSA.IMPR ADD CNATEC VARCHAR(32);
ALTER TABLE SITATSA.IMPR ADD DNATEC TIMESTAMP;
ALTER TABLE SITATSA.IMPR ADD PRONAS VARCHAR(5);
ALTER TABLE SITATSA.IMPR ADD SEXTEC VARCHAR(1);
REORG TABLE SITATSA.C0OGGASS;

ALTER TABLE SITATSA.TEIM ADD INCTEC NUMERIC(7);
ALTER TABLE SITATSA.TEIM ADD TIPALB NUMERIC(7);
ALTER TABLE SITATSA.TEIM ADD DATALB TIMESTAMP;
ALTER TABLE SITATSA.TEIM ADD PROALB VARCHAR(6);
ALTER TABLE SITATSA.TEIM ADD TCAPRE NUMERIC(7);
ALTER TABLE SITATSA.TEIM ADD NCAPRE VARCHAR(16);
REORG TABLE SITATSA.TEIM;

ALTER TABLE SITATSA.TECNI ADD TIPALB NUMERIC(7);
ALTER TABLE SITATSA.TECNI ADD TCAPRE NUMERIC(7);
ALTER TABLE SITATSA.TECNI ADD NCAPRE VARCHAR(16);
REORG TABLE SITATSA.TECNI;

ALTER TABLE SITATSA.IMPLEG ADD NOTLEG VARCHAR(2000);
REORG TABLE SITATSA.IMPLEG;

ALTER TABLE SITATSA.IMPDTE ADD NOTDTE VARCHAR(2000);
REORG TABLE SITATSA.IMPDTE;

ALTER TABLE SITATSA.IMPIND ADD NAZIMP NUMERIC(7);
ALTER TABLE SITATSA.IMPIND ADD REGDIT VARCHAR(20);
REORG TABLE SITATSA.IMPIND;

update SITATSA.impind set nazimp=1 where codcit is not null;

ALTER TABLE SITATSA.UFFINT ADD TIPOIN NUMERIC(7);
REORG TABLE SITATSA.UFFINT;

ALTER TABLE SITATSA.CAIS ADD ISARCHI VARCHAR(1);
REORG TABLE SITATSA.CAIS;

update SITATSA.cais set isarchi=null;

CREATE TABLE SITATSA.G_IMPCOL
(CODIMP VARCHAR(10) NOT NULL,
NUMCOL NUMERIC(3) NOT NULL,
CODTEC VARCHAR(10),
NOMTEC VARCHAR(60),
INCTIP NUMERIC(7),
INCINI TIMESTAMP,
INCFIN TIMESTAMP,
NOTCOL VARCHAR(2000)
) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.G_IMPCOL ADD CONSTRAINT G_IMPCOL_PK PRIMARY KEY (CODIMP,NUMCOL);

GRANT SELECT,Insert,UPDATE,DELETE ON TABLE SITATSA.G_IMPCOL TO USER SITATSA;


DELETE FROM SITATSA.TAB6 WHERE TAB6COD='G__1' AND TAB6TIP IN ('Ag008','Ag001','A2128');
DELETE FROM SITATSA.TAB1 WHERE TAB1COD='Ag001';

INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',6,'Libero professionista (art.90 c.1/d DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',7,'Società di professionisti (art.90 c.1/e DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',8,'Società di ingegneria (art.90 c.1/f DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',9,'Prestatore di servizi stabilito in altri Stati membri (art.90 c.1/f-bis DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',10,'Raggruppamento temporaneo di professionisti (art.90 c.1/g DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('Ag008',11,'Consorzio stabile di società di professionisti o di ingegneria (art.90 c.1/h DLgs 163/2006)');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_020',3,'Notifica di sistema');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_039',1,'Socio');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_039',2,'Professionista');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_039',3,'Dipendente');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_039',4,'Collaboratore');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',1,'Ingegneri');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',2,'Architetti');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',3,'Geometri');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',4,'Geologi');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',5,'Avvocati');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_040',6,'Notai');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_041',1,'Inarcassa');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_041',2,'CIPAG');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_041',3,'EPPI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_041',4,'Cassa forense');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_042',1,'Verticale');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_042',2,'Orizzontale');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_042',3,'Misto');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',1,'Società per azioni');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',2,'Società a responsabilità limitata');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',3,'Società in accomandita per azioni');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',4,'Società semplice');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',5,'Società in nome collettivo');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',6,'Società in accomandita semplice');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',7,'Studio associato o società di professionisti');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',8,'Società di fatto');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',9,'Impresa individuale');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',10,'Lavoratore autonomo o libero professionista');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',11,'Società cooperativa');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',12,'Organizzazione non lucrativa di utilità sociale');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',13,'Consorzio');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',14,'Società consortile');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',15,'Ente pubblico');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',16,'Forma giuridica estera');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_043',17,'Altro');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',1,'ORGANI COSTITUZIONALI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',2,'MINISTERI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',3,'ORGANI GIURISDIZIONALI E AVVOCATURA');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',4,'AMMINISTRAZIONI INDIPENDENTI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',5,'REGIONI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',6,'AZIENDE SPECIALI REGIONALIZZATE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',7,'PROVINCE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',8,'AZIENDE SPECIALI PROVINCIALIZZATE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',9,'COMUNI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',10,'ENTI DI PREVIDENZA E PREVENZIONE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',11,'ENTI PREPOSTI AD ATTIVITA'' SPORTIVE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',12,'ENTI SCIENTIFICI DI RICERCA E DI SPERIMENTAZIONE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',13,'ENTI DI PROMOZIONE CULTURALE E ARTISTICA');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',14,'AZIENDE SPECIALI MUNICIPALIZZATE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',15,'ISTITUTI AUTONOMI CASE POPOLARI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',16,'AZIENDE DEL SERVIZIO SANITARIO NAZIONALE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',17,'AUTORITA'' DI BACINO');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',18,'COMUNITA'' MONTANE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',19,'ENTI DI BONIFICA E DI SVILUPPO AGRICOLO');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',20,'CONSORZI DI INDUSTRIALIZZAZIONE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',21,'CONSORZI AUTONOMI DI REGIONI, PROVINCE E COMUNI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',22,'CONSORZI ENTI ED AUTORITA'' PORTUALI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',23,'UNIVERSITA'' ED ALTRI ENTI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',24,'ISTITUZIONI EUROPEE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',25,'ISTITUTI BANCARI E FINANZIARI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',26,'ENTI ED ISTITUTI RELIGIOSI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',27,'CONCESSIONARI E IMPRESE DI GESTIONE RETI E INFRASTRUTTURE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',28,'ASSOCIAZIONE DI IMPRESE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',29,'IMPRESE A PARTECIPAZIONE PUBBLICA');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',30,'CONSORZI DI IMPRESE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',31,'IMPRESE ED ALTRI SOGGETTI PRIVATI NON IN FORMA ASSOCIATA');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',32,'ASSOCIAZIONI DI CATEGORIA E ORGANIZZAZIONI SINDACALI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',33,'CAMERE DI COMMERCIO');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',34,'SOGGETTI ESTERI');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',35,'PROVVEDITORATO REGIONALE ALLE OPERE PUBBLICHE');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',36,'ORGANISMI DI DIRITTO PUBBLICO');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) VALUES ('G_044',37,'ALTRI SOGGETTI PUBBLICI E PRIVATI');

UPDATE SITATSA.TAB6 SET TAB6DESC = 'Tipo incarico del soggetto dell''impresa con altra carica o qualifica' WHERE TAB6COD = 'G__1' and TAB6TIP='Ag007';
INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) VALUES ('G__1','G_039','Tipo incarico del collaboratore dell''impresa');
INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) VALUES ('G__1','G_040','Tipo albo professionale');
INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) VALUES ('G__1','G_041','Tipo cassa di previdenza');
INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) VALUES ('G__1','G_042','Tipo raggruppamento temporaneo');


DELETE FROM SITATSA.C0CAMPI WHERE C0C_MNE_BER in ('G_NUMAZI','DINTIM','DFITIM','IMPISC','DINTEC1','DFITEC1');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'C',NULL,'DINTIM.TEIM.GENE','DINTIM','Data inizio dell''incarico (NON USATO)','NON USATO','A10',NULL,'DATA_ELDA','Data inizio incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'C',NULL,'DFITIM.TEIM.GENE','DFITIM','Data termine dell''incarico (NON USATO)','NON USATO','A10',NULL,'DATA_ELDA','Data termine incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'P',NULL,'IMPISC.CATE.GENE','IMPISC','Importo d''iscrizione della categoria','Importo d''iscrizione','F15',NULL,'MONEY',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'C',NULL,'DINTEC.TECNI.GENE','DINTEC1','Data inizio dell''incarico (NON USATO)','NON USATO','A10',NULL,'DATA_ELDA','Data inizio incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'C',NULL,'DFITEC.TECNI.GENE','DFITEC1','Data termine dell''incarico (NON USATO)','NON USATO','A10',NULL,'DATA_ELDA','Data termine incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TIPRTI.IMPR.GENE','G_TIPRTI','Tipo di raggruppamento temporaneo','Tipo raggrupp.temp.','A100','G_042',NULL,'Tipo di raggruppamento temporaneo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'INCTEC.IMPR.GENE','G_INCTEC','Titolo del libero professionista','Titolo','A40','Ag004',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TIPALB.IMPR.GENE','G_TIPALB','Albo professionale a cui il professionista è iscritto','Albo professionale','A100','G_040',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'ALBTEC.IMPR.GENE','G_ALBTEC','Numero di iscrizione all''albo professionale','N.iscrizione albo','A10',NULL,NULL,'Numero iscrizione all''albo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATALB.IMPR.GENE','G_DATALB','Data iscrizione all''albo professionale','Data iscriz.albo','A10',NULL,'DATA_ELDA','Data di iscrizione all''albo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'PROALB.IMPR.GENE','G_PROALB','Codice ISTAT della provincia di iscrizione all''albo','Prov.iscr.albo(ISTAT','A6',NULL,NULL,'Codice ISTAT provincia di iscriz.all''albo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TCAPRE.IMPR.GENE','G_TCAPRE','Tipologia cassa di previdenza a cui il profess.è iscritto','Cassa di previdenza','A100','G_041',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NCAPRE.IMPR.GENE','G_NCAPRE','Numero matricola di iscrizione alla Cassa di previdenza','N.matric.cassa prev.','A16',NULL,NULL,'N. matricola cassa di previdenza');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'CNATEC.IMPR.GENE','G_CNATEC','Comune di nascita del libero professionista','Comune di nascita','A32',NULL,NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DNATEC.IMPR.GENE','G_DNATEC','Data di nascita del libero professionista','Data di nascita','A10',NULL,'DATA_ELDA',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'PRONAS.IMPR.GENE','G_PRONAS','Provincia di nascita (sigla) del libero professionista','Provincia di nascita','A40','Agx15',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'SEXTEC.IMPR.GENE','G_SEXTEC','Sesso (M maschio, F femmina) del libero professionista','Sesso','A1',NULL,NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NOTDTE.IMPDTE.GENE','G_NOTDTE','Eventuali note','Note','A2000',NULL,'NOTE',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NOTLEG.IMPLEG.GENE','G_NOTLEG','Eventuali note','Note','A2000',NULL,'NOTE',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E','P','CODIMP.G_IMPCOL.GENE','G_CODIMPCO','Codice impresa','Codice impresa','A10',NULL,NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E','P','NUMCOL.G_IMPCOL.GENE','G_NUMCOL','Numero progressivo del collaboratore','Num. progressivo','N3',NULL,NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'CODTEC.G_IMPCOL.GENE','G_CODTEC_C','Codice del collaboratore','Cod. collaboratore','A10',NULL,NULL,'Codice');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NOMTEC.G_IMPCOL.GENE','G_NOMTEC_C','Nome del collaboratore','Nome collaboratore','A60',NULL,NULL,'Nome');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'INCTIP.G_IMPCOL.GENE','G_INCTIP','Tipo di incarico','Incarico','A100','G_039',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'INCINI.G_IMPCOL.GENE','G_INCINI','Data inizio dell''incarico','Inizio incarico','A10',NULL,'DATA_ELDA','Data inizio incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'INCFIN.G_IMPCOL.GENE','G_INCFIN','Data termine dell''incarico','Termine incarico','A10',NULL,'DATA_ELDA','Data termine incarico');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NOTCOL.G_IMPCOL.GENE','G_NOTCOL','Eventuali note','Note','A2000',NULL,'NOTE',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NAZIMP.IMPIND.GENE','G_NAZIMPIN','Nazione','Nazione','A100','Ag010',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'REGDIT.IMPIND.GENE','G_REGDITIN','Numero R.E.A. (Repertorio notizie Economiche Amministrative)','Numero R.E.A.','A20',NULL,NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'INCTEC.TEIM.GENE','G_INCTECIM','Titolo del tecnico','Titolo','A40','Ag004',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TIPALB.TEIM.GENE','G_TIPALBIM','Albo professionale a cui il tecnico è iscritto','Albo professionale','A100','G_040',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATALB.TEIM.GENE','G_DATALBIM','Data iscrizione all''albo professionale','Data iscriz.albo','A10',NULL,'DATA_ELDA','Data di iscrizione all''albo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'PROALB.TEIM.GENE','G_PROALBIM','Codice ISTAT della provincia di iscrizione all''albo','Prov.iscr.albo(ISTAT','A6',NULL,NULL,'Codice ISTAT provincia di iscriz.all''albo');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TCAPRE.TEIM.GENE','G_TCAPREIM','Tipologia Cassa di previdenza a cui il tecnico è iscritto','Cassa di previdenza','A100','G_041',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NCAPRE.TEIM.GENE','G_NCAPREIM','Numero matricola di iscrizione alla Cassa di previdenza','N.matric.cassa prev.','A16',NULL,NULL,'N. matricola cassa di previdenza');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TIPALB.TECNI.GENE','G_TIPALBI','Albo professionale a cui il tecnico è iscritto','Albo professionale','A100','G_040',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TCAPRE.TECNI.GENE','G_TCAPREI','Tipologia Cassa di previdenza a cui il tecnico è iscritto','Cassa di previdenza','A100','G_041',NULL,NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'NCAPRE.TECNI.GENE','G_NCAPREI','Numero matricola di iscrizione alla Cassa di previdenza','N.matric.cassa prev.','A16',NULL,NULL,'N. matricola cassa di previdenza');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'ISARCHI.CAIS.GENE','G_ISARCHIC','Categoria d''iscrizione archiviata?','Categ. archiviata?','A2',NULL,'SN',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'ISARCHI.V_CAIS_TIT.GENE','G_ISARCHI_T','Categoria d''iscrizione archiviata?','Categ. archiviata?','A2',NULL,'SN',NULL);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'TIPOIN.UFFINT.GENE','G_TIPOIN','Tipo di amministrazione','Tipologia','A100','G_044',NULL,NULL);

INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,COE_FRM_RE) values ('G_IMPCOL.GENE',0,'E','IMP_COLLAB','Collaboratori dell''impresa','CODIMP.G_IMPCOL.GENE', 'IMPR.GENE', 'CODIMP.IMPR.GENE', 'g_impco0');

UPDATE SITATSA.ELDAVER SET NUMVER='1.4.49' WHERE CODAPP='G_';


------------------------------
-- GENEWEB 1.6.6
------------------------------

UPDATE SITATSA.W_OGGETTI SET DESCR = 'Altre cariche o qualifiche' WHERE OGGETTO='GENE.ImprScheda.LEGALI.IMPAZI';
UPDATE SITATSA.W_OGGETTI SET DESCR = 'Aggiungi altra carica o qualifica' WHERE OGGETTO='INS.GENE.ImprScheda.LEGALI.INS-IMPAZI';
UPDATE SITATSA.W_OGGETTI SET DESCR = 'Elimina altra carica o qualifica' WHERE OGGETTO='DEL.GENE.ImprScheda.LEGALI.DEL-IMPAZI';

INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','GENE.TrovaImprese.NOTE','Note e avvisi',865);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','GENE.ImprScheda.DATIGEN.ALBO','Iscrizione Albo professionale',965);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','GENE.SchedaTeim.GEN','Dati generali',1693);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','GENE.SchedaTeim.ALT','Altri dati',1694);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','GENE.ImprScheda.LEGALI.G_IMPCOL','Collaboratori',1800);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','INS.GENE.ImprScheda.LEGALI.INS-G_IMPCOL','Inserisci collaboratore',1805);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','DEL.GENE.ImprScheda.LEGALI.DEL-G_IMPCOL','Elimina collaboratore',1810);


INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('FUNZ','VIS','ALT.GENE.ImprScheda.RegistraSuPortale','Visualizza',0,1,1,270277504);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.UFFINT.IDAMMIN','Visualizza',0,1,1,67575777);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.UFFINT.NATGIU','Visualizza',0,1,1,3281276367);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.IMPR.DCERCC','Visualizza',0,1,1,1883885030);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.IMPR.NCERCC','Visualizza',0,1,1,3848750968);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.IMPAZI.QUOAZI','Visualizza',0,1,1,4159529394);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.TECNI.CODSTU','Visualizza',0,1,1,3085434394);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.TECNI.ISCCO1','Visualizza',0,1,1,1826138674);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.TECNI.ISCCOL','Visualizza',0,1,1,4119712371);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','GENE.TEIM.INCTIM','Visualizza',0,1,1,571604719);

INSERT INTO SITATSA.W_ACCLIV (TABELLA,DISCR,LIV1,VALORE) values ('GAREAVVISI','SYSABG','CODGAR','CODGAR');

UPDATE SITATSA.ELDAVER SET NUMVER='1.6.6' WHERE CODAPP='W_';

------------------------------
-- PIATRI 1.0.1
------------------------------

CREATE TABLE SITATSA.ECOTRI
 (CONTRI NUMERIC(10) NOT NULL,
CONECO NUMERIC(5) NOT NULL,
DESCRI VARCHAR(2000),
CUPPRG VARCHAR(15) ,
STIMA NUMERIC(24,5)
) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.ECOTRI ADD CONSTRAINT ECOTRI_PK PRIMARY KEY (CONTRI,CONECO);

GRANT SELECT,Insert,UPDATE,DELETE ON TABLE SITATSA.ECOTRI TO USER SITATSA;

INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CONTRI.ECOTRI.PIANI','T2ECONTRI','Numero progressivo del programma','N.progr.piano trien.','N10',NULL,NULL,'Numero progressivo del programma');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CONECO.ECOTRI.PIANI','T2ECONECO','Numero progressivo del lavoro','N.progr.lavoro','N5',NULL,NULL,'Numero progressivo del lavoro');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'DESCRI.ECOTRI.PIANI','T2EDESCRI','Descrizione dell''intervento','Descrizione','A2000',NULL,'NOTE','Descrizione dell''intervento');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'CUPPRG.ECOTRI.PIANI','T2ECUPPRG','Codice CUP di progetto (assegnato da CIPE)','Cod. CUP Progetto','A15',NULL,NULL,'Codice CUP di progetto (assegnato da CIPE)');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'STIMA.ECOTRI.PIANI','T2ESTIMA','Stima costo del lavoro','Stima costo','F15',NULL,'MONEY','Stima costo del lavoro');
INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,COE_FRM_RE) values ('ECOTRI.PIANI',0,'E','LAV_ECON','Lavori in economia','CONTRI.ECOTRI.PIANI', 'PIATRI.PIANI', 'CONTRI.PIATRI.PIANI', 'pt_ectri');


CREATE TABLE SITATSA.PTFLUSSI
(IDFLUSSO NUMERIC(10) NOT NULL,
KEY01 NUMERIC(10) NOT NULL,
AUTORE VARCHAR(100),
TIPINV NUMERIC(7),
DATINV TIMESTAMP,
NOTEINVIO VARCHAR(2000),
VERXML VARCHAR(20),
CFSA VARCHAR(11),
XML BLOB
) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.PTFLUSSI ADD CONSTRAINT PTFLUSSI_PK PRIMARY KEY (IDFLUSSO);

GRANT SELECT,Insert,UPDATE,DELETE ON TABLE SITATSA.PTFLUSSI TO USER SITATSA;

INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','IDFLUSSO.PTFLUSSI.PIANI','PTFLID','ID dell''invio','ID invio','N10',NULL,NULL,'ID dell''invio');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'KEY01.PTFLUSSI.PIANI','PTFLKEY01','Codice del programma','Key 01','N10',NULL,NULL,'Codice del programma');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'AUTORE.PTFLUSSI.PIANI','PTFLAUTORE','Nome dell''autore dell''invio','Autore','A100',NULL,NULL,'Nome dell''autore dell''invio');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'TIPINV.PTFLUSSI.PIANI','PTFLTIPINV','Tipo di invio','Tipo di invio','A100','PT002',NULL,'Tipo di invio');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'DATINV.PTFLUSSI.PIANI','PTFLDATINV','Data invio','Data invio','A10',NULL, 'DATA_ELDA', 'Data invio');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'NOTEINVIO.PTFLUSSI.PIANI','PTNOTINVIO','Note invio','Note','A2000',NULL, 'NOTE', 'Note invio');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',NULL,'XML.PTFLUSSI.PIANI','PTFLXML','File XML','File XML','A2000',NULL, 'CLOB', 'File XML');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'VERXML.PTFLUSSI.PIANI','PTFLVERXML','Versione file XML','Versione XML','A20',NULL, NULL, 'Versione file XML');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'CFSA.PTFLUSSI.PIANI','PTFLCFSA','Codice fiscale della stazione appaltante','C.F. stazione appalt','A11',NULL, NULL, 'Cod.fiscale stazione appaltante');
INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,COE_FRM_RE) values ('PTFLUSSI.PIANI',0,'E','PTFLUSSI','Invii del programma','KEY01.PTFLUSSI.PIANI', 'PIATRI.PIANI', 'CONTRI.PIATRI.PIANI', 'pt_fluss');



-- Nuovi campi PIATRI/PIANI
ALTER TABLE SITATSA.PIATRI ADD COLUMN IMPACC NUMERIC(24,5);
ALTER TABLE SITATSA.PIATRI ADD COLUMN STATRI NUMERIC(7);
ALTER TABLE SITATSA.PIATRI DROP COLUMN NAPTRI;
REORG TABLE SITATSA.PIATRI;
ALTER TABLE SITATSA.PIATRI ADD COLUMN NAPTRI VARCHAR(10);
REORG TABLE SITATSA.PIATRI;

INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'IMPACC.PIATRI.PIANI','T2IMPACC','Accantonamento primo anno (art. 12 c. 1 dpr 207/2010)','Accantonamento 1''','F15',null,'MONEY','Accantonamento primo anno (art. 12 c. 1 dpr 207/2010)');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'STATRI.PIATRI.PIANI','T2STATRI','Stato programma','Stato programma','A100','PT001',NULL,'Stato programma');
UPDATE SITATSA.C0CAMPI SET C0C_FS='A10' WHERE C0C_MNE_BER='T2NAPTRI';

INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT001',1,'In compilazione');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT001',2,'Pubblicato');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT001',3,'In modifica');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT001',4,'Cancellato');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT002',1,'Primo invio');
INSERT INTO SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('PT002',2,'Rettifica');

INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('PT_1','PT001','Stato programma');
INSERT INTO SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('PT_1','PT002','Tipo di invio');

-- Aggiornamento del profilo SA-PIATRI
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.STATRI',0,1851973007);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.TAPTRI',0,2774453787);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.NAPTRI',0,1727008155);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.DAPTRI',0,3263189717);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.TADOZI',0,3107290751);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.NADOZI',0,2057027071);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','PIANI.PIATRI.DADOZI',0,3740000945);


-- Modificata la descizione dei profili
update SITATSA.W_PROFILI set descrizione='Profilo riservato all''Osservatorio Regionale per l''amministrazione dell''archiviodelle stazioni appaltanti' where cod_profilo='SA-ADMIN';
update SITATSA.W_PROFILI set descrizione='Comunicazioni di bandi ed esiti a cura degli Enti nazionali e comunicazione di eventi di sotratti inferiori a 40.000 euro' where cod_profilo='ENTINAZ';
update SITATSA.W_PROFILI set descrizione='Comnicazioni di avvisi per manifestazione di interesse ed altri avvisi' where cod_profilo='SA-AVVISI';
update SITATSA.W_PROFILI set descrizione='Comunicazioni di eventi di contratti di lavori, forniture e servizi' where cod_profilo='SA-APPA';
update SITATSA.W_PROFILI set descrizione='Comunicazioni di eventi di programmi triennali/annuali di lavori, forniture e servizi' where cod_profilo='SA-PIATRI';
update SITATSA.W_PROFILI set descrizione='Monitoraggio degli investimenti pubblici: richiesta e gestione del codice CUP' where cod_profilo='SA-CUP';


UPDATE SITATSA.ELDAVER SET NUMVER='1.0.1' WHERE CODAPP='PT';

------------------------------
-- SITATSA 2.4.1
--------------------------

UPDATE SITATSA.ELDAVER SET NUMVER='2.4.1' WHERE CODAPP='W9';

