-- 272 to 273 --
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.IMPANNO TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.PUNTICON TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.V_IMPR_SOGGETTI TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_NOTEAVVISI TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9DELEGHE  TO USER SITATORT;
