------ SCHEMA SITAT ORT ----------
SET SCHEMA = SITATORT;
SET CURRENT PATH = SITATORT;


UPDATE COMMAND OPTIONS USING s OFF;
DROP procedure aggiorna;
UPDATE COMMAND OPTIONS USING s ON;

------ CARATTERE TERMINATORE ----------
--#SET TERMINATOR @


--------------------------------
-- AGGIORNAMENTO SITAT/VIGILANZA
-- Database: DB2
-- Versione: 3.1.0 --> 3.2.0
------------------------------


--#SET TERMINATOR @

create procedure aggiorna ()
begin

	Declare v_sql varchar(5000);
	Declare v_max varchar(10);

	IF (select count(*) from eldaver where codapp='W9' and (numver='3.1.0' or numver like '3.1.0.%'))=1
	THEN
	
		------------------------------------------------------------------------------------------------
		------------------------		MODIFICA STRUTTURA TABELLE			------------------------
		------------------------------------------------------------------------------------------------
		
		SET v_sql = 'CREATE TABLE TAB_CONTROLLI (
			CODAPP VARCHAR(5) NOT NULL,
			NUM NUMERIC(7) NOT NULL,
			ENTITA VARCHAR(50),
			SEZIONE VARCHAR(50),
			TITOLO VARCHAR(100),
			CONDIZIONE VARCHAR(2000),
			MSG VARCHAR(2000),
			TIPO VARCHAR(1),
			PRIMARY KEY (CODAPP,NUM)
		)';
		EXECUTE IMMEDIATE (v_sql);
		
		SET v_sql = 'ALTER TABLE UFFICI ADD COLUMN CODICE_UFFICIO VARCHAR(6)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE UFFICI');
		
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN FIN_REGIONALE VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN FLAG_IMPORTI VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN FLAG_SICUREZZA VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN FLAG_LIVELLO_PROGETTUALE VARCHAR(100)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN FLAG_LIVELLO_PROGETTUALE VARCHAR(100)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9APPA ADD COLUMN VERIFICA_CAMPIONE VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9APPA');
		
		SET v_sql = 'ALTER TABLE W9AVAN ADD COLUMN SUBAPPALTI VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9AVAN');
		
		SET v_sql = 'ALTER TABLE W9VARI ADD COLUMN FLAG_VARIANTE VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9VARI ADD COLUMN QUINTO_OBBLIGO VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9VARI ADD COLUMN FLAG_IMPORTI VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9VARI ADD COLUMN FLAG_SICUREZZA VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9VARI');
		
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN FLAG_SINGOLO_COMMISSIONE VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_APPROVAZIONE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN FLAG_IMPORTI VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN FLAG_SICUREZZA VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN FLAG_SUBAPPALTATORI VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_INIZIO_AMM_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_FINE_AMM_RISERVE  TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_INIZIO_ARB_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_FINE_ARB_RISERVE  TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_INIZIO_GIU_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_FINE_GIU_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_INIZIO_TRA_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9COLL ADD COLUMN DATA_FINE_TRA_RISERVE TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9COLL');
		
		SET v_sql = 'ALTER TABLE W9ACCO ADD COLUMN DATA_INIZIO_ACC TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9ACCO ADD COLUMN DATA_FINE_ACC TIMESTAMP';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9ACCO');
		
		SET v_sql = 'ALTER TABLE W3TABREQ ADD COLUMN INIZIALE VARCHAR(1)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W3TABREQ ADD COLUMN DOCUMENTI_DEFAULT VARCHAR(40)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W3TABREQ');
		
		SET v_sql = 'ALTER TABLE W9LOTT ADD COLUMN CUIINT VARCHAR(25)';
		EXECUTE IMMEDIATE (v_sql);
		SET v_sql = 'ALTER TABLE W9LOTT ADD COLUMN URL_EPROC VARCHAR(2000)';
		EXECUTE IMMEDIATE (v_sql);
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9LOTT');
		
		------------------------------------------------------------------------------------------------
		----------------------------------------    MODIFICA DATI    -----------------------------------
		------------------------------------------------------------------------------------------------

		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'CODICE_UFFICIO.UFFICI.W9','W9UFFCODUFF','Codice ufficio','Codice ufficio','A6',null,null,'Codice ufficio');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FIN_REGIONALE.W9APPA.W9','W9APPAFINREG','Il contratto attinge a finanziamenti regionali?','Finanz. regionali?','A2',null,'SN','Il contratto attinge a finanziamenti regionali?');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_IMPORTI.W9APPA.W9','W9APPAFLAGIMP','Tipo di importo in esecuzione','Tipo importo','A15','W9z01',null,'Tipo di importo in esecuzione');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_SICUREZZA.W9APPA.W9','W9APPAFLAGSIC','Tipo di oneri di sicurezza','Tipo oneri sicurezza','A15','W9z01',null,'Tipo di oneri di sicurezza');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_LIVELLO_PROGETTUALE.W9APPA.W9','W9APPALIVPROG','Livello progettuale','Livello progettuale','A50','W9021',null,'Livello progettuale');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'VERIFICA_CAMPIONE.W9APPA.W9','W9APPAVERICAMP','Effettuata la verifica a campione dei requisiti?','Verifica campione','A2',null,'SN','Effettuata la verifica a campione dei requisiti?');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'SUBAPPALTI.W9AVAN.W9','W9AVANSUBAPP','Sono stati autorizzati subappalti per questo SAL?','Autorizzati subapp?','A2',null,'SN','Sono stati autorizzati subappalti per questo SAL?');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_VARIANTE.W9VARI.W9','W9VARIFLVAR','Tipologia della variante','Tipologia variante','A50','W9z03',null,'Tipologia della variante');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'QUINTO_OBBLIGO.W9VARI.W9','W9VARIQUINTO','Rientranti nel quinto d''obbligo?','Quinto obbligo?','A2',null,'SN','Rientranti nel quinto d''obbligo?');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_IMPORTI.W9VARI.W9','W9VARIFLIMPOR','Tipo di importo in esecuzione','Tipo importo esecuz.','A15','W9z01',null,'Tipo di importo in esecuzione');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_SICUREZZA.W9VARI.W9','W9VARIFLSIC','Tipo di oneri di sicurezza','Tipo oneri sicurez.','A15','W9z01',null,'Tipo di oneri di sicurezza');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_SINGOLO_COMMISSIONE.W9COLL.W9','W9COLLFLSIC','Collaudatore o commissione?','Collaudatore o comm.','A15','W9z02',null,'Collaudatore o commissione?');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_APPROVAZIONE.W9COLL.W9','W9COLLDTAPPROV','Data approvazione del certificato relativo','Data approv. cert','A10',null,'DATA_ELDA','Data approvazione del certificato relativo');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_IMPORTI.W9COLL.W9','W9COLLFLIMP','Tipo di importo in esecuzione','Tipo importo','A15','W9z01',null,'Tipo di importo in esecuzione');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_SICUREZZA.W9COLL.W9','W9COLLFLSICUR','Tipo di oneri di sicurezza','Tipo oneri sicurezza','A15','W9z01',null,'Tipo di oneri di sicurezza');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'FLAG_SUBAPPALTATORI.W9COLL.W9','W9COLLFLSUBAP','Nel contratto l''aggiudicatario ha usufruito di subappalti','Iter subappaltatori','A2',NULL,'SN','Durante l''iter del contratto l''aggiudicatario si è avvalso di subappaltatori');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_INIZIO_AMM_RISERVE.W9COLL.W9','W9COLLDTINAMMRI','Data inizio riserva in via amministrativa','Data inizio ris.amm.','A10',null,'DATA_ELDA','Data inizio riserva in via amministrativa');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_INIZIO_ARB_RISERVE.W9COLL.W9','W9COLLDTINARBRI','Data inizio riserva in via arbitrale', 'Data inizio ris.arb.','A10',null,'DATA_ELDA','Data inizio riserva in via arbitrale');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_INIZIO_GIU_RISERVE.W9COLL.W9','W9COLLDTINGIURI','Data inizio riserva in via giudiziale','Data inizio ris.giu.','A10',null,'DATA_ELDA','Data inizio riserva in via giudiziale');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_INIZIO_TRA_RISERVE.W9COLL.W9','W9COLLDTINTRARI','Data inizio riserva in via transattiva','Data inizio ris.tra.','A10',null,'DATA_ELDA','Data inizio riserva in via transattiva');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_FINE_AMM_RISERVE.W9COLL.W9','W9COLLDTFIAMMRI','Data fine riserva in via amministrativa','Data fine ris.amm.','A10',null,'DATA_ELDA','Data fine riserva in via amministrativa');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_FINE_ARB_RISERVE.W9COLL.W9','W9COLLDTFIARBRI','Data fine riserva in via arbitrale','Data fine ris.arb.','A10',null,'DATA_ELDA','Data fine riserva in via arbitrale');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_FINE_GIU_RISERVE.W9COLL.W9','W9COLLDTFIGIURI','Data fine riserva in via giudiziale','Data fine ris.giu.','A10',null,'DATA_ELDA','Data fine riserva in via giudiziale');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_FINE_TRA_RISERVE.W9COLL.W9','W9COLLDTFITRARI','Data fine riserva in via transattiva','Data fine ris.tra','A10',null,'DATA_ELDA','Data fine riserva in via transattiva');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_INIZIO_ACC.W9ACCO.W9','W9ACCODTINAC','Data inizio accordo quadro','Data inizio accordo','A10',null,'DATA_ELDA','Data inizio accordo quadro');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'DATA_FINE_ACC.W9ACCO.W9','W9ACCODTFIAC','Data fine accordo quadro','Data fine accordo','A10',null,'DATA_ELDA','Data fine accordo quadro');
		
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'CUIINT.W9LOTT.W9','W9LOCUIINT','CUI progettazione','CUI progettazione','A25',null,null,'CUI progettazione');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',NULL,'URL_EPROC.W9LOTT.W9','W9LOURLEPROC','URL piattaforma e-procurement di svolgimento gara','URL e-procur gara','A2000',null,null,'URL piattaforma e-procurement di svolgimento gara');
		
		UPDATE C0CAMPI SET COC_CONTA=1 WHERE COC_MNE_UNI LIKE 'CODGARA.%.W9' AND C0C_CHI='P';
		UPDATE C0CAMPI SET COC_CONTA=2 WHERE COC_MNE_UNI LIKE 'CODLOTT.%.W9' AND C0C_CHI='P';
		UPDATE C0CAMPI SET COC_CONTA=3 WHERE COC_MNE_UNI IN ('NUM_APPA.W9AGGI.W9','NUM_APPA.W9APPA.W9','NUM_TPRO.W9TECPRO.W9','NUM_VARI.W9VARI.W9','NUMXML.W9XML.W9','NUM_CANT.W9CANT.W9','NUM_CANT.W9CANTDEST.W9','NUM_CANT.W9CANTIMP.W9','NUM_COLL.W9COLL.W9','NUM_CONC.W9CONC.W9','NUM_COND.W9COND.W9','NUM_CPV.W9CPV.W9','NUM_APPA.W9FINA.W9','NUM_IMPR.W9IMPRESE.W9','NUM_INAD.W9INASIC.W9','NUM.W9INCA.W9','NUM_INFOR.W9INFOR.W9','NUM_INIZ.W9INIZ.W9','NUM_CATE.W9LOTTCATE.W9','NUM_MISS.W9MISSIC.W9','NUM_VARI.W9MOTI.W9','NUM_APPA.W9PUBB.W9','NUM_INIZ.W9PUES.W9','NUM_REGO.W9REGCON.W9','NUM_APPA.W9REQU.W9','NUM_RITA.W9RITA.W9','NUM_SIC.W9SIC.W9','NUM_SOSP.W9SOSP.W9','NUM_SUBA.W9SUBA.W9','NUM_PUBB.W9PUBLOTTO.W9','FASE_ESECUZIONE.W9DOCFASE.W9', 'NUM_PUBB.W9DOCGARA.W9', 'NUMXML.W9XMLANOM.W9','NUM_ACCO.W9ACCO.W9');
		UPDATE C0CAMPI SET COC_CONTA=4 WHERE COC_MNE_UNI IN ('NUM_AGGI.W9AGGI.W9','NUM_FINA.W9FINA.W9','NUM_INCA.W9INCA.W9','NUM_IMP.W9CANTIMP.W9','NUM_MOTI.W9MOTI.W9','NUM_PUBB.W9PUBB.W9','NUM_PUES.W9PUES.W9','NUM_REQU.W9REQU.W9','NUM_FASE.W9DOCFASE.W9','NUM.W9XMLANOM.W9','NUM.W9FASI.W9');
		UPDATE C0CAMPI SET COC_CONTA=5 WHERE COC_MNE_UNI IN ('NUMDOC.W9DOCFASE.W9','SEZIONE.W9INCA.W9');
		UPDATE C0CAMPI SET COC_CONTA=2 WHERE COC_MNE_UNI IN ('NUM_PUBB.W9PUBBLICAZIONI.W9','NUMDOC.W9DOCGARA.W9') AND C0C_CHI='P';

		UPDATE C0CAMPI SET COC_CONTA=1 WHERE COC_MNE_UNI IN ('CODEIN.AVVISO.W9','IDCENTRO.CENTRICOSTO.W9','IDFLUSSO.W9FLUSSI.W9','IDCOMUN.W9INBOX.W9','CODCONF.W9CF_MODPERMESSI_SA.W9','CODCONF.W9CF_REGPERMESSI.W9','IDMACROFASE.W9CF_MACROFASI.W9','NUMREG.W9PERMESSI.W9','IDFLUSSO.V_W9FLUSSI.W9','IDFLUSSO.W9FLUSSI_ELIMINATI.W9','IDCOMUN.V_W9INBOX.W9','ID.UFFICI.W9');
		UPDATE C0CAMPI SET COC_CONTA=2 WHERE COC_MNE_UNI IN ('IDAVVISO.AVVISO.W9','CODEIN.W9CF_MODPERMESSI_SA.W9','NUMREG.W9CF_REGPERMESSI.W9','IDSCHEDA.W9CF_MACROFASI.W9');
		UPDATE C0CAMPI SET COC_CONTA=3 WHERE COC_MNE_UNI IN ('CODSISTEMA.AVVISO.W9','NUM_APPAF.W9APPAFORN.W9','NUM_APPAL.W9APPALAV.W9','NUM_AVAN.W9AVAN.W9');
		UPDATE C0CAMPI SET COC_CONTA=4 WHERE COC_MNE_UNI IN ('DEST.W9CANTDEST.W9');
		
		UPDATE C0CAMPI SET COC_DES='Data fine prevista per ultimazione lavori/servizi/forniture',COC_DES_FRM='Data fine prevista',COC_DES_WEB='Data fine prevista per dare ultimazione ai lavori/servizi/forniture' WHERE COC_MNE_UNI='DATA_TERMINE.W9INIZ.W9';
		UPDATE C0CAMPI SET COC_DES='Numero progressivo atto',COC_DES_FRM='Numero atto',COC_DES_WEB='Numero progressivo atto'  WHERE C0C_MNE_BER='W9PBNUMPUBB';

		--- Tipo di importo ---
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z01','M','M','A misura');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z01','C','C','A corpo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z01','E','E','In economia');

		--- Singolo o Commissione ---
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z02','S','S','Singolo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z02','C','C','Commissione');

		--- Tipologia di variante ---
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z03','A','A','In aumento');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z03','D','D','In diminuzione');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z03','S','S','Senza variazioni di importo');

		--- Livello progettuale ---
		INSERT INTO TAB1 (TAB1COD,TAB1TIP, TAB1DESC) VALUES ('W9021',1,'Studio di fattibilita'' tecnico economica');
		INSERT INTO TAB1 (TAB1COD,TAB1TIP, TAB1DESC) VALUES ('W9021',2,'Progetto preliminare');
		INSERT INTO TAB1 (TAB1COD,TAB1TIP, TAB1DESC) VALUES ('W9021',3,'Progetto definitivo');
		INSERT INTO TAB1 (TAB1COD,TAB1TIP, TAB1DESC) VALUES ('W9021',4,'Progetto esecutivo');

		--- Tabellato per la conversione del codice nazione NAZIMP (Ag010) in StatoEsteroType
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AD','16','Andorra');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AE','17','Emirati Arabi Uniti');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AF','18','Afghanistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AG','19','Antigua e Barbuda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AI','20','Anguilla');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AL','21','Albania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AM','22','Armenia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AN','23','Antille Olandesi');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AO','24','Angola');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AQ','25','Antartico');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AR','26','Argentina');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AS','27','Samoa Americane');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AT','2','Austria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AU','28','Australia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AW','29','Aruba');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AX','30','Isole Aland');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','AZ','31','Azerbaigian');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BA','32','Bosnia-Erzegovina');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BB','33','Barbados');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BD','34','Bangladesh');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BE','3','Belgio');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BF','35','Burkina Faso');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BG','36','Bulgaria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BH','37','Bahrain');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BI','38','Burundi');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BJ','39','Benin');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BL','40','Saint-Barthelemy');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BM','41','Bermuda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BN','42','Brunei');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BO','43','Bolivia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BR','44','Brasile');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BS','45','Bahamas');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BT','46','Bhutan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BV','47','Isola Bouvet');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BW','48','Botswana');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BY','49','Bielorussia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','BZ','50','Belize');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CA','51','Canada');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CC','52','Isole Cocos');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CD','53','Repubblica Democratica del Congo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CF','54','Repubblica Centrafricana');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CG','55','Repubblica del Congo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CH','56','Svizzera');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CI','57','Costa d''Avorio');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CK','58','Isole Cook');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CL','59','Cile');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CM','60','Camerun');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CN','61','Cina');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CO','62','Colombia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CR','63','Costa Rica');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CU','64','Cuba');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CV','65','Capo Verde');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CX','66','Isola Christmas');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CY','67','Cipro');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','CZ','68','Repubblica Ceca');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DE','7','Germania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DJ','69','Gibuti');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DK','4','Danimarca');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DM','70','Dominica');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DO','71','Repubblica Dominicana');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','DZ','72','Algeria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','EC','73','Ecuador');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','EE','74','Estonia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','EG','75','Egitto');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','EH','76','Sahara Occidentale');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ER','77','Eritrea');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ES','14','Spagna');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ET','78','Etiopia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FI','5','Finlandia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FJ','79','Figi');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FK','80','Isole Falkland');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FM','81','Stati Federati di Micronesia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FO','82','Isole Faorer');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','FR','6','Francia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GA','83','Gabon');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GB','13','Regno Unito');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GD','84','Grenada');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GE','85','Georgia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GF','86','Guyana Francese');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GG','87','Guernsey');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GH','88','Ghana');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GI','89','Gibilterra');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GL','90','Groenlandia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GM','91','Gambia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GN','92','Guinea');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GP','93','Guadalupa');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GQ','94','Guinea Equatoriale');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GR','8','Grecia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GS','95','Georgia del Sud e isole Sandwich meridionali');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GT','96','Guatemala');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GU','97','Guam');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GW','98','Guinea-Bissau');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','GY','247','Guyana');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HK','100','Hong Kong');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HM','101','Isole Heard e McDonald');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HN','102','Honduras');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HR','103','Croazia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HT','104','Haiti');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','HU','105','Ungheria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ID','106','Indonesia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IE','9','Irlanda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IL','107','Israele');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IM','108','Isola di Man');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IN','109','India');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IO','110','Territori Britannici dell''Oceano Indiano');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IQ','111','Iraq');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IR','112','Iran');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IS','113','Islanda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','JE','114','Jersey');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','JM','115','Giamaica');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','JO','116','Giordania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','JP','117','Giappone');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KE','118','Kenya');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KG','119','Kirghizistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KH','120','Cambogia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KI','121','Kiribati');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KM','122','Comore');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KN','123','Saint Kitts e Nevis');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KP','124','Corea del Nord');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KR','125','Corea del Sud');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KW','126','Kuwait');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KY','127','Isole Cayman');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','KZ','128','Kazakistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LA','129','Laos');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LB','130','Libano');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LC','131','Santa Lucia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LI','132','Liechtenstein');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LK','133','Sri Lanka');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LR','134','Liberia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LS','135','Lesotho');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LT','136','Lituania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LU','10','Lussemburgo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LV','137','Lettonia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','LY','138','Libia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MA','139','Marocco');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MC','140','Monaco');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MD','141','Moldavia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ME','142','Montenegro');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MF','143','Saint-Martin');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MG','144','Madagascar');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MH','145','Isole Marshall');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MK','146','Macedonia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ML','147','Mali');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MM','148','Birmania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MN','149','Mongolia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MO','150','Macao');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MP','151','Isole Marianne Settentrionali');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MQ','152','Martinica');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MR','153','Mauritania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MS','154','Montserrat');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MT','155','Malta');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MU','156','Mauritius');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MV','157','Maldive');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MW','158','Malawi');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MX','159','Messico');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MY','160','Malesia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','MZ','161','Mozambico');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NA','162','Namibia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NC','163','Nuova Caledonia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NE','164','Niger');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NF','165','Isola Norfolk');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NG','166','Nigeria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NI','167','Nicaragua');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NL','11','Olanda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NO','168','Norvegia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NP','169','Nepal');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NR','170','Nauru');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NU','171','Niue');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','NZ','172','Nuova Zelanda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','OM','173','Oman');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PA','174','Panama');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PE','175','Peru''');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PF','176','Polinesia Francese');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PG','177','Papua Nuova Guinea');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PH','178','Filippine');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PK','179','Pakistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PL','180','Polonia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PM','181','Saint Pierre e Miquelon');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PN','182','Isole Pitcairn');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PR','183','Porto Rico');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PS','184','Territori Palestinesi Occupati');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PT','12','Portogallo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PW','185','Palau');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','PY','186','Paraguay');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','QA','187','Qatar');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','RE','188','Reunion');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','RO','189','Romania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','RS','190','Serbia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','RU','191','Russia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','RW','192','Ruanda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SA','193','Arabia Saudita');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SB','194','Isole Salomone');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SC','195','Seychelles');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SD','196','Sudan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SE','15','Svezia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SG','197','Singapore');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SH','198','Sant''Elena');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SI','199','Slovenia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SJ','200','Svalbard');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SK','201','Slovacchia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SL','202','Sierra Leone');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SM','203','San Marino');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SN','204','Senegal');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SO','205','Somalia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SR','206','Suriname');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ST','207','Sao Tome''e Principe');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SV','208','El Salvador');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SY','209','Siria');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','SZ','210','Swaziland');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TC','211','Isole Turks e Caicos');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TD','212','Ciad');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TF','213','Territori Francesi del Sud');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TG','214','Togo');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TH','215','Thailandia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TJ','216','Tagikistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TK','217','Tokelau');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TL','218','Timor Est');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TM','219','Turkmenistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TN','220','Tunisia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TO','221','Tonga');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TR','222','Turchia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TT','223','Trinidad e Tobago');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TV','224','Tuvalu');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TW','225','Repubblica di Cina');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','TZ','226','Tanzania');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','UA','227','Ucraina');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','UG','228','Uganda');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','UM','229','Isole minori esterne degli Stati Uniti');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','US','230','Stati Uniti d''America');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','UY','231','Uruguay');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','UZ','232','Uzbekistan');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VA','233','Citta''del Vaticano');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VC','234','Saint Vincent e Grenadine');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VE','235','Venezuela');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VG','236','Isole Vergini Britanniche');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VI','237','Isole Vergini Americane');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VN','238','Vietnam');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','VU','239','Vanuatu');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','WF','240','Wallis e Futuna');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','WS','241','Samoa');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','YE','242','Yemen');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','YT','243','Mayotte');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ZA','244','Sudafrica');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ZM','245','Zambia');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','ZW','246','Zimbabwe');
		INSERT INTO TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) VALUES ('W9z04','IT','1','Italia');
		
		Delete from TAB2 where TAB2COD='W3z15' and TAB2TIP='2';
		Delete from TAB2 where TAB2COD='W3z15' and TAB2TIP='5';
		Delete from TAB2 where TAB2COD='W3z15' and TAB2TIP='6';

		Delete from TAB2 where TAB2COD='W3z16' and TAB2TIP='3';
		Delete from TAB2 where TAB2COD='W3z16' and TAB2TIP='4';
		
		--- W_OGGETTI ---
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.XML-REGLIGURIA','Integrazione Osservatorio Regione Liguria',6040);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('MASC','W9.ListaUffici','Lista uffici/aree di pertinenza',6050);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('MASC','W9.SchedaUffici','Scheda ufficio/area di pertinenza',6060);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.W9FasiDiGara-schede.ControlloDatiInseriti','Controllo dati inseriti per tutte le fasi',6070);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.W9FASI-lista.NuovoInvio','Invio delle Fasi',6080);

		--- W_AZIONI ---
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('FUNZ','VIS','ALT.W9.XML-REGLIGURIA','Visualizza',0,1,1,380417339);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','GENE.IMPR.TIPIMP','Visualizza',0,1,1,3961689214);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','GENE.IMPR.NINPS','Visualizza',0,1,1,374426080);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.UFFICI.CODICE_UFFICIO','Visualizza',0,1,1,852369789);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9APPA.FIN_REGIONALE','Visualizza',0,1,1,743479047);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9APPA.FLAG_IMPORTI','Visualizza',0,1,1,2822594622);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9APPA.FLAG_SICUREZZA','Visualizza',0,1,1,2218262908);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9APPA.FLAG_LIVELLO_PROGETTUALE','Visualizza',0,1,1,2569052933);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9APPA.VERIFICA_CAMPIONE','Visualizza',0,1,1,2986606718);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9AVAN.SUBAPPALTI','Visualizza',0,1,1,2284810500);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9VARI.FLAG_VARIANTE','Visualizza',0,1,1,2026986704);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9VARI.QUINTO_OBBLIGO','Visualizza',0,1,1,1556911898);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9VARI.FLAG_IMPORTI','Visualizza',0,1,1,2396779207);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9VARI.FLAG_SICUREZZA','Visualizza',0,1,1,1598525190);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.FLAG_SINGOLO_COMMISSIONE','Visualizza',0,1,1,3602743858);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_APPROVAZIONE','Visualizza',0,1,1,3353983221);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.FLAG_IMPORTI','Visualizza',0,1,1,315243894);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.FLAG_SICUREZZA','Visualizza',0,1,1,2839696335);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.FLAG_SUBAPPALTATORI','Visualizza',0,1,1,3578306268);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_INIZIO_AMM_RISERVE','Visualizza',0,1,1,1216645332);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_INIZIO_ARB_RISERVE','Visualizza',0,1,1,2842125386);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_INIZIO_GIU_RISERVE','Visualizza',0,1,1,2062234358);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_INIZIO_TRA_RISERVE','Visualizza',0,1,1,1021895867);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_FINE_AMM_RISERVE','Visualizza',0,1,1,3954796485);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_FINE_ARB_RISERVE','Visualizza',0,1,1,173706075);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_FINE_GIU_RISERVE','Visualizza',0,1,1,3654737383);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) values ('COLS','VIS','W9.W9COLL.DATA_FINE_TRA_RISERVE','Visualizza',0,1,1,2681539498);
		
		Update TAB1 set TAB1DESC='In fase di pubblicazione o affidamento' where TAB1COD='W9007' and TAB1TIP=1;
		Update TAB1 set TAB1DESC='Concluso in attesa di collaudo' where TAB1COD='W9007' and TAB1TIP=6;
		Update TAB1 set TAB1DESC='Monitoraggio terminato' where TAB1COD='W9007' and TAB1TIP=7;
		
		-- Ricalcolo la situazione
		Update W9LOTT l set SITUAZIONE=null where situazione <=8;
		Update W9LOTT l set SITUAZIONE=8 where exists (select 1 from W9ESITO t join W9FASI f on t.CODGARA=f.CODGARA and t.CODLOTT=f.CODLOTT join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE=984 and l.CODGARA=t.CODGARA and l.CODLOTT=t.CODLOTT AND t.ESITO_PROCEDURA>1) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=5 where exists (select 1 from W9SOSP t join W9FASI f  on t.CODGARA=f.CODGARA and t.CODLOTT=f.CODLOTT join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE=6 and l.CODGARA=t.CODGARA and l.CODLOTT=t.CODLOTT AND t.DATA_VERB_RIPR IS NULL) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=7 where exists (select 1 from W9FASI f join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE in (5,11,985) and l.CODGARA=i.KEY01 and l.CODLOTT=i.KEY02 ) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=6 where exists (select 1 from W9FASI f join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE =4 and l.CODGARA=i.KEY01 and l.CODLOTT=i.KEY02) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=4 where exists (select 1 from W9FASI f join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE =3 and l.CODGARA=i.KEY01 and l.CODLOTT=i.KEY02) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=3 where exists (select 1 from W9FASI f join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE in (2,986) and l.CODGARA=i.KEY01 and l.CODLOTT=i.KEY02) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=2 where exists (select 1 from W9FASI f join W9FLUSSI i on f.CODGARA=i.KEY01 and f.CODLOTT=i.KEY02 where f.FASE_ESECUZIONE in (1,987,12) and l.CODGARA=i.KEY01 and l.CODLOTT=i.KEY02) and SITUAZIONE is null;
		Update W9LOTT l set SITUAZIONE=1 where SITUAZIONE is null;

		Update W9GARA g set SITUAZIONE=null where situazione <=8;
		Update W9GARA g set SITUAZIONE=8 where exists (select 1 from W9LOTT l where l.SITUAZIONE=8 and g.CODGARA=l.CODGARA) and not exists(select 1 from W9LOTT l where l.SITUAZIONE<>8 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=1 where exists (select 1 from W9LOTT l where l.SITUAZIONE=1 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=2 where exists (select 1 from W9LOTT l where l.SITUAZIONE=2 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=3 where exists (select 1 from W9LOTT l where l.SITUAZIONE=3 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=4 where exists (select 1 from W9LOTT l where l.SITUAZIONE=4 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=5 where exists (select 1 from W9LOTT l where l.SITUAZIONE=5 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=6 where exists (select 1 from W9LOTT l where l.SITUAZIONE=6 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;
		Update W9GARA g set SITUAZIONE=7 where exists (select 1 from W9LOTT l where l.SITUAZIONE=7 and g.CODGARA=l.CODGARA) and SITUAZIONE is null;

		Delete from W_OGGETTI where oggetto='W9.W9LOTT-scheda.PUBBLICAZIONI';
		Insert into W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('PAGE','W9.W9LOTT-scheda.PUBBLICAZIONI','Scheda lotto - Pagina Pubblicazioni',6020);
		
		-- Correzione c0campi
		Delete from c0campi where coc_mne_uni = 'IMP_COMPL_INTERVENTO.W9VARI';
		
		--Aggiornamento all'elenco atti
		Update W9CF_PUBB set NUMORD=NUMORD*10;
		Delete from W9CF_PUBB where ID=14;
		Insert into W9CF_PUBB (ID,NOME,NUMORD,CL_WHERE_VIS,CAMPI_VIS) values(14,'Provvedimento di adesione',140,'L.ID_SCELTA_CONTRAENTE_50 in (10,11)','DATAPUBB|DATA_PROVVEDIMENTO|NUM_PROVVEDIMENTO|');
		Update W9CF_PUBB set CL_WHERE_VIS='L.ID_SCELTA_CONTRAENTE_50<>10' where ID in (1,20);
		Update W9CF_PUBB set CL_WHERE_VIS='L.ID_SCELTA_CONTRAENTE_50 IN (6,8,23,24)' where ID =2;
		Update W9CF_PUBB set CL_WHERE_VIS='L.ID_SCELTA_CONTRAENTE_50 not in (10,11)' where ID =13;
		Update W9CF_PUBB set CL_WHERE_VIS='L.ID_SCELTA_CONTRAENTE_50 IN (2,3,9,11,13,14,24)' where ID=15;
		Update W9CF_PUBB set CL_WHERE_VIS='L.ID_SCELTA_CONTRAENTE_50 NOT IN (10,15,16)' where ID in (22,23,24);
		Update W9CF_PUBB set CL_WHERE_VIS='1=2' where ID=21;
		Update W9CF_PUBB set NOME='Provvedimento di revoca dell''aggiudicazione o dell''adesione' where ID=16;
		
		--Aggiornamento requisiti gara per richiesta CIG
		Delete from W3TABREQ;

		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('34','USO: SISTEMA RISCOSSIONE 31 - DIMOSTRAZIONE DEL VERSAMENTO DEL CONTRIBUTO AD ANAC','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('35','USO: SISTEMA ANNOTAZIONI 32 - ASSENZA DI ISCRIZIONI NEL CASELLARIO INFORMATICO DEI CONTRATTI PUBBLICI CHE COMPORTANO L&apos;ESCLUSIONE DALLA PROCEDURA DI AFFIDAMENTO','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('36','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-PER AGGIUDICAZIONE ED ESECUZIONE LAVORI-NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('37','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-TECNICO-PROFESSIONALI-NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('38','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-IDONEITA&apos; PROFESSIONALE-NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('39','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-ECONOMICO-FINANZIARI-NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('40','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-GARANZIA DI QUALITA&apos; - NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('41','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE SPECIALE-SISTEMA DI GESTIONE AMBIENTALE - NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('42','USO: FACOLTATIVO 39 - IDONEITA&apos; PROFESSIONALE','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('43','USO: FACOLTATIVO 40 - ISCRIZIONE AD ORDINI PROFESSIONALI','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('53','USO: FACOLTATIVO 50 - TITOLI DI STUDIO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('54','USO: FACOLTATIVO 51 - TITOLI PROFESSIONALI','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('55','USO: FACOLTATIVO 52 - POSSESSO DI UN SISTEMA DI QUALITA&apos; CONFORME ALLA NORMATIVA UNI EN ISO 9000','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('57','USO: FACOLTATIVO 54 - POSSESSO DI UN ADEGUATO SISTEMA DI GESTIONE AMBIENTALE (SGA)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('58','USO: FACOLTATIVO 999 - REQUISITO DI ORDINE GENERALE - NON CLASSIFICATO','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('59','USO: OBBLIGATORIO 01 - ASSENZA DI STATO DI FALLIMENTO, LIQUIDAZIONE COATTA O CONCORDATO PREVENTIVO O DI PROCEDIMENTO PER LA DICHIARAZIONE DI TALI SITUAZIONI (ART. 38, COMMA 1, LETT. A) D.LGS. 163/06)','1','15');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('60','USO: OBBLIGATORIO 04 - ASSENZA DI PROCEDIMENTI PER L&apos;APPLICAZIONE DI UNA DELLE MISURE DI PREVENZIONE DI CUI ALL&apos;ART. 6 -- D.LGS. 159/11 O DI UNA DELLE CAUSE OSTATIVE DI CUI ART. 67 D.LGS. 159/11 (ART. 38, COMMA 1, LETT. B) D.LGS. 163/06)','1','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('61','USO: OBBLIGATORIO 05 - ASSENZA DI SENTENZE DI CONDANNA PASSATE IN GIUDICATO, O DI DECRETI PENALI DI CONDANNA IRREVOCABILI, O DI SENTENZE EX ART.444 C.P.P. PER REATI GRAVI IN DANNO DELLO STATO O DELLA COMUNIT&#192; CHE INCIDONO SULLA MORALIT&#192; PROFESSIONALE, NONCH&#200; DI CONDANNE, CON SENTENZE PASSATE IN GIUDICATO, PER UNO O PI&#217; REATI DI PARTECIPAZIONE A UN&apos;ORGANIZZAZIONE CRIMINALE, CORRUZIONE, FRODE, RICICLAGGIO (ART. 38, COMMA 1, LETT. C) D.LGS. 163/06)','1','4');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('62','USO: OBBLIGATORIO 06 - INSUSSISTENZA DI VIOLAZIONI DEL DIVIETO DI INTESTAZIONE FIDUCIARIA DI CUI ALL&apos;ART. 17 L. 55/90 (ART. 38, COMMA 1, LETT. D), D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('63','USO: OBBLIGATORIO 07 - ASSENZA DI ISCRIZIONI RELATIVE A GRAVI INFRAZIONI DEBITAMENTE ACCERTATE ALLE NORME IN MATERIA DI SICUREZZA E A OGNI ALTRO OBBLIGO DERIVANTE DAI RAPPORTI DI LAVORO (ART. 38, COMMA 1, LETT. E), D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('64','USO: OBBLIGATORIO 08 - ASSENZA DI ISCRIZIONI RELATIVE ALLA PRESENTAZIONE DI FALSA DICHIARAZIONE O FALSA DOCUMENTAZIONE IN MERITO A REQUISITI E CONDIZIONI RILEVANTI PER LA PARTECIPAZIONE A PROCEDURE DI GARA E PER L&apos;AFFIDAMENTO DEI SUBAPPALTI  (ART. 38, COMMA 1, LETT. H), D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('65','USO: OBBLIGATORIO 09 - ASSENZA DI ISCRIZIONI RELATIVE ALLA PRESENTAZIONE DI FALSA DICHIARAZIONE O FALSA DOCUMENTAZIONE AI FINI DEL RILASCIO DELL&apos;ATTESTAZIONE SOA (ART. 38, COMMA 1, LETT. M-BIS), D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('66','USO: OBBLIGATORIO 10 - ASSENZA DI SOGGETTI, TRA QUELLI DI CUI ALL&apos;ART. 38, COMMA 1, LETT. B) DEL D.LGS. 163/06, CHE ABBIANO OMESSO DENUNCIA DEI REATI DI CUI AGLI ARTT. 317 E 629 C.P., AGGRAVATI EX ART. 7, D.L. 152/91 (ART. 38, COMMA 1, LETT. M-TER D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('67','USO: OBBLIGATORIO 11 - ASSENZA DI EPISODI DI GRAVE NEGLIGENZA O MALAFEDE NELL&apos;ESECUZIONE DELLE PRESTAZIONI AFFIDATE DALLA STAZIONE APPALTANTE CHE BANDISCE LA GARA (ART. 38, COMMA 1, LETT. F) D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('68','USO: OBBLIGATORIO 12 - ASSENZA DI EPISODI DI ERRORE GRAVE NELL&apos;ESERCIZIO DELL&apos;ATTIVITA&apos; PROFESSIONALE (ART. 38, COMMA 1, LETT. F) D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('69','USO: OBBLIGATORIO 13 - INSUSSISTENZA DI VIOLAZIONI GRAVI, DEFINITIVAMENTE ACCERTATE, RISPETTO AGLI OBBLIGHI RELATIVI AL PAGAMENTO DELLE IMPOSTE E DELLE TASSE (ART. 38, COMMA 1, LETT. G) D.LGS. 163/06)','1','10');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('70','USO: OBBLIGATORIO 14 - INSUSSISTENZA DI VIOLAZIONI GRAVI, DEFINITIVAMENTE ACCERTATE, ALLE NORME IN MATERIA DI CONTRIBUTI PREVIDENZIALI E ASSISTENZIALI (ART. 38, COMMA 1, LETT. I) D.LGS. 163/06)','1','11-52-35');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('71','USO: OBBLIGATORIO 16 - REGOLARITA&apos; DELL&apos;IMPRESA RISPETTO ALLE NORME CHE DISCIPLINANO IL DIRITTO AL LAVORO DEI DISABILI L. 68/99 (ART. 38, COMMA 1, LETT. L), D.LGS. 163/06)','1','12');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('72','USO: OBBLIGATORIO 19 - ASSENZA DELLA SANZIONE INTERDITTIVA DI CUI ALL&apos;ART. 9, COMMA 2, LETT. C), DEL D.LGS. 231/01  (ART. 38, COMMA 1, LETT. M) D.LGS. 163/06)','1','20');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('73','USO: OBBLIGATORIO 20 - ASSENZA DI SANZIONI COMPORTANTI IL DIVIETO DI CONTRARRE CON LA PUBBLICA AMMINISTRAZIONE COMPRESI I PROVVEDIMENTI INTERDITTIVI EX ART. 14 D.LGS. 81/08 (ART. 38, COMMA 1, LETT. M) D.LGS. 163/06)','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('74','USO: OBBLIGATORIO 21 - ASSENZA DI DIVIETO A  CONTRARRE CON LA PUBBLICA AMMINISTRAZIONE EX ART. 32-QUATER C.P.','1','2');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('75','USO: FACOLTATIVO 22 - ASSENZA DI UNA SITUAZIONE DI CONTROLLO EX ART. 2359 C.C. O DI ALTRA RELAZIONE, ANCHE DI FATTO, SE LA SITUAZIONE DI CONTROLLO O LA RELAZIONE COMPORTINO L&apos;IMPUTABILITA&apos; DELLE OFFERTE AD UN UNICO CENTRO DECISIONALE (ART. 38, COMMA 1, LETT. M-QUATER), D.LGS. 163/06)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('76','USO: FACOLTATIVO 24 - ASSENZA DI ATTI O COMPORTAMENTI DISCRIMINATORI PER MOTIVI RAZZIALI, ETNICI, NAZIONALI O RELIGIOSI','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('77','USO: FACOLTATIVO 46 - IMPORTO DEI LAVORI ANALOGHI ESEGUITI DIRETTAMENTE NEL QUINQUENNIO ANTECEDENTE LA DATA DI PUBBLICAZIONE DEL BANDO (ART. 90, COMMA 1, LETT. A), D.P.R. 207/10)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('78','USO: FACOLTATIVO 47 - COSTO COMPLESSIVO SOSTENUTO PER IL PERSONALE (ART. 90, COMMA 1, LETT. B), D.P.R. 207/10)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('79','USO: FACOLTATIVO 48 - POSSESSO DI ADEGUATA ATTREZZATURA TECNICA (ART. 90, COMMA 1, LETT. C), D.P.R. 207/10)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('80','USO: FACOLTATIVO 51 - CAPACITA ECONOMICA E FINANZIARIA DI CUI ALL&apos;ART 41 COMMA 1, D.LGS. 163/06','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('81','USO: FACOLTATIVO 55 - CAPACITA&apos; TECNICA E PROFESSIONALE DIMOSTRATA MEDIANTE ELENCO DEI PRINCIPALI SERVIZI O DELLE PRINCIPALI FORNITURE PRESTATI NEGLI ULTIMI TRE ANNI (ART. 42, COMMA 1, LETT. A) D.LGS. 163/06)','2','');
		Insert into W3TABREQ(CODICE_DETTAGLIO, DESCRIZIONE, INIZIALE, DOCUMENTI_DEFAULT) values('82','USO: FACOLTATIVO 55 - QUALIFICAZIONE PER ESEGUIRE LAVORI PUBBLICI DI IMPORTO SUPERIORE AD &#8364; 150.000','2','');

		Insert into TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD,TAB1ARC) values ('W3020',981,'Programma Triennale Opere Pubbliche',null,1,null);
		Insert into TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD,TAB1ARC) values ('W3020',982,'Programma Biennale Acquisti',null,2,null);
		
		Update W_CONFIG set VALORE='3.2.0' where CODAPP='W9' and CHIAVE='"it.eldasoft.sitatproxy.versioneTracciatoXML';
		Update W_CONFIG set VALORE='3.2.0' where CODAPP='W9' and CHIAVE='"it.eldasoft.rt.sitatproxy.versioneTracciatoXML';

		Update ELDAVER set NUMVER='3.2.0', DATVET=CURRENT_TIMESTAMP where CODAPP='W9';		
	END IF;
end@

call aggiorna@
drop procedure aggiorna@



--#SET TERMINATOR ;

Update COMMAND OPTIONS USING s OFF;
DROP procedure ASSEGNA_GRANT;
Update COMMAND OPTIONS USING s ON;

--#SET TERMINATOR @

CREATE PROCEDURE ASSEGNA_GRANT ()
BEGIN
  DECLARE EOF INT DEFAULT 0;
  DECLARE S_SQL VARCHAR(200);
  DECLARE S_TABELLA VARCHAR(50);
  DECLARE S_USER VARCHAR(50);
  
  DECLARE C1 CURSOR FOR select TABNAME from SYSCAT.TABLES where TABSCHEMA =CURRENT SCHEMA and status='N';
  DECLARE C2 CURSOR FOR select SEQNAME from SYSCAT.SEQUENCES where SEQSCHEMA =CURRENT SCHEMA;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET EOF = 1;

	SET S_USER=CURRENT SCHEMA;
	SET S_USER=S_USER || ',SSELDAS';	--------		Utente Eldasoft		----------------
	SET S_USER=S_USER || ',LM07421';	--------	Utente Luca Menegatti	----------------

  OPEN C1;
  WHILE EOF = 0 DO
    FETCH FROM C1 INTO S_TABELLA;
  	SET S_SQL = 'GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE ' || S_TABELLA || ' TO USER ' || S_USER;
  	EXECUTE IMMEDIATE S_SQL;
  END WHILE;
  CLOSE C1;


  OPEN C2;
  WHILE EOF = 0 DO
    FETCH FROM C2 INTO S_TABELLA;
  	SET S_SQL = 'GRANT USAGE ON SEQUENCE ' || S_TABELLA || ' TO ' || S_USER;
  	EXECUTE IMMEDIATE S_SQL;
  END WHILE;
  CLOSE C2;
END@

call ASSEGNA_GRANT@
drop procedure ASSEGNA_GRANT@
Update COMMAND OPTIONS USING s ON@

--#SET TERMINATOR ;

