------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------


ALTER TABLE SITATORT.W9ESITO ADD COLUMN DATA_VERB_AGGIUDICAZIONE TIMESTAMP;
ALTER TABLE SITATORT.W9ESITO ADD COLUMN IMPORTO_AGGIUDICAZIONE NUMERIC(24,5);
REORG TABLE SITATORT.W9ESITO;

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DATA_VERB_AGGIUDICAZIONE.W9ESITO.W9','W3ESDVERB','Data di aggiudicazione definitiva','Data aggiudicazione','A10',null,'DATA_ELDA','Data aggiudicazione definitiva');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'IMPORTO_AGGIUDICAZIONE.W9ESITO.W9','W3ESIMP_AGGI','Importo di aggiudicazione','Imp. aggiudicazione','F15',null,'MONEY','Importo di aggiudicazione');

Update SITATORT.W9ESITO e SET DATA_VERB_AGGIUDICAZIONE=(Select DATA_VERB_AGGIUDICAZIONE from SITATORT.W9APPA a WHERE e.CODGARA=a.CODGARA and e.CODLOTT=a.CODLOTT);
Update SITATORT.W9ESITO e SET IMPORTO_AGGIUDICAZIONE=(Select IMPORTO_AGGIUDICAZIONE from SITATORT.W9APPA a WHERE e.CODGARA=a.CODGARA and e.CODLOTT=a.CODLOTT);


UPDATE SITATORT.ELDAVER Set numver='2.1.1' where codapp='W9';

CREATE or replace view SITATORT.V_PUBB_APPA
(CODGARA,CODLOTT,NUM_APPA,PROCEDURA_ACC,PREINFORMAZIONE,
TERMINE_RIDOTTO,ID_MODO_INDIZIONE,NUM_IMPRESE_INVITATE,NUM_IMPRESE_RICHIEDENTI,NUM_IMPRESE_OFFERENTI,
NUM_OFFERTE_AMMESSE,DATA_VERB_AGGIUDICAZIONE,DATA_SCADENZA_RICHIESTA_INVITO,DATA_SCADENZA_PRES_OFFERTA,IMPORTO_AGGIUDICAZIONE,
IMPORTO_LAVORI,IMPORTO_SERVIZI,IMPORTO_FORNITURE,IMPORTO_DISPOSIZIONE,IMPORTO_PROGETTAZIONE,
SISTEMA_QUALIFICAZIONE,CRITERI_SELEZIONE_STABILITI_SA,FLAG_ACCORDO_QUADRO,ASTA_ELETTRONICA,PERC_RIBASSO_AGG,
PERC_OFF_AUMENTO,DATA_INVITO,NUM_MANIF_INTERESSE,DATA_MANIF_INTERESSE,FLAG_RICH_SUBAPPALTO,
NUM_OFFERTE_ESCLUSE,OFFERTA_MASSIMO,OFFERTA_MINIMA,VAL_SOGLIA_ANOMALIA,NUM_OFFERTE_FUORI_SOGLIA,
NUM_IMP_ESCL_INSUF_GIUST,COD_STRUMENTO,IMPORTO_SUBTOTALE,IMPORTO_COMPL_APPALTO,IMPORTO_COMPL_INTERVENTO,
IMP_NON_ASSOG,ACQBENI,IMPBENI,IMPRICIC,ACQREPRIC,
IMPAMM1,IMPCAR1,IMPGOM1,IMPINE1,IMPLEG1,
IMPPLA1,IMPTES1,IMPAMM2,IMPCAR2,IMPGOM2,
IMPINE2,IMPLEG2,IMPPLA2,IMPTES2,IMPORTO_ATTUAZIONE_SICUREZZA,
FILE_ALLEGATO,NOMEFILE,ID_MODO_INDIZIONE_D,COD_STRUMENTO_D)
AS 
SELECT 
E.CODGARA,E.CODLOTT,COALESCE(NUM_APPA,0),PROCEDURA_ACC,PREINFORMAZIONE,
TERMINE_RIDOTTO,ID_MODO_INDIZIONE,NUM_IMPRESE_INVITATE,NUM_IMPRESE_RICHIEDENTI,NUM_IMPRESE_OFFERENTI,
NUM_OFFERTE_AMMESSE,date(COALESCE(A.DATA_VERB_AGGIUDICAZIONE,E.DATA_VERB_AGGIUDICAZIONE)),date(DATA_SCADENZA_RICHIESTA_INVITO),date(DATA_SCADENZA_PRES_OFFERTA),COALESCE(A.IMPORTO_AGGIUDICAZIONE,E.IMPORTO_AGGIUDICAZIONE),
IMPORTO_LAVORI,IMPORTO_SERVIZI,IMPORTO_FORNITURE,IMPORTO_DISPOSIZIONE,IMPORTO_PROGETTAZIONE,
SISTEMA_QUALIFICAZIONE,CRITERI_SELEZIONE_STABILITI_SA,FLAG_ACCORDO_QUADRO,ASTA_ELETTRONICA,PERC_RIBASSO_AGG,
PERC_OFF_AUMENTO,Date(DATA_INVITO),NUM_MANIF_INTERESSE,Date(DATA_MANIF_INTERESSE),FLAG_RICH_SUBAPPALTO,
NUM_OFFERTE_ESCLUSE,OFFERTA_MASSIMO,OFFERTA_MINIMA,VAL_SOGLIA_ANOMALIA,NUM_OFFERTE_FUORI_SOGLIA,
NUM_IMP_ESCL_INSUF_GIUST,COD_STRUMENTO,IMPORTO_SUBTOTALE,IMPORTO_COMPL_APPALTO,IMPORTO_COMPL_INTERVENTO,
IMP_NON_ASSOG,ACQBENI,IMPBENI,IMPRICIC,ACQREPRIC,
IMPAMM1,IMPCAR1,IMPGOM1,IMPINE1,IMPLEG1,
IMPPLA1,IMPTES1,IMPAMM2,IMPCAR2,IMPGOM2,
IMPINE2,IMPLEG2,IMPPLA2,IMPTES2,IMPORTO_ATTUAZIONE_SICUREZZA,
E.FILE_ALLEGATO,'Esito.pdf',tW3008.TAB1DESC,tW3z01.tab2d2
FROM SITATORT.W9ESITO E left outer join SITATORT.W9APPA A on A.CODGARA=E.CODGARA and A.CODLOTT=E.CODLOTT
left outer join (select * from SITATORT.tab1 where tab1cod='W3008') tW3008 on ID_MODO_INDIZIONE=tW3008.tab1tip
left outer join (select * from SITATORT.tab2 where tab2cod='W3z01') tW3z01 on COD_STRUMENTO=tW3z01.tab2tip

UNION ALL

SELECT 
idbando + 1000000000,1,1,'','',
'',0,CAST (NULL AS INTEGER),CAST (NULL AS INTEGER),CAST (NULL AS INTEGER),
CAST (NULL AS INTEGER),DataEsito,CAST (NULL AS DATE),CAST (NULL AS DATE),ImportoAggiudicato,
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
'','','','',CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DATE),CAST (NULL AS INTEGER),CAST (NULL AS DATE),'',
CAST (NULL AS INTEGER),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS INTEGER),
CAST (NULL AS INTEGER),'',CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),'2',CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),'2',
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
DatiAllegato1,NomeAllegato1,'',''
from SITATORT.esiti

UNION ALL

SELECT 
idEsitoSenza + 2000000000,1,1,'','',
'',0,CAST (NULL AS INTEGER),CAST (NULL AS INTEGER),CAST (NULL AS INTEGER),
CAST (NULL AS INTEGER),DataAffidamento,CAST (NULL AS DATE),CAST (NULL AS DATE),ImportoAffidato,
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
'','','','',CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DATE),CAST (NULL AS INTEGER),CAST (NULL AS DATE),'',
CAST (NULL AS INTEGER),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS INTEGER),
CAST (NULL AS INTEGER),'',CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),'2',CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),'2',
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),CAST (NULL AS DECIMAL),
DatiAllegato1,NomeAllegato1,'',''
from SITATORT.EsitiSenzaBando;


