------------------------------
-- AGGIORNAMENTO TABELLE SITAT	
------------------------------
-- GENE 1.4.39
-- GENEWEB 1.5.5
-- SITATSA 2.0.3
--------------------------

-- SITAT


UPDATE SITATSA.C0CAMPI SET COC_DES='Codice gara Autorità alla richiesta del CIG',COC_DES_WEB='Codice gara restituito dall''AVCP' where C0C_MNE_BER='W3IDGARA';
UPDATE SITATSA.C0CAMPI SET COC_DES='Principali carenze dell''impresa', COC_DES_WEB='Principali carenze dell''impresa' where C0C_MNE_BER='W3TPDESCARE';
UPDATE SITATSA.C0CAMPI SET COC_DES='Messaggio di errore', COC_DES_WEB='Messaggio di errore',COC_DES_FRM='Messaggio errore' where C0C_MNE_BER='W9IBMSG';

UPDATE SITATSA.TAB1 SET TAB1DESC = 'Esito negativo idoneità tecnico-professionale impresa' where TAB1COD = 'W3020' and TAB1TIP = 997;

--Profilo: SA_APPA
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.DANTIM',0,160075319);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPAZI',0,147612543);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPDTE',0,2570711371);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','SEZ','VIS','GENE.ImprScheda.DATIGEN.ISO1',0,900991630);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPDTE',0,1526828649);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPAZI',0,3404995677);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','SEZ','VIS','GENE.ImprScheda.DATIGEN.ABI',0,4156912262);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','MOD','W9.W9GARA.IDAVGARA',0,4149243513);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','MOD','W9.W9LOTT.CIG',0,2486431594);
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-APPA' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-APPA' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;

--Profilo: SA_ADMIN
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-ADMIN' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-ADMIN' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;

--Profilo: SA-AVVISI
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-AVVISI' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-AVVISI' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-AVVISI' AND TIPO = 'SEZ'  AND AZIONE = 'VIS' AND OGGETTO = 'GENE.ImprScheda.DATIGEN.CCIAA' AND VALORE = 0 AND CRC = 2016087763;

--Profilo: SA-PIATRI
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.DANTIM',0,160075319);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPAZI',0,147612543);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPDTE',0,2570711371);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','SEZ','VIS','GENE.ImprScheda.DATIGEN.ISO1',0,900991630);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPDTE',0,1526828649);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPAZI',0,3404995677);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','SEZ','VIS','GENE.ImprScheda.DATIGEN.ABI',0,4156912262);
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-PIATRI' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-PIATRI' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;
DELETE FROM SITATSA.W_PROAZI WHERE COD_PROFILO = 'SA-PIATRI' AND TIPO = 'SEZ'  AND AZIONE = 'VIS' AND OGGETTO = 'GENE.ImprScheda.DATIGEN.CCIAA' AND VALORE = 0 AND CRC = 2016087763;
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.DCCIAA',0,3154606715);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.DCERCC',0,2246961577);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.DISCIF',0,1402202500);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.NCERCC',0,563984103);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.PCCIAA',0,798409382);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','COLS','VIS','GENE.IMPR.REGDIT',0,1344076067);

UPDATE SITATSA.ELDAVER Set numver='2.0.3' where codapp='W9';