------------------------------
-- AGGIORNAMENTO TABELLE SITAT	
------------------------------
-- GENE 1.4.39
-- GENEWEB 1.5.5
-- SITATSA 2.0.4
--------------------------

-- SITAT

Insert into SITATSA.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'ALT.W9.W9GARA-scheda.InviaSimapRT', 'Invia bandi avvisi a SimapRT', 3140);
Insert into SITATSA.W_PROAZI (COD_PROFILO, TIPO, AZIONE, OGGETTO, VALORE, CRC) Values ('SA-APPA', 'FUNZ', 'VIS', 'ALT.W9.W9GARA-scheda.InviaSimapRT', 0, 1687406857);

ALTER TABLE SITATSA.AVVISO ALTER COLUMN DESCRI SET DATA TYPE VARCHAR(500); 
UPDATE SITATSA.C0CAMPI SET C0C_FS = 'A500', COC_DOM = 'NOTE' WHERE C0C_MNE_BER = 'W3PADESCRI';
REORG TABLE SITATSA.AVVISO;

ALTER TABLE SITATSA.PIATRI ALTER COLUMN BRETRI SET DATA TYPE VARCHAR(500); 
UPDATE SITATSA.C0CAMPI SET C0C_FS = 'A500', COC_DOM = 'NOTE' WHERE C0C_MNE_BER = 'T2BRETRI';
REORG TABLE SITATSA.PIATRI;

Update SITATSA.INTTRI SET DI1INT=BI1TRI + DV1TRI + IM1TRI + MU1TRI + AL1TRI WHERE DI1INT IS NULL or DI1INT=0;
Update SITATSA.INTTRI SET DI2INT=BI2TRI + DV2TRI + IM2TRI + MU2TRI + AL2TRI WHERE DI2INT IS NULL or DI2INT=0;
Update SITATSA.INTTRI SET DI3INT=BI3TRI + DV3TRI + IM3TRI + MU3TRI + AL3TRI WHERE DI3INT IS NULL or DI3INT=0;

Update SITATSA.INTTRI SET TOTINT=DITINT + ICPINT;

ALTER TABLE SITATSA.W9GARA ALTER COLUMN NLOTTI SET DATA TYPE NUMERIC(4);
ALTER TABLE SITATSA.W9LOTT ALTER COLUMN NLOTTO SET DATA TYPE NUMERIC(4);
UPDATE SITATSA.C0CAMPI SET C0C_FS='A4' WHERE C0C_MNE_BER like 'W3NLOTT_';
REORG TABLE SITATSA.W9GARA;
REORG TABLE SITATSA.W9LOTT;

UPDATE SITATSA.ELDAVER Set numver='2.0.4' where codapp='W9';