------ SCHEMA SITAT SA ----------
SET SCHEMA = SITATSA;
SET CURRENT PATH = SITATSA;


UPDATE COMMAND OPTIONS USING s OFF;
DROP procedure aggiorna;
UPDATE COMMAND OPTIONS USING s ON;

------ CARATTERE TERMINATORE ----------
--#SET TERMINATOR @


------------------------------------------------
---- AGGIORNAMENTO DEL PROFILO SA-PIATRI-RT ----
------------------------------------------------

Delete from W_ACCPRO where COD_PROFILO='SA-PIATRI-RT' and ID_ACCOUNT=50;
Delete from W_PROAZI where COD_PROFILO='SA-PIATRI-RT';
Delete from W_PROFILI where COD_PROFILO='SA-PIATRI-RT';

Insert into W_PROFILI (COD_PROFILO,CODAPP,NOME,DESCRIZIONE,FLAG_INTERNO,DISCRIMINANTE,COD_CLIENTE,CRC) values ('SA-PIATRI-RT','W9','Comunicazioni di programmi (Regione Toscana)','Comunicazioni di eventi di programmi di lavori, forniture e servizi (Regione Toscana)',1,null,1091,1270918309);

Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.IMPR.CFIMP',1,2065006782);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.IMPR.NOMEST',1,3277781792);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.TECNI.CFTEC',1,3376415354);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.TECNI.NOMTEC',1,3922502992);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.TEIM.NOMTIM',1,570191537);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','MAN','GENE.UFFINT.NOMEIN',1,231133415);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','*',1,4179291998);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.CATE.*',0,370569137);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPDTE.*',0,330687099);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.*',0,4259985762);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.CAPIMP',1,1055711822);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.CFIMP',1,3491673339);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.CODCIT',1,2640199616);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.EMAI2IP',1,2274275292);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.EMAIIP',1,1886847457);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.FAXIMP',1,1554286120);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.INDIMP',1,4272570007);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.LOCIMP',1,3589152389);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.NATGIUI',1,3278708774);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.NAZIMP',1,361470767);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.NCCIAA',1,1869616547);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.NCIIMP',1,2130958198);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.NOMEST',1,3309520139);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.PIVIMP',1,197727184);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.PROIMP',1,254284923);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.IMPR.TELIMP',1,2719250587);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.*',0,2991376634);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.CAPTEC',1,2262503981);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.CFTEC',1,3479026769);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.CITTEC',1,2668115584);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.CODTEC',0,1589015177);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.COGTEI',1,2499727429);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.EMATEC',1,3477690718);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.FAXTEC',1,3834869323);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.INDTEC',1,1184747252);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.LOCTEC',1,1842999014);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.MGSFLG',0,2713166260);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.NCITEC',1,3342083861);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.NOMETEI',1,3837335197);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.NOMTEC',1,1165377966);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.PROTEC',1,3072320536);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.TELTEC',1,438536440);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.WEBPWD',0,1014852124);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TECNI.WEBUSR',0,271746853);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.*',0,1916466235);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.CFTIM',1,1497752044);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.CODTIM',0,1008853949);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.COGTIM',1,210151931);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.NOMETIM',1,3897678699);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.TEIM.NOMTIM',1,669110426);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.CODEIN',0,1286571583);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.CODNAZ',0,3138619347);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.CODRES',0,1998027873);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.CODSTA',0,2864423568);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.DATICC',0,554502752);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.DNAEIN',0,2327110756);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.DOFEIN',0,4090031057);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.INDWEB',0,2084316072);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.IVAEIN',0,82183506);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.LNAEIN',0,3109792259);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.NUMICC',0,1892343888);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.PROICC',0,552494107);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.PROUFF',0,1100855954);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','GENE.UFFINT.USERID',0,921977655);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.RESPUF',1,1092694516);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.DADOZI',0,3740000945);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.DAPTRI',0,3263189717);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.NADOZI',0,2057027071);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.NAPTRI',0,1727008155);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.STATRI',0,1851973007);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.TADOZI',0,3107290751);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.PIATRI.TAPTRI',0,2774453787);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.ACQVERDI',1,4026006493);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.DIRGEN',1,381433749);
---Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.MATRIC',1,994321679);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.QUANTIT',1,3937949287);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.REFERE',1,2693057517);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.STRUOP',1,676045197);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.UNIMIS',1,1156269016);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.INTTRI.VALUTAZIONE',1,2541728618);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.RIS_CAPITOLO.IMPALTCB',1,2216124492);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.RIS_CAPITOLO.IMPRFSCB',1,3593613409);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','COLS','VIS','PIANI.RIS_CAPITOLO.RG1CB',1,2989739536);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.C0OGGASS',0,1888279893);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.G_NOTEAVVISI',0,4289628934);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.HELPPAGINA',0,2611775279);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.Homepage-EseguiReport',0,3712486845);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.UTENT-lista.HELPPAGINA',0,1352063578);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.UTENT-scheda.HELPPAGINA',0,2022395450);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.UTENT-trova.HELPPAGINA',0,4258458524);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.GENE.W_MODELLI',0,2702599471);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.PIANI.CREATE-XML',0,214293566);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.PIANI.IMPORT-XML',1,391094081);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.PIANI.SITAT',1,3454430183);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.W9.W9HOME.APPA',0,153343456);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.W9.W9HOME.ORT-INBX',0,306086409);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.W9.W9HOME.PIATRI',1,220199141);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.W9.W9HOME.SA-ADMIN',0,1456500244);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','ALT.W9.W9HOME.SA-AVVISI',0,1568287917);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','INS.GENE.ImprScheda.DATIGEN.INS-AIN',0,3816322368);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-G_IMPCOL',0,1319656519);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPAZI',0,147612543);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPDTE',0,2570711371);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','MENU','VIS','REPORT',0,3456026856);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','MENU','VIS','STRUMENTI',0,2622732340);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','GENE.ImprScheda.CASE',0,322106228);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','GENE.ImprScheda.CATE',0,377349617);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','GENE.ImprScheda.CATEGARE',0,1917287626);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','GENE.ImprScheda.IMPANTIMAFIA',0,960791731);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','GENE.ImprScheda.RAGIMP',0,4033516002);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','PAGE','VIS','PIANI.INTTRI-scheda.RISORSEBILANCIO',1,2705155577);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','MOD','W9.W9LOTT-scheda.DATIDET.MODLAV',1,1184464117);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.ABI',0,4156912262);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.AIN',0,3033598880);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.ALT',0,37172112);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.IMPDTE',0,1737007254);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.IND',1,4190301654);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.INPS',0,3614861476);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.ISO1',0,900991630);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.PERSDIP',0,507325010);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.SOA',0,3453285577);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.DATIGEN.XIMPR',0,2833513384);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPAZI',0,3404995677);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPDTE',0,1526828649);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.SchedaTecni.ALT',0,835318545);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','GENE.SchedaTeim.ALT',0,3279515167);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SEZ','VIS','W9.W9LOTT-scheda.DATIDET.MODLAV',1,3404640381);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','ARCHIVI.Archivio-staz-appaltanti',0,1400821008);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','ARCHIVI.Archivio-uffici-intestatari',0,2798010941);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','ARCHIVI.Archivio-utenti',0,3100152466);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','UTILITA.Import-export-modelli',0,3037951636);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','UTILITA.Import-export-report',0,2149004479);
Insert into W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) values ('SA-PIATRI-RT','SUBMENU','VIS','UTILITA.Manuali',0,3283288817);


Insert into W_ACCPRO (ID_ACCOUNT,COD_PROFILO) values (50,'SA-PIATRI-RT');


Insert into W_GRUPPI (ID_GRUPPO,NOME,DESCR,COD_PROFILO) Select distinct (select Coalesce(max(ID_GRUPPO),0)+1 from W_GRUPPI),'Comunicazioni di programmi (Regione Toscana)','default per il profilo SA-PIATRI-RT','SA-PIATRI-RT' from W_PROFILI where not exists (select 1 from W_GRUPPI where cod_profilo='SA-PIATRI-RT');
Update W_GENCHIAVI Set CHIAVE=(Select max(ID_GRUPPO) from W_GRUPPI) where TABELLA='W_GRUPPI';
Insert into W_ACCGRP (ID_ACCOUNT,ID_GRUPPO,PRIORITA) select 50,ID_GRUPPO,0 from W_GRUPPI where COD_PROFILO='SA-PIATRI-RT'  and not exists (select * from W_ACCGRP A join W_GRUPPI G on A.id_gruppo=G.id_gruppo where cod_profilo='SA-PIATRI-RT' and id_account=50);
