------ SCHEMA SITAT SA ----------
SET SCHEMA = SITATSA;
SET CURRENT PATH = SITATSA;

UPDATE COMMAND OPTIONS USING S ON;

--- DUPLICO TABELLA TECNICI
CREATE TABLE TEIM2 LIKE TEIM;
INSERT INTO TEIM2 SELECT * FROM TEIM;

--- SVUOTO LA TABELLA TECNICI
DELETE FROM TEIM;

--- INSERISCO NELLA TABELLA DEI TECNICI I RISULTATI DI UNA SELECT PER PORLI IN RAPPORTO 1:1 CON LE IMPRESE			 
INSERT INTO TEIM 
(TEIM.CODTIM, TEIM.NOMTIM, TEIM.COGTIM,TEIM.NOMETIM,TEIM.CFTIM,TEIM.CGENTIM)
SELECT 
I.CODIMP, T.NOMTIM,T.COGTIM,T.NOMETIM,T.CFTIM,T.CGENTIM
FROM IMPR I 
LEFT JOIN (SELECT CODIMP2,MIN (CODLEG)AS CODLEG FROM IMPLEG L WHERE LEGFIN IS NULL OR EXISTS (SELECT 1 FROM (SELECT CODIMP2,MAX(LEGFIN) AS LEGFIN FROM IMPLEG GROUP BY CODIMP2) A WHERE A.CODIMP2=L.CODIMP2 AND A.LEGFIN=L.LEGFIN)  GROUP BY CODIMP2) L ON L.CODIMP2=I.CODIMP
LEFT JOIN 
TEIM2 T ON 
T.CODTIM=L.CODLEG;

--- SVUOTO LA TABELLA IMPLEG
DELETE FROM IMPLEG;

--- RIPOPOLO LA TABELLA IMPLEG CON DATI ESSENZIALI
INSERT INTO IMPLEG
(IMPLEG.CODIMP2, IMPLEG.CODLEG, IMPLEG.NOMLEG)
SELECT
TEIM.CODTIM, TEIM.CODTIM, TEIM.NOMTIM FROM TEIM;

--- DISTRUGGO TABELLA TEMPORANEA TECNICI 2
DELETE FROM TEIM2;
DROP TABLE TEIM2;

