--------------------------------
-- AGGIORNAMENTO SITAT/VIGILANZA
-- Database: DB2
------------------------------



------------------------------
-- SITATSA 2.7.2
--------------------------

------------------------------------------------------------------------------------------------
------------------------         MODIFICA STRUTTURA TABELLE              ------------------------
------------------------------------------------------------------------------------------------

ALTER TABLE SITATSA.W9LOTT ADD COLUMN DATA_PUBBLICAZIONE TIMESTAMP;
ALTER TABLE SITATSA.W9LOTT ADD COLUMN DATA_CONSULTA_GARA TIMESTAMP;
ALTER TABLE SITATSA.W9LOTT ADD COLUMN EXSOTTOSOGLIA VARCHAR(1);

CREATE TABLE SITATSA.W9LOADER_APPALTO_USR (
	SYSCON NUMERIC(12) NOT NULL,
	SIMOGUSER VARCHAR(100),
	SIMOGPASS VARCHAR(100)
);
ALTER TABLE SITATSA.W9LOADER_APPALTO_USR ADD CONSTRAINT W9LOADER_APPALTO_USR_PK PRIMARY KEY (SYSCON);

ALTER TABLE SITATSA.W9FASI ADD COLUMN DAEXPORT VARCHAR(1);
ALTER TABLE SITATSA.W9XML ADD COLUMN IDFLUSSO NUMERIC(10);
ALTER TABLE SITATSA.W9XML ADD XML CLOB(10 M);

ALTER TABLE SITATSA.W9FLUSSI ALTER COLUMN CFSA SET DATA TYPE VARCHAR(16);
ALTER TABLE SITATSA.UFFINT ALTER COLUMN CFEIN SET DATA TYPE VARCHAR(20);

REORG TABLE SITATSA.W9LOTT;
REORG TABLE SITATSA.W9FASI;
REORG TABLE SITATSA.W9XML;
REORG TABLE SITATSA.UFFINT;
REORG TABLE SITATSA.W9FLUSSI;

--- View V_RUOLOTECNICO: drop and create
DROP VIEW SITATSA.V_RUOLOTECNICO;

CREATE VIEW SITATSA.V_RUOLOTECNICO as
SELECT I.CODGARA, I.CODLOTT, I.ID_RUOLO, I.CODTEC, G.CODEIN
  FROM SITATSA.W9INCA I, SITATSA.TECNI T, SITATSA.W9GARA G
 WHERE I.ID_RUOLO IN (15,16,17)
   AND I.CODTEC = T.CODTEC
   AND T.CGENTEI = G.CODEIN
   AND I.CODGARA = G.CODGARA
UNION
SELECT G.CODGARA, L.CODLOTT, 14 AS ID_RUOLO, G.RUP AS CODTEC, G.CODEIN
  FROM SITATSA.W9GARA G LEFT OUTER JOIN SITATSA.W9LOTT L on G.CODGARA = L.CODGARA
  JOIN SITATSA.TECNI T ON G.RUP = T.CODTEC AND G.CODEIN = T.CGENTEI
 WHERE G.RUP IS NOT NULL;


------------------------------------------------------------------------------------------------
------------------------         MODIFICA AI DATI          -------------------------------------
------------------------------------------------------------------------------------------------


--- C0CAMPI
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DATA_PUBBLICAZIONE.W9LOTT.W9','W9DPUBBLICAZ','Data pubblicazione','Data pubblicazione','A10',null,'DATA_ELDA','Data pubblicazione');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',null,'XML.W9XML.W9','W9FILEXML','File XML','File XML','A2000',null,'BLOB','File XML');
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'P',null,'XML.W9FLUSSI.W9','W9FLXML','File XML','File XML','A2000',null,'CLOB','File XML');
UPDATE SITATSA.C0CAMPI set COC_DES='Importo componente forniture al netto sicurezza',COC_DES_WEB='Importo componente forniture al netto sicurezza' where C0C_MNE_BER='W3I_FORNIT';
UPDATE SITATSA.C0CAMPI SET C0C_FS ='N4' WHERE C0C_MNE_BER = 'W3NLOTTO';
UPDATE SITATSA.C0CAMPI SET C0C_FS ='A20' WHERE COC_MNE_UNI = 'CFEIN.UFFINT.GENE';

--- W_OGGETTI
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('PAGE','W9.W9INIZ-scheda.SICUREZZA','Pagina Scheda sicurezza',2683);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('PAGE','W9.W9INIZ-scheda.CHECKSICUREZZA','Pagina Misure aggiuntive e migliorative per la sicurezza',2686);

INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.W9INBOX-HOME.FLUSSI','Home page Inbox - Sezione Flussi',3540);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.W9INBOX-HOME.FEEDBACK','Home page Inbox - Sezione Feedback',3545);

--- W_CONFIG
INSERT INTO SITATSA.W_CONFIG (CODAPP, CHIAVE, VALORE) values ('W9', 'registrazione.consentiCreazioneNuovaSA', '1');

UPDATE SITATSA.W_PROFILI SET DESCRIZIONE='Comunicazioni di avvisi per manifestazione di interesse ed altri avvisi' WHERE COD_PROFILO='SA-AVVISI';


UPDATE SITATSA.TAB1 SET TAB1NORD=6 WHERE TAB1COD='W3020' AND TAB1TIP=101;
UPDATE SITATSA.TAB1 SET TAB1NORD=7 WHERE TAB1COD='W3020' AND TAB1TIP=987;
UPDATE SITATSA.TAB1 SET TAB1NORD=8 WHERE TAB1COD='W3020' AND TAB1TIP=1;
UPDATE SITATSA.TAB1 SET TAB1NORD=9 WHERE TAB1COD='W3020' AND TAB1TIP=984;

--- TAB1
UPDATE SITATSA.TAB1 SET TAB1DESC='Manutenzione (Valore non piu'' valido)' where TAB1COD='W3002' and TAB1TIP=11;
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W3002', 12, 'Manutenzione Ordinaria');
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W3002', 13, 'Manutenzione straordinaria');
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC) values ('W3005', 25, 'Procedura ristretta semplificata');

--- TAB2
DELETE FROM SITATSA.TAB2 WHERE TAB2COD='W3z05' AND TAB2TIP IN ('CL','CS');
UPDATE SITATSA.W9LOTT SET TIPO_CONTRATTO='L' WHERE TIPO_CONTRATTO='CL';
UPDATE SITATSA.W9LOTT SET TIPO_CONTRATTO='S' WHERE TIPO_CONTRATTO='CS';

UPDATE SITATSA.C0CAMPI SET COC_DES='Denominazione del soggetto per cui agisce la S.A',COC_DES_WEB='Denominazione del soggetto per cui agisce la S.A' where C0C_MNE_BER='W3GASAAGENTE';
UPDATE SITATSA.C0CAMPI SET COC_DES='Codice fiscale del soggetto per cui agisce la S.A',COC_DES_WEB='Codice fiscale del soggetto per cui agisce la S.A' where C0C_MNE_BER='W3GACFAGENTE';

INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','ALT.W9.INVIISIMOG','Invii a Simog - LoaderAppalto',3550);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('FUNZ','VIS','ALT.W9.INVIISIMOG','Visualizza',0,1,1,1909453922);
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','W9.W9PERMESSI.CODGARA','Visualizza',0,1,1,71550828);

--- W_CONFIG
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.simog.tipoAccesso',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.simog.ws.url',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.simog.ws.login',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.simog.ws.password',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.simog.loaderAppalto.url',null);

INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.sitat.pdd.basicAuth.simogws.username',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.sitat.pdd.basicAuth.simogws.password',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.sitat.pdd.basicAuth.loaderAppalto.username',null);
INSERT INTO SITATSA.W_CONFIG (CODAPP,CHIAVE,VALORE) VALUES ('W9','it.eldasoft.sitat.pdd.basicAuth.loaderAppalto.password',null);

--- Script aggiunti in un secondo momento
------------------------------------------------------------------------------------------------
------------------------         MODIFICA STRUTTURA TABELLE              ------------------------
------------------------------------------------------------------------------------------------
ALTER TABLE SITATSA.W9GARA ADD COLUMN IDCC_BCKP NUMERIC(10);
REORG TABLE SITATSA.W9GARA;

------------------------------------------------------------------------------------------------
------------------------         MODIFICA AI DATI          -------------------------------------
------------------------------------------------------------------------------------------------
UPDATE SITATSA.W9GARA set IDCC_BCKP = IDCC;

INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('MASC','W9.TrovaCentri','Trova Centri di costo',3600);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','INS.W9.TrovaCentri.TROVANUOVO','Nuovo Centro di costo',3603);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('MASC','W9.ListaCentri','Lista Centri di costo',3605);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','DEL.W9.ListaCentri.DEL','Elimina Centro di costo',3607);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','DEL.W9.ListaCentri.LISTADELSEL','Elimina Centri di costo selezionati',3610);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','INS.W9.ListaCentri.LISTANUOVO','Nuovo Centro di costo',3612);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','MOD.W9.ListaCentri.MOD','Modifica Centro di costo',3615);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('MASC','W9.SchedaCentri','Scheda Centri di costo',3617);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','MOD.W9.SchedaCentri.SCHEDAMOD','Modifica Centro di costo',3618);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','INS.W9.SchedaCentri.SCHEDANUOVO','Nuovo Centro di costo',3620);

--- Profilo: SA-APPA. Centri di costo: no modifica, no inserimento, no cancellazione
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','INS.W9.TrovaCentri.TROVANUOVO',0,3396902013);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','INS.W9.SchedaCentri.SCHEDANUOVO',0,3239673868);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','INS.W9.ListaCentri.LISTANUOVO',0,2549356594);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','MOD.W9.ListaCentri.MOD',0,2157433065);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','MOD.W9.SchedaCentri.SCHEDAMOD',0,914238721);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','DEL.W9.ListaCentri.DEL',0,301653945);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','FUNZ','VIS','DEL.W9.ListaCentri.LISTADELSEL',0,2176608700);

--- Profilo: SA-PIATRI. Centri di costo: no modifica, no inserimento, no cancellazione
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','INS.W9.TrovaCentri.TROVANUOVO',0,3396902013);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','INS.W9.ListaCentri.LISTANUOVO',0,2549356594);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','INS.W9.SchedaCentri.SCHEDANUOVO',0,3239673868);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','MOD.W9.ListaCentri.MOD',0,2157433065);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','MOD.W9.SchedaCentri.SCHEDAMOD',0,914238721);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','DEL.W9.ListaCentri.DEL',0,301653945);
INSERT INTO SITATSA.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-PIATRI','FUNZ','VIS','DEL.W9.ListaCentri.LISTADELSEL',0,2176608700);

--- Aggiornamento di versione di SitatSA
UPDATE SITATSA.ELDAVER SET NUMVER='2.7.2', DATVET=CURRENT TIMESTAMP WHERE CODAPP='W9';
