------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------
-- GENE 1.4.41
------------------------------
-----------------------------------------------------
---   Aggiornamento da 1.4.39 a 1.4.40 di Gene    ---
-----------------------------------------------------
-- C0CAMPI
UPDATE SITATSA.C0CAMPI SET COC_CONTA=800102086, C0C_TIP='E', C0C_CHI=null, COC_MNE_UNI='COORBA.IMPR.GENE', COC_DES='Estremi del conto corrente dedicato', COC_DES_FRM='Conto corr. dedicato', C0C_FS='A50', C0C_TAB1=null, COC_DOM=null, COC_DES_WEB='Conto corrente dedicato' WHERE C0C_MNE_BER='G_COORBA';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=800109059, C0C_TIP='E',C0C_CHI=null,COC_MNE_UNI='WEBUSR.TECNI.GENE',COC_DES='Utente per la connessione a internet (NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='G_WEBUSRT';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=800109060,C0C_TIP='E',C0C_CHI=null,COC_MNE_UNI='WEBPWD.TECNI.GENE',COC_DES='Password per la connessione a internet (NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A16',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='G_WEBPWDT';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=800110040,C0C_TIP='E',C0C_CHI=null,COC_MNE_UNI='WEBUSR.UTENT.GENE',COC_DES='Utente per la connessione a internet (NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='WEBUSR';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=800110041,C0C_TIP='E',C0C_CHI=null,COC_MNE_UNI='WEBPWD.UTENT.GENE',COC_DES='Password per la connessione a internet (NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A16',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='WEBPWD';
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (800102087,'E',null,'SOGMOV.IMPR.GENE','G_SOGMOV','Soggetti abilitati a movimentazioni su conto dedicato','Sogg.abilitati mov.','A2000',null,'NOTE','Soggetti abilitati a movimentazioni su conto corrente dedicato');
DELETE FROM SITATSA.C0CAMPI WHERE COC_MNE_UNI LIKE 'EMAIL2PEC.IMPR.GENE';

-- TAB3
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','CI','Carbonia Iglesias',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','FC','Forlì Cesena',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','OG','Ogliastra',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','OT','Olbia Tempio',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','PU','Pesaro e Urbino',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('Agx15','VS','Medio Campidano',null);
UPDATE SITATSA.TAB3 SET TAB3DESC='La Spezia' ,TAB3MOD=null WHERE TAB3COD='Agx15' AND TAB3TIP='SP';
UPDATE SITATSA.TAB3 SET TAB3DESC='Forli (vecchia sigla)' ,TAB3MOD=null WHERE TAB3COD='Agx15' AND TAB3TIP='FO';
UPDATE SITATSA.TAB3 SET TAB3DESC='Pesaro (vecchia sigla)',TAB3MOD=null WHERE TAB3COD='Agx15' AND TAB3TIP='PS';

-- TABSCHE
UPDATE SITATSA.TABSCHE SET TABDESC='FORLI CESENA',TABCOD3='FC',TABCOD4=null,TABCOD5=null   WHERE TABCOD='S2003' AND TABCOD1='07' AND TABCOD2='0040';
UPDATE SITATSA.TABSCHE SET TABDESC='PESARO E URBINO',TABCOD3='PU',TABCOD4=null,TABCOD5=null WHERE TABCOD='S2003' AND TABCOD1='07' AND TABCOD2='0041';

ALTER TABLE SITATSA.IMPR ADD COLUMN SOGMOV VARCHAR(2000);
REORG TABLE SITATSA.IMPR;

-- -----------------------------------------------------
-- ---   Aggiornamento da 1.4.40 a 1.4.41 di Gene    ---
-- -----------------------------------------------------
-- C0CAMPI
UPDATE SITATSA.C0CAMPI SET COC_CONTA=801200005,C0C_TIP='C',C0C_CHI=null,COC_MNE_UNI='DYNCAM_BASE.DYNCAM_GEN.GENE',COC_DES='Il campo e''parte della struttura base dell''entita''?',COC_DES_FRM='Campo base ?',C0C_FS='A1',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DCAM_BASEG';
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038014,'P','P','CODICE.TABNUTS.GENE','NUTSCODICE','Codice NUTS','Codice NUTS','A5',null,null,null);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038015,'P',null,'PAESE.TABNUTS.GENE','NUTSPAESE','Paese','Paese','A2',null,null,null);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038016,'P',null,'AREA.TABNUTS.GENE','NUTSAREA','Area','Area','A1',null,null,null);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038017,'P',null,'REGIONE.TABNUTS.GENE','NUTSREG','Regione','Regione','A1',null,null,null);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038018,'P',null,'PROVINCIA.TABNUTS.GENE','NUTSPROV','Provincia','Provincia','A2',null,null,null);
INSERT INTO SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (880038019,'P',null,'DESCRIZIONE.TABNUTS.GENE','NUTSDESC','Descrizione','Descrizione','A100',null,null,null);

-- C0ENTIT
INSERT INTO SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) VALUES ('TABNUTS.GENE',88020110,'P','TABNUTS','Lista dei codici NUTS','CODICE.TABNUTS.GENE',null,null,null,null,'g_nuts0');

CREATE TABLE SITATSA.TABNUTS
  (CODICE VARCHAR(5) NOT NULL,
  PAESE VARCHAR(2),
	AREA VARCHAR(1),
	REGIONE VARCHAR(1),
	PROVINCIA VARCHAR(1),
	DESCRIZIONE VARCHAR(100)
	   ) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.TABNUTS ADD CONSTRAINT TABNUTS_PK PRIMARY KEY (CODICE);
 
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.TABNUTS TO USER SITATSA;

INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('IT','IT',null,null,null,'ITALIA');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC','IT','C',null,null,'NORD-OVEST');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC1','IT','C','1',null,'Piemonte');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC11','IT','C','1','1','Torino');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC12','IT','C','1','2','Vercelli');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC13','IT','C','1','3','Biella');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC14','IT','C','1','4','Verbano-Cusio-Ossola');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC15','IT','C','1','5','Novara');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC16','IT','C','1','6','Cuneo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC17','IT','C','1','7','Asti');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC18','IT','C','1','8','Alessandria');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC2','IT','C','2',null,'Valle d''Aosta/Vallée d''Aoste');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC20','IT','C','2','0','Valle d''Aosta/Vallée d''Aoste');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC3','IT','C','3',null,'Liguria');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC31','IT','C','3','1','Imperia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC32','IT','C','3','2','Savona');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC33','IT','C','3','3','Genova');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC34','IT','C','3','4','La Spezia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC4','IT','C','4',null,'Lombardia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC41','IT','C','4','1','Varese');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC42','IT','C','4','2','Como');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC43','IT','C','4','3','Lecco');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC44','IT','C','4','4','Sondrio');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC45','IT','C','4','5','Milano');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC46','IT','C','4','6','Bergamo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC47','IT','C','4','7','Brescia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC48','IT','C','4','8','Pavia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC49','IT','C','4','9','Lodi');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC4A','IT','C','4','A','Cremona');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITC4B','IT','C','4','B','Mantova');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD','IT','D',null,null,'NORD-EST');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD1','IT','D','1',null,'Provincia Autonoma Bolzano/Bozen');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD10','IT','D','1','0','Bolzano-Bozen');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD2','IT','D','2',null,'Provincia Autonoma Trento');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD20','IT','D','2','0','Trento');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD3','IT','D','3',null,'Veneto');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD31','IT','D','3','1','Verona');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD32','IT','D','3','2','Vicenza');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD33','IT','D','3','3','Belluno');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD34','IT','D','3','4','Treviso');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD35','IT','D','3','5','Venezia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD36','IT','D','3','6','Padova');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD37','IT','D','3','7','Rovigo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD4','IT','D','4',null,'Friuli-Venezia Giulia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD41','IT','D','4','1','Pordenone');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD42','IT','D','4','2','Udine');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD43','IT','D','4','3','Gorizia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD44','IT','D','4','4','Trieste');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD5','IT','D','5',null,'Emilia-Romagna');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD51','IT','D','5','1','Piacenza');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD52','IT','D','5','2','Parma');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD53','IT','D','5','3','Reggio nell''Emilia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD54','IT','D','5','4','Modena');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD55','IT','D','5','5','Bologna');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD56','IT','D','5','6','Ferrara');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD57','IT','D','5','7','Ravenna');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD58','IT','D','5','8','Forlì-Cesena');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITD59','IT','D','5','9','Rimini');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE','IT','E',null,null,'CENTRO');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE1','IT','E','1',null,'Toscana');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE11','IT','E','1','1','Massa-Carrara');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE12','IT','E','1','2','Lucca');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE13','IT','E','1','3','Pistoia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE14','IT','E','1','4','Firenze');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE15','IT','E','1','5','Prato');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE16','IT','E','1','6','Livorno');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE17','IT','E','1','7','Pisa');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE18','IT','E','1','8','Arezzo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE19','IT','E','1','9','Siena');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE1A','IT','E','1','A','Grosseto');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE2','IT','E','2',null,'Umbria');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE21','IT','E','2','1','Perugia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE22','IT','E','2','2','Terni');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE3','IT','E','3',null,'Marche');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE31','IT','E','3','1','Pesaro e Urbino');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE32','IT','E','3','2','Ancona');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE33','IT','E','3','3','Macerata');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE34','IT','E','3','4','Ascoli Piceno');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE4','IT','E','4',null,'Lazio');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE41','IT','E','4','1','Viterbo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE42','IT','E','4','2','Rieti');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE43','IT','E','4','3','Roma');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE44','IT','E','4','4','Latina');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITE45','IT','E','4','5','Frosinone');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF','IT','F',null,null,'SUD');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF1','IT','F','1',null,'Abruzzo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF11','IT','F','1','1','L''Aquila');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF12','IT','F','1','2','Teramo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF13','IT','F','1','3','Pescara');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF14','IT','F','1','4','Chieti');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF2','IT','F','2',null,'Molise');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF21','IT','F','2','1','Isernia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF22','IT','F','2','2','Campobasso');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF3','IT','F','3',null,'Campania');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF31','IT','F','3','1','Caserta');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF32','IT','F','3','2','Benevento');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF33','IT','F','3','3','Napoli');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF34','IT','F','3','4','Avellino');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF35','IT','F','3','5','Salerno');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF4','IT','F','4',null,'Puglia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF41','IT','F','4','1','Foggia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF42','IT','F','4','2','Bari');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF43','IT','F','4','3','Taranto');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF44','IT','F','4','4','Brindisi');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF45','IT','F','4','5','Lecce');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF5','IT','F','5',null,'Basilicata');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF51','IT','F','5','1','Potenza');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF52','IT','F','5','2','Matera');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF6','IT','F','6',null,'Calabria');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF61','IT','F','6','1','Cosenza');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF62','IT','F','6','2','Crotone');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF63','IT','F','6','3','Catanzaro');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF64','IT','F','6','4','Vibo Valentia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITF65','IT','F','6','5','Reggio di Calabria');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG','IT','G',null,null,'ISOLE');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG1','IT','G','1',null,'Sicilia');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG11','IT','G','1','1','Trapani');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG12','IT','G','1','2','Palermo');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG13','IT','G','1','3','Messina');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG14','IT','G','1','4','Agrigento');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG15','IT','G','1','5','Caltanissetta');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG16','IT','G','1','6','Enna');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG17','IT','G','1','7','Catania');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG18','IT','G','1','8','Ragusa');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG19','IT','G','1','9','Siracusa');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG2','IT','G','2',null,'Sardegna');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG25','IT','G','2','5','Sassari');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG26','IT','G','2','6','Nuoro');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG27','IT','G','2','7','Cagliari');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG28','IT','G','2','8','Oristano');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG29','IT','G','2','9','Olbia-Tempio');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG2A','IT','G','2','A','Ogliastra');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG2B','IT','G','2','B','Medio Campidano');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITG2C','IT','G','2','C','Carbonia-Iglesias');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITZ','IT','Z',null,null,'EXTRA-REGIO');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITZZ','IT','Z','Z',null,'Extra-Regio');
INSERT INTO SITATSA.TABNUTS (CODICE,PAESE,AREA,REGIONE,PROVINCIA,DESCRIZIONE) VALUES ('ITZZZ','IT','Z','Z','Z','Extra-Regio');


----------------------------------------------------------------------------------------
---   Aggiornamento cumulativo dalla versione 1.4.41 alla versione 1.4.43 di Gene    ---
----------------------------------------------------------------------------------------

-- Aggiornamento tabella IMPANTIMAFIA da 1.4.41 a 1.4.42
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN SOGMOV VARCHAR(2000);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NPRICH VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN TIPRIC NUMERIC(7);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN TIPGEN NUMERIC(7);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN IMPAPP NUMERIC(24,5);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN ENTALT VARCHAR(500);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN FORALT VARCHAR(500);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NRISFP VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NPROVV VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NRIESA VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NRIEFP VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NACCAT VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NAUTAT VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NRICATT VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NTRAATT VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NPROTAR VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NUMCON VARCHAR(10);
ALTER TABLE SITATSA.IMPANTIMAFIA ADD COLUMN NPROCON VARCHAR(10);
REORG TABLE SITATSA.IMPANTIMAFIA;

-- Aggiornamento tabella CAIS da 1.4.42 a 1.4.43
ALTER TABLE SITATSA.CAIS ADD COLUMN TITCAT VARCHAR(15);
REORG TABLE SITATSA.CAIS;
update SITATSA.CAIS set titcat='1' where caisim like 'OG%';
update SITATSA.CAIS set titcat='2' where caisim like 'OS%';

-- Aggiornamento tabella TABx da 1.4.42 a 1.4.43
ALTER TABLE SITATSA.TAB0 ADD COLUMN TAB0NORD NUMERIC(8,2);
ALTER TABLE SITATSA.TAB2 ADD COLUMN TAB2NORD NUMERIC(8,2);
ALTER TABLE SITATSA.TAB3 ADD COLUMN TAB3NORD NUMERIC(8,2);
ALTER TABLE SITATSA.TAB5 ADD COLUMN TAB5NORD NUMERIC(8,2);
REORG TABLE SITATSA.TAB0;
REORG TABLE SITATSA.TAB2;
REORG TABLE SITATSA.TAB3;
REORG TABLE SITATSA.TAB5;

-- Aggiornamento IMPR da 1.4.42 a 1.4.43
ALTER TABLE SITATSA.IMPR ADD COLUMN DINVREG TIMESTAMP;
ALTER TABLE SITATSA.IMPR ADD COLUMN DELAREG TIMESTAMP;
REORG TABLE SITATSA.IMPR;


-- Aggiornamento cumulativo di C0CAMPI/C0ENTIT da 1.4.41 a 1.4.43
delete from SITATSA.C0CAMPI where c0c_mne_ber in ('DCCIAC','DCCIAE','NCCIAC','NCCIAE','G_CAISIM_T','G_ACONTEC_T','G_CAISORD_T','DCCIAA','G_DCERCC','G_DESCAT_T','DISCIF','G_ENTALT','G_FORALT','G_IMPAPP','G_NACCAT','G_NAUTAT','NCCIAA','G_NCERCC','G_NOTGAR','G_NPRICH','G_NPROCON','G_NPROTAR','G_NPROVV','G_NRICATT','G_NRIEFP','G_NRIESA','G_NRISFP','G_NTRAATT','G_NUMCON','G_NUMORD_T','G_PCCIAA','G_QUAOBB_T','G_REGDIT','G_TIPGEN','G_TIPLAVG','G_TIPLAVG_T','G_TIPRIC','G_TITCAT','G_TITCAT_T','G_TITNORD_T','TAB5TIP','TAB0NORD','TAB2NORD','TAB3NORD','TAB5NORD');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'C',null,'DCCIAA.IMPR.GENE','DCCIAC','Data dell''iscrizione al Registro Imprese','Data iscr. Reg.Impr.','A10',null,'DATA_ELDA','Data iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'C',null,'DCCIAA.IMPR.GENE','DCCIAE','Data dell''iscrizione al Registro Imprese','Data iscr. Reg.Impr.','A10',null,'DATA_ELDA','Data iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'C',null,'NCCIAA.IMPR.GENE','NCCIAC','Numero dell''iscrizione al Registro Imprese','N.iscr. Reg.Imprese','A16',null,null,'Numero iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'C',null,'NCCIAA.IMPR.GENE','NCCIAE','Numero dell''iscrizione al Registro Imprese','N.iscr. Reg.Imprese','A16',null,null,'Numero iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CAISIM.V_CAIS_TIT.GENE','G_CAISIM_T','Codice della categoria','Codice categoria','A5',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'ACONTEC.V_CAIS_TIT.GENE','G_ACONTEC_T','Categoria superspecialistica?','Super specialistica?','A2',null,'SN',null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'CAISORD.V_CAIS_TIT.GENE','G_CAISORD_T','Numero d''ordine della categoria','Numero ord. categ.','N3',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DCCIAA.IMPR.GENE','DCCIAA','Data dell''iscrizione al Registro Imprese','Data iscr. Reg.Impr.','A10',null,'DATA_ELDA','Data iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DCERCC.IMPR.GENE','G_DCERCC','Data certificato iscrizione C.C.I.A.A.','Data cert.C.C.I.A.A.','A10',null,'DATA_ELDA','Data certificato iscrizione');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DESCAT.V_CAIS_TIT.GENE','G_DESCAT_T','Descrizione della categoria','Descr.categoria','A2000',null,null,'Descrizione');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DISCIF.IMPR.GENE','DISCIF','Data dell''iscrizione R.E.A.','Data iscriz. R.E.A.','A10',null,'DATA_ELDA','Data iscrizione R.E.A.');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'ENTALT.IMPANTIMAFIA.GENE','G_ENTALT','Descrizione altro ente richiedente','Altro ente richied.','A500',null,null,'Altro ente richiedente');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'FORALT.IMPANTIMAFIA.GENE','G_FORALT','Descrizione altra forza di polizia','Altra forza polizia','A500',null,null,'Altra forza di polizia');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'IMPAPP.IMPANTIMAFIA.GENE','G_IMPAPP','Importo','Importo','F15',null,'MONEY','Importo');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NACCAT.IMPANTIMAFIA.GENE','G_NACCAT','Numero richiesta di accesso agli atti','Num. rich.acces.atti','A10',null,null,'Numero richiesta accesso agli atti');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NAUTAT.IMPANTIMAFIA.GENE','G_NAUTAT','Numero autorizzazione all''accesso agli atti','Num. autor.acc.atti','A10',null,null,'Numero autorizzazione accesso agli atti');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NCCIAA.IMPR.GENE','NCCIAA','Numero dell''iscrizione al Registro Imprese','N.iscr. Reg.Imprese','A16',null,null,'Numero iscrizione Registro Imprese');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NCERCC.IMPR.GENE','G_NCERCC','Numero certificato iscrizione C.C.I.A.A.','N.certif.C.C.I.A.A.','A23',null,null,'Numero certificato iscrizione');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NOT_GAR.IMPANTIMAFIA.GENE','G_NOTGAR','Oggetto','Oggetto','A2000',null,'NOTE',null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NPRICH.IMPANTIMAFIA.GENE','G_NPRICH','Numero protocollo richiesta accertamento','N.prot.richiesta','A10',null,null,'N.protocollo richiesta');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NPROCON.IMPANTIMAFIA.GENE','G_NPROCON','Numero pronuncia del Consiglio di Stato','Num. pronun.Cons.St.','A10',null,null,'Numero pronuncia');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NPROTAR.IMPANTIMAFIA.GENE','G_NPROTAR','Numero pronuncia del TAR','Num. pronuncia TAR','A10',null,null,'Numero pronuncia del TAR');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NPROVV.IMPANTIMAFIA.GENE','G_NPROVV','Numero del provvedimento','Num. provvedimento','A10',null,null,'Numero provvedimento');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NRICATT.IMPANTIMAFIA.GENE','G_NRICATT','Numero richiesta atti','Num. rich.atti','A10',null,null,'Numero richiesta atti');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NRIEFP.IMPANTIMAFIA.GENE','G_NRIEFP','Numero lettera alle forze di polizia per il riesame','Num. riesame f.pol.','A10',null,null,'Numero lettera alle forze di polizia');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NRIESA.IMPANTIMAFIA.GENE','G_NRIESA','Numero richiesta del riesame','Num. rich. riesame','A10',null,null,'Numero richiesta riesame');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NRISFP.IMPANTIMAFIA.GENE','G_NRISFP','Numero risposta delle forze di polizia','N.risposta f.pol.','A10',null,null,'Numero risposta forze di polizia');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NTRAATT.IMPANTIMAFIA.GENE','G_NTRAATT','Numero trasmissione atti','Num. trasmis.atti','A10',null,null,'Numero trasmissione atti');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NUMCON.IMPANTIMAFIA.GENE','G_NUMCON','Numero del ricorso al Consiglio di Stato','Num. ricorso Cons.St','A10',null,null,'Numero ricorso');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'NUMORD.V_CAIS_TIT.GENE','G_NUMORD_T','Numero ordinamento per tipo appalto e titolo','Numero ordine','A20',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'PCCIAA.IMPR.GENE','G_PCCIAA','Codice ISTAT della provincia di iscrizione C.C.I.A.A.','Prov.iscr.C.C.I.A.A.','A10',null,null,'Codice ISTAT provincia di iscriz.');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'QUAOBB.V_CAIS_TIT.GENE','G_QUAOBB_T','Categoria a qualificazione obbligatoria ?','Qualificaz.obblig.?','A2',null,'SN',null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'REGDIT.IMPR.GENE','G_REGDIT','Numero R.E.A. (Repertorio notizie Economiche Amministrative)','Numero R.E.A.','A16',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TIPGEN.IMPANTIMAFIA.GENE','G_TIPGEN','Tipo di appalto (Lavori, Forniture o Servizi)','Tipo di appalto','A100','A1007',null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TIPLAVG.CAIS.GENE','G_TIPLAVG','Tipo di appalto (Lavori,Forniture, Servizi)','Tipo di appalto','A100','A1007',null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TIPLAVG.V_CAIS_TIT.GENE','G_TIPLAVG_T','Tipo di appalto (Lavori,Forniture, Servizi)','Tipo di appalto','A100','A1007',null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TIPRIC.IMPANTIMAFIA.GENE','G_TIPRIC','Tipo di richiesta accertamento (per appalto, subappalto ...)','Tipo richiesta','A100','G_034',null,'Richiesta per');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TITCAT.CAIS.GENE','G_TITCAT','Titolo della categoria','Titolo','A240','G_j05',null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TITCAT.V_CAIS_TIT.GENE','G_TITCAT_T','Titolo della categoria','Titolo','A240','G_j05',null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'TITNORD.V_CAIS_TIT.GENE','G_TITNORD_T','Numero d''ordine del titolo','Numero ord. titolo','F8.2',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P','P','TAB5TIP.TAB5.GENE','TAB5TIP','Caratteri identificatori del Numero del dato tabellato','Caratteri ident.','A10',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',null,'TAB0NORD.TAB2.GENE','TAB0NORD','Numero d''ordine','Numero d''ordine','F8.2',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',null,'TAB2NORD.TAB2.GENE','TAB2NORD','Numero d''ordine','Numero d''ordine','F8.2',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',null,'TAB3NORD.TAB3.GENE','TAB3NORD','Numero d''ordine','Numero d''ordine','F8.2',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'P',null,'TAB5NORD.TAB5.GENE','TAB5NORD','Numero d''ordine','Numero d''ordine','F8.2',null,null,null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DINVREG.IMPR.GENE','G_DINVREG','Data invio richiesta registrazione su portale','Data rich.registraz.','A10',null,null,'Data richiesta registrazione su portale');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'DELAREG.IMPR.GENE','G_DELAREG','Data elaborazione registrazione su portale','Data registrazione','A10',null,null,'Data registrazione su portale');
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('V_CAIS_TIT.GENE',80000989,'E','CATEG_TIT','Lista Categorie Iscrizione ordinate per tipo app. e titolo','CAISIM.CAIS.GENE','CAIS.GENE','CAISIM.CAIS.GENE',null,null,'g_cait0');



-- TAB1 da 1.4.41 a 1.4.42
delete from SITATSA.TAB1 where tab1cod = 'G_026' and tab1tip = 99;
delete from SITATSA.TAB1 where tab1cod = 'G_027' and tab1tip = 99;
delete from SITATSA.TAB1 where tab1cod = 'G_028' and tab1tip = 3;
delete from SITATSA.TAB1 where tab1cod = 'G_034' and tab1tip = 1;
delete from SITATSA.TAB1 where tab1cod = 'G_034' and tab1tip = 2;
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('G_026',99,'Altro','1',null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('G_027',99,'Altro','1',null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('G_028',3,'Comunicazione art.1 septies Dlgs.629/82',null,null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('G_034',1,'Appalto','1',null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('G_034',2,'Subappalto',null,null);

-- TAB6 da 1.4.41 a 1.4.42
DELETE FROM SITATSA.TAB6 WHERE TAB6COD = 'G__1' AND TAB6TIP = 'G_034'; 
Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_034','Tipo di richiesta accertamento (per appalto, subappalto ...) (WEB)');

-- TAB5 da 1.4.42 a 1.4.43
DELETE FROM SITATSA.TAB5 WHERE TAB5COD = 'G_j05' AND TAB5TIP IN ('1','2');
Insert into SITATSA.TAB5 (TAB5COD,TAB5TIP,TAB5DESC,TAB5MOD,TAB5NORD) values ('G_j05','1','Categorie per opere generali','1',1);
Insert into SITATSA.TAB5 (TAB5COD,TAB5TIP,TAB5DESC,TAB5MOD,TAB5NORD) values ('G_j05','2','Categorie per opere specializzate','1',2);

-- TAB6 da 1.4.42 a 1.4.43
DELETE FROM SITATSA.TAB6 WHERE TAB6COD = 'G__1' AND TAB6TIP = 'G_j05'; 
Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_j05','Titolo della categoria d''iscrizione');

-- Aggiornamenti delle versioni di G_, W_ e W9
UPDATE SITATSA.ELDAVER SET NUMVER = '1.4.43' WHERE CODAPP= 'G_';

--Correzione errore
UPDATE SITATSA.c0campi set c0c_fs = 'N4' where coc_mne_uni = 'INDCON.IMPIND.GENE';

------------------------------
-- GENEWEB 1.5.7
------------------------------
-- -----------------------------------------------------
-- ---   Aggiornamento di GeneWeb da 1.5.5 a 1.5.6   ---
-- -----------------------------------------------------

-- TAB1:
UPDATE SITATSA.TAB1 SET TAB1DESC='Riservata (invio mail o fax e consultazione in area riservata)', TAB1MOD=null, TAB1NORD=null WHERE TAB1COD='G_023' AND TAB1TIP=2;
UPDATE SITATSA.TAB1 SET TAB1DESC='PEC',    TAB1MOD=null, TAB1NORD=null WHERE TAB1COD='W_003' AND TAB1TIP=1;
UPDATE SITATSA.TAB1 SET TAB1DESC='E-mail', TAB1MOD=null, TAB1NORD=null WHERE TAB1COD='W_003' AND TAB1TIP=2;
UPDATE SITATSA.TAB1 SET TAB1DESC='Fax',    TAB1MOD=null, TAB1NORD=null WHERE TAB1COD='W_003' AND TAB1TIP=3;

--C0CAMPI:
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000121, C0C_TIP='C',C0C_CHI=null,COC_MNE_UNI='COMTIPMA.W_INVCOM.GENEWEB',   COC_DES='Tipo indirizzo da utilizzare (PEC, e-mail)(NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A100',C0C_TAB1='W_003',COC_DOM=null,COC_DES_WEB='Invio comunicazione a indirizzo PEC o e-mail?' WHERE C0C_MNE_BER='COMTIPMA_';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000206, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESMAIL.W_INVCOMDES.GENEWEB', COC_DES='Indirizzo del destinatario',COC_DES_FRM='Indirizzo',C0C_FS='A100',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DESMAIL';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000208, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESTESTO.W_INVCOMDES.GENEWEB',COC_DES='Testo messaggio personalizzato (se abilitato)',COC_DES_FRM='Testo personalizzato',C0C_FS='A2000',C0C_TAB1=null,COC_DOM='NOTE',COC_DES_WEB=null WHERE C0C_MNE_BER='DESTESTO';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000209, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESIDDOCDIG.W_INVCOMDES.GENEWEB',COC_DES='Documento composto personalizzato (se abilitato)',COC_DES_FRM='Allegato personaliz.',C0C_FS='N12',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DESIDDOCDIG';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000210, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESDATINV.W_INVCOMDES.GENEWEB'  ,COC_DES='Data e ora invio',COC_DES_FRM='Data e ora invio',C0C_FS='A10',C0C_TAB1=null,COC_DOM='DATA_ELDA',COC_DES_WEB=null WHERE C0C_MNE_BER='DESDATINV';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000211, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESDATINV_S.W_INVCOMDES.GENEWEB',COC_DES='Data e ora invio',COC_DES_FRM='Data e ora invio',C0C_FS='A20',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DESDATINV_S';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000212, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESSTATO.W_INVCOMDES.GENEWEB', COC_DES='Stato della comunicazione',COC_DES_FRM='Stato comunicazione',C0C_FS='A100',C0C_TAB1='G_z21',COC_DOM=null,COC_DES_WEB=null WHERE  C0C_MNE_BER='DESSTATO';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000213, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESERRORE.W_INVCOMDES.GENEWEB',COC_DES='Descrizione errore',COC_DES_FRM='Descrizione errore',C0C_FS='A2000',C0C_TAB1=null,COC_DOM='NOTE',COC_DES_WEB=null WHERE C0C_MNE_BER='DESERRORE';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000214, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DESINTEST.W_INVCOMDES.GENEWEB',COC_DES='Intestazione',COC_DES_FRM='Intestazione',C0C_FS='A61',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DESINTEST';

ALTER TABLE SITATSA.W_INVCOMDES ADD COLUMN COMTIPMA NUMERIC(7);
REORG TABLE SITATSA.W_INVCOMDES;

--Valorizza il campo a 2 = 'E-mail' per le occ. esistenti
update SITATSA.W_INVCOMDES set COMTIPMA=2;

-- -----------------------------------------------------
-- ---   Aggiornamento di GeneWeb da 1.5.6 a 1.5.7   ---
-- -----------------------------------------------------

ALTER TABLE SITATSA.W_DOCDIG ALTER COLUMN DIGKEY1 SET DATA TYPE VARCHAR(30);
ALTER TABLE SITATSA.W_DOCDIG ALTER COLUMN DIGKEY2 SET DATA TYPE VARCHAR(30);
ALTER TABLE SITATSA.W_DOCDIG ALTER COLUMN DIGKEY3 SET DATA TYPE VARCHAR(30);
ALTER TABLE SITATSA.W_DOCDIG ALTER COLUMN DIGKEY4 SET DATA TYPE VARCHAR(30);
ALTER TABLE SITATSA.W_DOCDIG ALTER COLUMN DIGKEY5 SET DATA TYPE VARCHAR(30);
REORG TABLE SITATSA.W_DOCDIG;

-- C0CAMPI:
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000302, C0C_TIP='P',C0C_CHI='P',COC_MNE_UNI='IDDOCDIG.W_DOCDIG.GENEWEB',COC_DES='ID documento',COC_DES_FRM='Codice documento',C0C_FS='N12',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGID';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000303, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGENT.W_DOCDIG.GENEWEB' ,COC_DES='Entità di collegamento',COC_DES_FRM='Entità collegata',C0C_FS='A20',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGENT';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000304, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGKEY1.W_DOCDIG.GENEWEB',COC_DES='KEY1',COC_DES_FRM='Chiave1',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGCODKEY1';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000305, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGKEY2.W_DOCDIG.GENEWEB',COC_DES='KEY2',COC_DES_FRM='Chiave2',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGCODKEY2';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000306, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGKEY3.W_DOCDIG.GENEWEB',COC_DES='KEY3',COC_DES_FRM='Chiave3',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGCODKEY3';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000307, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGKEY4.W_DOCDIG.GENEWEB',COC_DES='KEY4',COC_DES_FRM='Chiave4',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGCODKEY4';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000308, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='DIGKEY5.W_DOCDIG.GENEWEB',COC_DES='KEY5',COC_DES_FRM='Chiave5',C0C_FS='A30',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='DIGCODKEY5';
UPDATE SITATSA.C0CAMPI SET COC_CONTA=100000405, C0C_TIP='P',C0C_CHI=null,COC_MNE_UNI='EMAILPEC.W_PUSER.GENEWEB',COC_DES='Indirizzo PEC? (NON USATO)',COC_DES_FRM='NON USATO',C0C_FS='A1',C0C_TAB1=null,COC_DOM=null,COC_DES_WEB=null WHERE C0C_MNE_BER='USEREMAILPEC';

-- TAB3:
UPDATE SITATSA.TAB3 SET TAB3DESC='Richiesta registrazione',TAB3MOD=null WHERE TAB3COD='G_x10' AND TAB3TIP='FS1';
UPDATE SITATSA.TAB3 SET TAB3DESC='Richiesta iscrizione',TAB3MOD=null WHERE TAB3COD='G_x10' AND TAB3TIP='FS2';
UPDATE SITATSA.TAB3 SET TAB3DESC='Aggiornamento dati iscrizione elenco',TAB3MOD=null WHERE TAB3COD='G_x10' AND TAB3TIP='FS4';
UPDATE SITATSA.TAB3 SET TAB3DESC='Notifica variazioni anagrafiche',TAB3MOD=null WHERE TAB3COD='G_x10' AND TAB3TIP='FS5';
DELETE FROM SITATSA.TAB3 WHERE TAB3COD = 'G_x10' AND TAB3TIP IN ('FS6','FS9');
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('G_x10','FS6','Richiesta variazione dati identificativi anagrafica',null);
INSERT INTO SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD) VALUES ('G_x10','FS9','Tipo di partecipazione impresa alla gara (RTI, singola)',null);

-- W_AZIONI:
INSERT INTO SITATSA.W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('PAGE','VIS','GENE.USRSYS-Scheda.TECNI','Visualizza',0,1,1,3993855647);

-- W_OGGETTI:
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','INS.GENE.USRSYS-Scheda.TECNI.INS-TECNIACCOUNT','Inserisci associazione account-tecnico',1632);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','DEL.GENE.USRSYS-Scheda.TECNI.DEL-TECNIACCOUNT','Elimina associazione account-tecnico',1634);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('FUNZ','MOD.GENE.USRSYS-Scheda.TECNI.SCHEDAMOD','Modifica associazione account-tecnici',1636);
INSERT INTO SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('PAGE','GENE.USRSYS-Scheda.TECNI','Utente applicativo - Pagina "Tecnici"',1665);



----------------------------------------------------------------
---   Aggiornamento cumulativo di GeneWeb da 1.5.7 a 1.6.0   ---
----------------------------------------------------------------
delete from SITATSA.C0ENTIT where C0E_NOM in ('W_DOCDIG.GENEWEB','W_INVCOM.GENEWEB','W_INVCOMDES.GENEWEB','W_LOGEVENTI.GENEWEB','W_PUSER.GENEWEB');
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W_DOCDIG.GENEWEB','P','DOCDIG','Documenti/oggetti Digitali','IDDOCDIG.W_DOCDIG.GENEWEB',null,null,null,null,null);
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W_INVCOM.GENEWEB','P','COMUNIC','Comunicazioni','IDCOM.W_INVCOM.GENEWEB',null,null,null,null,null);
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W_INVCOMDES.GENEWEB','P','COMDES','Soggetti destinatari','IDCOM.W_INVCOMDES.GENEWEB','W_INVCOM.GENEWEB','IDCOM.W_INVCOM.GENEWEB',null,null,null);
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W_LOGEVENTI.GENEWEB','P','LOGEVENTI','Tracciatura log accessi all''applicativo web','IDEVENTO.W_LOGEVENTI.GENEWEB',null,null,null,null,null);
Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W_PUSER.GENEWEB','P','PUSERG','Collegamento utenti BKO con utenti Portale','IDUSER.W_PUSER.GENEWEB',null,null,null,null,null);

-- Aggiornamento W_OGGETTI da 1.5.7 a 1.5.8
delete from SITATSA.W_OGGETTI where TIPO = 'FUNZ' and OGGETTO = 'ALT.GENE.ImprScheda.InviaMailAttivazioneSuPortale';
Insert into SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.GENE.ImprScheda.InviaMailAttivazioneSuPortale','Funzione Invia mail attivazione utenza su portale',1790);

-- Aggiornamento di TAB1 da 1.5.8 a 1.6.0
DELETE FROM SITATSA.TAB1 WHERE TAB1COD = 'W0003' AND TAB1TIP IN (0,1,2,3);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('W0003',0,'CSV',null,null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('W0003',1,'Excel',null,null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('W0003',2,'RTF',null,null);
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD) values ('W0003',3,'PDF',null,null);

-- Aggiornamento di TAB3 da 1.5.8 a 1.6.0
DELETE FROM SITATSA.TAB3 WHERE TAB3COD = 'G_x03' AND TAB3TIP IN ('U','G','S','M');
Insert into SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD,TAB3NORD) values ('G_x03','U','Una sola volta',null,null);
Insert into SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD,TAB3NORD) values ('G_x03','G','Giornaliera',null,null);
Insert into SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD,TAB3NORD) values ('G_x03','S','Settimanale',null,null);
Insert into SITATSA.TAB3 (TAB3COD,TAB3TIP,TAB3DESC,TAB3MOD,TAB3NORD) values ('G_x03','M','Mensile',null,null);


-- Aggiornamento di TAB6 da 1.5.8 a 1.6.0
DELETE FROM SITATSA.TAB6 WHERE TAB6COD = 'G__1' AND TAB6TIP = 'G_x03';
DELETE FROM SITATSA.TAB6 WHERE TAB6COD = 'W1_1' AND TAB6TIP IN ('W0002','W0003');
Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_x03','Tipo di schedulazione delle ricerche');
Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('W1_1','W0002','Stato elaborazione ricerca schedulata');
Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('W1_1','W0003','Formato export risultato ricerca schedulata');

-- Creazione tabella W_CODASCHED
CREATE TABLE SITATSA.W_CODASCHED
 (ID_CODASCHED NUMERIC(12) NOT NULL,
  ID_SCHEDRIC NUMERIC(12) NOT NULL,
  ID_RICERCA NUMERIC(12) NOT NULL,
  STATO NUMERIC(1) NOT NULL,
  MSG VARCHAR(200),
  NOMEFILE VARCHAR(20),
  DATA_ESEC TIMESTAMP NOT NULL,
  ESECUTORE NUMERIC(12) NOT NULL,
  PROFILO_OWNER VARCHAR(20),
  CODAPP VARCHAR(10) NOT NULL)
  IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
  
ALTER TABLE SITATSA.W_CODASCHED ADD CONSTRAINT W_CODASCHED_PK PRIMARY KEY (ID_CODASCHED); 
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W_CODASCHED TO USER SITATSA; 

-- Creazione tabella W_SCHEDRIC
CREATE TABLE SITATSA.W_SCHEDRIC
 (ID_SCHEDRIC NUMERIC(12) NOT NULL,
  ID_RICERCA NUMERIC(12) NOT NULL,
  TIPO VARCHAR(1) NOT NULL,
  ATTIVO NUMERIC(1) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ORA_AVVIO NUMERIC(2) NOT NULL,
  MINUTO_AVVIO NUMERIC(2) NOT NULL,
  DATA_PRIMA_ESEC TIMESTAMP,
  GIORNO NUMERIC(3),
  SETTIMANA NUMERIC(2),
  GIORNI_SETTIMANA VARCHAR(14),
  MESE VARCHAR(27),
  GIORNI_MESE VARCHAR(84),
  FORMATO NUMERIC(1),
  EMAIL VARCHAR(500),
  DATA_ULT_ESEC TIMESTAMP,
  DATA_PROX_ESEC TIMESTAMP,
  OWNER NUMERIC(12) NOT NULL,
  ESECUTORE NUMERIC(12) NOT NULL,
  PROFILO_OWNER VARCHAR(20),
  NO_OUTPUT_VUOTO NUMERIC(1) NOT NULL,
  CODAPP VARCHAR(10) NOT NULL,
  RIPETI_DOPO_MINUTI NUMERIC(3))
  IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
  
ALTER TABLE SITATSA.W_SCHEDRIC ADD CONSTRAINT W_SCHEDRIC_PK PRIMARY KEY (ID_SCHEDRIC); 
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W_SCHEDRIC TO USER SITATSA; 

-- Aggiornamento di W_GENCHIAVI da 1.5.8 a 1.6.0
insert into SITATSA.W_GENCHIAVI (TABELLA,CHIAVE) values ('W_SCHEDRIC',0);
insert into SITATSA.W_GENCHIAVI (TABELLA,CHIAVE) values ('W_CODASCHED',0);

-- Aggiornamento di W_OGGETTI da 1.5.8 a 1.6.0
Insert into SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('SUBMENU','REPORT.Risultati-schedulazioni','Risultati schedulazioni',1710);
Insert into SITATSA.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('SUBMENU','REPORT.Schedulazioni','Schedulazione report',1700);

-- Aggiornamento W_RICERCHE
ALTER TABLE SITATSA.W_RICERCHE ADD COLUMN VISPARAM NUMERIC(1);
ALTER TABLE SITATSA.W_RICERCHE ADD COLUMN LINKSCHEDA NUMERIC(1);
ALTER TABLE SITATSA.W_RICERCHE ADD COLUMN CODREPORTWS VARCHAR(30);
ALTER TABLE SITATSA.W_RICERCHE ALTER COLUMN CODREPORTWS SET NOT NULL;
REORG TABLE SITATSA.W_RICERCHE;
ALTER TABLE SITATSA.W_RICERCHE ADD CONSTRAINT UN_RICERCHE_CODREPORTWS UNIQUE(CODREPORTWS);
REORG TABLE SITATSA.W_RICERCHE;

UPDATE SITATSA.W_RICERCHE SET VISPARAM = 0 WHERE FAMIGLIA in (0,1) AND VISPARAM IS NULL;
UPDATE SITATSA.W_RICERCHE SET LINKSCHEDA = 0 WHERE FAMIGLIA in (0,1) AND LINKSCHEDA IS NULL;

-- Aggiornamenti delle versioni di W9
UPDATE SITATSA.ELDAVER SET NUMVER = '1.6.0'  WHERE CODAPP= 'W_';

------------------------------
-- SITATSA 2.1.0
--------------------------

-- SITAT

Update SITATSA.TAB1 SET TAB1DESC='Anagrafica e bando di gara' WHERE TAB1COD='W3020' AND TAB1TIP=988;
ALTER TABLE SITATSA.W9GARA ADD COLUMN PREV_BANDO VARCHAR(1);
REORG TABLE SITATSA.W9GARA;
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'PREV_BANDO.W9GARA.W9','W9GABANDO','E'' prevista la pubblicazione del bando?','Pubblicazione bando?','Pubblicazione bando?','A2',NULL,'SN' );
Update SITATSA.W9GARA SET PREV_BANDO='2';
Update SITATSA.W9GARA SET PREV_BANDO='1' WHERE DGURI IS NOT NULL OR DSCADE IS NOT NULL;


Update SITATSA.TAB1 set TAB1NORD=TAB1NORD+1 WHERE TAB1COD='W3020' and TAB1NORD>=6;
Insert into SITATSA.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1NORD) values ('W3020',984,'Comunicazione esito',6);


CREATE TABLE SITATSA.W9ESITO
  (CODGARA NUMERIC(10) NOT NULL,
  CODLOTT NUMERIC(10) NOT NULL,
	ESITO_PROCEDURA NUMERIC(7),
	FILE_ALLEGATO BLOB (100 M ) LOGGED NOT COMPACT
	   ) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.W9ESITO ADD CONSTRAINT W9ESITO_PK PRIMARY KEY (CODGARA,CODLOTT);
 
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9ESITO TO USER SITATSA;

Insert into SITATSA.W9ESITO (SELECT A.CODGARA,A.CODLOTT,ESITO_PROCEDURA,FILE_ALLEGATO FROM SITATSA.W9LOTT L,SITATSA.W9APPA A WHERE A.CODGARA=L.CODGARA AND A.CODLOTT=L.CODLOTT);


Delete from SITATSA.C0CAMPI WHERE C0C_MNE_BER='W9LOESIPROC';

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODGARA.W9ESITO.W9','W3ESCODGARA','Codice della gara','Codice della gara','N10',null,null,'Codice della gara');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODLOTT.W9ESITO.W9','W9ESCODLOTT','Numero del lotto','Num. lotto','N10',null,null,'Numero del lotto');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ESITO_PROCEDURA.W9ESITO.W9','W9LOESIPROC','Esito procedura','Esito procedura','Esito procedura','A100','W3022',NULL );
Insert into SITATSA.C0ENTIT (C0E_NOM, C0E_NUM, C0E_TIP, COE_ARG, C0E_DES, C0E_KEY, C0E_NOM_EX, COE_KEY_EX, COE_FRM_RE) values ('W9ESITO.W9',80011670,'E','ESITI','Esiti delle gare ','CODGARA.W9ESITO.W9,CODLOTT.W9ESITO.W9','W9LOTT.W9','CODGARA.W9LOTT.W9,CODLOTT.W9LOTT.W9','w9_esit0');

--Cancellazione scheda sicurezza
Update SITATSA.TAB1 SET TAB1NORD=0 where tab1cod='W3020' and TAB1TIP=999;
Delete from SITATSA.W9FASI WHERE FASE_ESECUZIONE=999;

Update SITATSA.C0CAMPI set COC_DES='Nominato il dir. operativo ai sensi art.21 c. 3 LR 38/07?', COC_DES_WEB='Nominato dir. operativo ai sensi art.21 c.3 LR38/07?' where C0C_MNE_BER='W3DIROPE';
ALTER TABLE SITATSA.W9SIC ADD COLUMN TUTOR VARCHAR(1);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'TUTOR.W9SIC.W9','W9SITUTOR','Nominato il tutor ai sensi art.22 LR 38/07?','Nomina tutor?','Nominato il tutor ai sensi art.22 LR 38/07?','A2',NULL,'SN' );
REORG TABLE SITATSA.W9SIC;

Update SITATSA.W9INCA SET NUM_INCA=NUM_INCA+100,SEZIONE='IN' WHERE SEZIONE='SI';

Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W3004', 98, 'Direttore operativo', NULL, 0);


ALTER TABLE SITATSA.W9INIZ ADD COLUMN INCONTRI_VIGIL NUMERIC(7);
REORG TABLE SITATSA.W9INIZ;
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'INCONTRI_VIGIL.W9INIZ.W9','W9ININCVIGIL','Effettuati incontri con organi vigilanza (art23 c2 LR38/07)?','Incontri org.vigil.?','Effettuati incontri organi vigilanza(art23 c2 LR38/07)?','A100','W9005',null );

Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('W9_1','W9005','Effettuazione incontri con organi vigilanza');
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W9005', 1, 'Sì', NULL, 1);
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W9005', 2, 'No', NULL, 2);
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W9005', 3, 'Previsti ma non ancora realizzati', NULL, 3);


Update SITATSA.C0CAMPI set COC_DES='Breve desc.misure aggiuntive e migliorative per la sicurezza' where C0C_MNE_BER='W3MSDESCMI';
Update SITATSA.C0ENTIT set C0E_DES='Misure aggiuntive per la sicurezza' WHERE C0E_NOM='W9MISSIC.W9';                                  


Update SITATSA.TAB1 Set TAB1DESC='Misure aggiuntive e migliorative per la sicurezza' WHERE TAB1COD='W3020' AND TAB1TIP=993;
Update SITATSA.TAB1 Set TAB1DESC='Segnalazione infortuni ai sensi art.23 c.1 let.c' WHERE TAB1COD='W3020' AND TAB1TIP=994;
Update SITATSA.TAB1 Set TAB1DESC='Inadempienze disposizioni sicurezza e regolarità del lavoro ai sensi dell’art.23 LR 38/07' WHERE TAB1COD='W3020' AND TAB1TIP=995;
Update SITATSA.TAB1 Set TAB1DESC='Mancata aggiud. def. o pagamento per irregolarità contrib. ed assicurativa (art.17c.1 e 2 LR 38/07)' WHERE TAB1COD='W3020' AND TAB1TIP=996;
Update SITATSA.TAB1 Set TAB1DESC='Esito negativo verifiche dell''idoneità tecnico professionale ai sensi dell''art. 16 c.1 LR 38/07' WHERE TAB1COD='W3020' AND TAB1TIP=997;


ALTER TABLE SITATSA.W9INASIC ADD COLUMN COMMA5 VARCHAR(1);
ALTER TABLE SITATSA.W9INASIC ADD COLUMN COMMA6 VARCHAR(1);
REORG TABLE SITATSA.W9INASIC;

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'COMMA5.W9INASIC.W9','W3COMMA5','Mancata estensione formaz. agli altri soggetti nel cantiere','In.comma 5 art 23','Mancata estensione formaz. agli altri soggetti nel cantiere','A2',null,'SN' );
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'COMMA6.W9INASIC.W9','W3COMMA6','Inad. moduli informativi di ingr.per lavoratori nel cantiere','In.comma 6 art 23','Inad. moduli informativi di ingr.per lavoratori nel cantiere','A2',null,'SN' );


ALTER TABLE SITATSA.W9REGCON ADD COLUMN RISCONTRO_IRR NUMERIC(7);
ALTER TABLE SITATSA.W9REGCON ADD COLUMN DATACOMUN TIMESTAMP;
REORG TABLE SITATSA.W9REGCON;

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'RISCONTRO_IRR.W9REGCON.W9','W9RCRISCIRR','Riscontro irregolarità contributiva dell''Operatore Economico','Riscontro irregol.','Riscontro irregolarità contributiva Operatore Economico','A100','W9006',null);
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'DATACOMUN.W9REGCON.W9','W9RCDATACOMU','Data atto comunicazione mancata aggiud. o pagamento','Data atto comunicaz.','Data atto comunicazione mancata aggiud. o pagamento','A10',null,'DATA_ELDA');

Insert into SITATSA.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('W9_1','W9006','Riscontro irregolarità contributiva ed assicurativa');
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W9006', 1, 'All''aggiudicazione definitiva', NULL, 1);
Insert into SITATSA.TAB1 (TAB1COD, TAB1TIP, TAB1DESC, TAB1MOD, TAB1NORD) Values ('W9006', 2, 'Al pagamento', NULL, 2);


CREATE TABLE SITATSA.W9DOCFASE
  (CODGARA NUMERIC(10) NOT NULL,
  CODLOTT NUMERIC(10) NOT NULL,
	FASE_ESECUZIONE NUMERIC(7) NOT NULL,
	NUM_FASE NUMERIC(5) NOT NULL,
	NUMDOC NUMERIC(4) NOT NULL,
	TITOLO VARCHAR(250),
	FILE_ALLEGATO BLOB (100 M ) LOGGED NOT COMPACT
	   ) IN TBS_SITATSA_N0 INDEX IN TBS_SITATSA_N0;
 ALTER TABLE SITATSA.W9DOCFASE ADD CONSTRAINT W9DOCFASE_PK PRIMARY KEY (CODGARA,CODLOTT,FASE_ESECUZIONE,NUM_FASE,NUMDOC);
 
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATSA.W9DOCFASE TO USER SITATSA;

Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODGARA.W9DOCFASE.W9','W9DFCODGARA','Codice della gara','Codice della gara','N10',null,null,'Codice della gara');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODLOTT.W9DOCFASE.W9','W9DFCODLOTT','Numero del lotto','Num. lotto','N10',null,null,'Numero del lotto');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','FASE_ESECUZIONE.W9DOCFASE.W9','W9DFFASEESEC','Fase di esecuzione','Fase di esecuzione','A100','W3020',null,'Tipologia della fase di esecuzione');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUM_FASE.W9DOCFASE.W9','W9DFNUMFASE','Numero progressivo fase','Numero progressivo','N5',null,null,'Numero progressivo fase');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUMDOC.W9DOCFASE.W9','W9DFNUMDOC','Numero progressivo documento','Numero documento','N4',null,null,'Numero documento');
Insert into SITATSA.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'TITOLO.W9DOCFASE.W9','W9DFTITOLO','Titolo del documento','Titolo','A250',null,null,'Titolo');

Insert into SITATSA.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values 
('W9DOCFASE.W9',80011650,'E','DOCFAS','Documentazione associata ad una fase','CODGARA.W9DOCFASE.W9,CODLOTT.W9DOCFASE.W9,FASE_ESECUZIONE.W9DOCFASE.W9,NUM_FASE.W9DOCFASE.W9','W9FASI.W9','CODGARA.W9FASI.W9,CODLOTT.W9FASI.W9,FASE_ESECUZIONE.W9FASI.W9,NUM.W9FASI.W9',null,null,'w9_docf0');


ALTER TABLE SITATSA.PIATRI ALTER COLUMN CONTRI SET DATA TYPE NUMERIC(10);
ALTER TABLE SITATSA.INTTRI ALTER COLUMN CONTRI SET DATA TYPE NUMERIC(10);
ALTER TABLE SITATSA.IMMTRAI ALTER COLUMN CONTRI SET DATA TYPE NUMERIC(10);
ALTER TABLE SITATSA.IMMTRAI ALTER COLUMN DESIMM SET DATA TYPE VARCHAR(400);
 
REORG TABLE SITATSA.PIATRI;
REORG TABLE SITATSA.INTTRI;
REORG TABLE SITATSA.IMMTRAI;
Update SITATSA.C0CAMPI set C0C_FS='N10' where C0C_MNE_BER in('T2CONTRI','T2CONTRI1','T2ICONTRI2');
Update SITATSA.C0CAMPI set C0C_FS='A400' where C0C_MNE_BER ='T2IDESIMM';

-- Aggiornamento descrizione del profilo SA-AVVISI (ex Comunicazione avvisi)
update SITATSA.W_GRUPPI set nome = 'Manifestazione di interesse ed altri avvisi' where id_gruppo = 6;
update SITATSA.W_PROFILI set nome = 'Manifestazione di interesse ed altri avvisi', descrizione = 'Sitat SA - Manifestazione di interesse ed altri avvisi', crc = 3427011599 where cod_profilo = 'SA-AVVISI';

-- Altre modifiche
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (1''anno)' where C0C_MNE_BER='T2IM1TRI';
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (2''anno)' where C0C_MNE_BER='T2IM2TRI';
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (3''anno)' where C0C_MNE_BER='T2IM3TRI';
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (1''anno)' where C0C_MNE_BER='T2IIM1TRI';
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (2''anno)' where C0C_MNE_BER='T2IIM2TRI';
Update SITATSA.C0CAMPI set COC_DES='Trasferimento immobili (3''anno)' where C0C_MNE_BER='T2IIM3TRI';

-- Correzione errore
update SITATSA.C0CAMPI set COC_DES='Modalità di pagamento del corrispettivo', COC_DES_FRM='Modalità pagamento', COC_DES_WEB='Modalità di pagamento del corrispettivo' where COC_MNE_UNI= 'FLAG_PAGAMENTO.W9AVAN.W9' and C0C_MNE_BER='W3FLAG_PAG';

UPDATE SITATSA.ELDAVER Set numver='2.1.0' where codapp='W9';