------ SCHEMA SITAT ORT ----------
--#SET TERMINATOR ;

SET SCHEMA = SITATORT;
SET CURRENT PATH = SITATORT;



UPDATE COMMAND OPTIONS USING s OFF;
DROP procedure aggiorna;
UPDATE COMMAND OPTIONS USING s ON;

------ CARATTERE TERMINATORE ----------
--#SET TERMINATOR @
--------------------------------
-- AGGIORNAMENTO SITAT/VIGILANZA
-- Database: DB2
-- Versione: 3.0.0 --> 3.1.0
------------------------------


--#SET TERMINATOR @

create procedure aggiorna ()
begin

	Declare v_sql varchar(5000);
	Declare v_max varchar(10);

	IF (select count(*) from eldaver where codapp='W9' and (numver='3.0.0' or numver like '3.0.0.%'))=1
	THEN
	
	------------------------------------------------------------------------------------------------
	------------------------		MODIFICA STRUTTURA TABELLE			------------------------
	------------------------------------------------------------------------------------------------
		
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN NOME_STRU_INFRASTR set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN IND_AREA_RIFER set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN DESCRIZIONE_INTERVENTO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN DESC_STRUM_PROGR set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN DENOM_IMPR_STAB set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN DENOM_IMPR_STAB_PREC set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN DENOMINAZIONE_PROGETTO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN ENTE set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN OBIETT_CORSO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN MOD_INTERVENTO_FREQUENZA set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN SERVIZIO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN BENE set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN RAGIONE_SOCIALE set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN RAGIONE_SOCIALE_PREC set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN BENEFICIARIO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN ATTO_AMMINISTR set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI ALTER COLUMN SCOPO_INTERVENTO set DATA TYPE VARCHAR(1000)';
		EXECUTE immediate v_sql;
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE CUPDATI');
	
		SET v_sql = 'ALTER TABLE CUPDATI ADD COLUMN TMP VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'UPDATE CUPDATI SET TMP =SUBSTR(ALTRE_INFORMAZIONI,1,1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI DROP COLUMN ALTRE_INFORMAZIONI';
		EXECUTE immediate v_sql;
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE CUPDATI');
		SET v_sql = 'ALTER TABLE CUPDATI ADD COLUMN ALTRE_INFORMAZIONI VARCHAR(1000)';
		EXECUTE immediate v_sql;
		SET v_sql = 'UPDATE CUPDATI SET ALTRE_INFORMAZIONI=TMP';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE CUPDATI DROP COLUMN TMP';
		EXECUTE immediate v_sql;
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE CUPDATI');
		
		SET v_sql = 'Create table W3GARA (
		NUMGARA NUMERIC(10) not null,
		OGGETTO VARCHAR(1024),
		RUP_CODTEC VARCHAR(10),
		ID_GARA VARCHAR(20),
		IMPORTO_GARA NUMERIC(24,5),
		IMPORTO_SA_GARA NUMERIC(24,5),
		DATA_CANCELLAZIONE_GARA TIMESTAMP,
		DATA_TERMINE_PAGAMENTO TIMESTAMP,
		DATA_COMUN TIMESTAMP,
		DATA_INIB_PAGAM TIMESTAMP,
		DATA_CONFERMA_GARA TIMESTAMP,
		TIPO_SCHEDA VARCHAR(5),
		MODO_INDIZIONE VARCHAR(5),
		MODO_REALIZZAZIONE VARCHAR(5),
		ID_MOTIVAZIONE VARCHAR(5),
		NOTE_CANC VARCHAR(1000),
		CIG_ACC_QUADRO VARCHAR(10),
		NUMERO_LOTTI NUMERIC(5),
		DATA_CREAZIONE TIMESTAMP,
		ID_OSSERVATORIO VARCHAR(2000),
		ID_STATO_GARA VARCHAR(5),
		DATA_PERFEZIONAMENTO_BANDO TIMESTAMP,
		SYSCON NUMERIC(12),
		STATO_SIMOG NUMERIC(7),
		TIPO_OPERAZIONE VARCHAR(5),
		GARA_UUID VARCHAR(40),
		COLLABORAZIONE NUMERIC(10),
		DATA_GUCE TIMESTAMP,
		DATA_GURI TIMESTAMP,
		DATA_ALBO TIMESTAMP,
		DATA_BORE TIMESTAMP,
		QUOTIDIANI_NAZ NUMERIC(5),
		QUOTIDIANI_REG NUMERIC(5),
		PERIODICI NUMERIC(5),
		PROFILO_COMMITTENTE VARCHAR(2),
		SITO_MINISTERO_INF_TRASF VARCHAR(2),
		SITO_OSSERVATORIO VARCHAR(2),
		NUMERO_GUCE VARCHAR(20),
		NUMERO_GURI VARCHAR(20),
		NUMERO_BORE VARCHAR(20),
		LINK_SITO VARCHAR(250),
		FLAG_BENICULT VARCHAR(2),
		FLAG_SOSPESO VARCHAR(2),
		ID_ESCLUSIONE NUMERIC(7),
		PROVV_PRESA_CARICO VARCHAR(250),
		ESCLUSO_AVCPASS VARCHAR(1),
		ORA_SCADENZA VARCHAR(5),
		DSCAD_RICHIESTA_INVITO TIMESTAMP,
		DATA_LETTERA_INVITO TIMESTAMP,
		URGENZA_DL133 VARCHAR(1),
		M_RICH_CIG NUMERIC(7),
		M_RICH_CIG_COMUNI NUMERIC(7),
		PRIMARY KEY (NUMGARA))';
		EXECUTE immediate v_sql;
		
		SET v_sql = 'Create table W3GARADOC (
		NUMGARA NUMERIC(10) not null,
		NUMDOC NUMERIC(3) not null,
		TIPO_DOCUMENTO VARCHAR(5),
		NOTE_DOCUMENTO VARCHAR(2000),
		NOME_DOCUMENTO VARCHAR(200),
		DOCUMENTO BLOB,
		PRIMARY KEY (NUMGARA,NUMDOC))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3GARAREQ (
		NUMGARA NUMERIC(10) not null,
		NUMREQ NUMERIC(3) not null,
		CODICE_DETTAGLIO VARCHAR(5),
		DESCRIZIONE VARCHAR(80),
		VALORE VARCHAR(20),
		FLAG_ESCLUSIONE VARCHAR(1),
		FLAG_COMPROVA_OFFERTA VARCHAR(1),
		FLAG_AVVALIMENTO VARCHAR(1),
		FLAG_BANDO_TIPO VARCHAR(1),
		FLAG_RISERVATEZZA VARCHAR(1),
		PRIMARY KEY (NUMGARA,NUMREQ))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3GARAREQCIG (
		NUMGARA NUMERIC(10) not null,
		NUMREQ NUMERIC(3) not null,
		NUMCIG NUMERIC(3) not null,
		CIG VARCHAR(10),
		PRIMARY KEY (NUMGARA,NUMREQ,NUMCIG))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3GARAREQDOC (
		NUMGARA NUMERIC(10) not null,
		NUMREQ NUMERIC(3) not null,
		NUMDOC NUMERIC(3) not null,
		CODICE_TIPO_DOC NUMERIC(7),
		DESCRIZIONE VARCHAR(800),
		EMETTITORE VARCHAR(300),
		FAX VARCHAR(13),
		TELEFONO VARCHAR(13),
		MAIL VARCHAR(80),
		MAIL_PEC VARCHAR(80),
		PRIMARY KEY (NUMGARA,NUMREQ,NUMDOC))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3GARAMERC	(
		NUMGARA NUMERIC(10) NOT NULL,
		NUMMERC NUMERIC(3) NOT NULL,
		CATEGORIA NUMERIC(7),
		PRIMARY KEY (NUMGARA, NUMMERC))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3TABREQ (
		CODICE_DETTAGLIO VARCHAR(5) not null,
		DESCRIZIONE VARCHAR(2000),
		PRIMARY KEY (CODICE_DETTAGLIO))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3LOTT (
		NUMGARA NUMERIC(10) not null,
		NUMLOTT NUMERIC(10) not null,
		CIG VARCHAR(10),
		OGGETTO VARCHAR(1024),
		SOMMA_URGENZA VARCHAR(1),
		IMPORTO_LOTTO NUMERIC(24,5),
		IMPORTO_SA NUMERIC(24,5),
		IMPORTO_IMPRESA NUMERIC(24,5),
		CPV VARCHAR(12),
		ID_SCELTA_CONTRAENTE NUMERIC(7),
		ID_CATEGORIA_PREVALENTE VARCHAR(5),
		DATA_PUBBLICAZIONE TIMESTAMP,
		DATA_SCADENZA_PAGAMENTI TIMESTAMP,
		DATA_COMUNICAZIONE TIMESTAMP,
		DATA_INIB_PAGAMENTO TIMESTAMP,
		ID_MOTIVAZIONE VARCHAR(5),
		NOTE_CANC VARCHAR(1000),
		TIPO_CONTRATTO VARCHAR(5),
		FLAG_ESCLUSO VARCHAR(1),
		LUOGO_ISTAT VARCHAR(20),
		LUOGO_NUTS VARCHAR(20),
		IMPORTO_ATTUAZIONE_SICUREZZA NUMERIC(24,5),
		TRIENNIO_ANNO_INIZIO NUMERIC(5),
		TRIENNIO_ANNO_FINE NUMERIC(5),
		TRIENNIO_PROGRESSIVO NUMERIC(5),
		ANNUALE_CUI_MININF VARCHAR(22),
		DATA_CREAZIONE_LOTTO TIMESTAMP,
		DATA_CANCELLAZIONE_LOTTO TIMESTAMP,
		STATO_SIMOG NUMERIC(7),
		LOTTO_UUID VARCHAR(40),
		ID_ESCLUSIONE NUMERIC(7),
		FLAG_PREVEDE_RIP VARCHAR(1),
		FLAG_RIPETIZIONE VARCHAR(1),
		CIG_ORIGINE_RIP VARCHAR(10),
		ORA_SCADENZA VARCHAR(5),
		STATO_AVCPASS NUMERIC(7),
		DSCAD_RICHIESTA_INVITO TIMESTAMP,
		DATA_LETTERA_INVITO TIMESTAMP,
		FLAG_CUP VARCHAR(1),
		PRIMARY KEY (NUMGARA,NUMLOTT))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3LOTTCATE (
		NUMGARA NUMERIC(10) not null,
		NUMLOTT NUMERIC(10) not null,
		NUMCATE NUMERIC(3) not null,
		CATEGORIA VARCHAR(5),
		PRIMARY KEY (NUMGARA,NUMLOTT,NUMCATE))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3LOTTTIPI (
		NUMGARA NUMERIC(10) not null,
		NUMLOTT NUMERIC(10) not null,
		NUMTIPI NUMERIC(3) not null,
		IDAPPALTO NUMERIC(7),
		PRIMARY KEY (NUMGARA,NUMLOTT,NUMTIPI))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3LOTTCUP (
		NUMGARA NUMERIC(10) not null,
		NUMLOTT NUMERIC(10) not null,
		NUMCUP NUMERIC(3) not null,
		CUP VARCHAR(15),
		DATI_DIPE VARCHAR(1024),
		PRIMARY KEY (NUMGARA,NUMLOTT,NUMCUP))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3USRSYS (
		SYSCON NUMERIC(12) not null,
		SIMOGWSUSER VARCHAR(100),
		SIMOGWSPASS VARCHAR(100),
		RUP_CODTEC VARCHAR(10),
		SIMAPWSUSER VARCHAR(100),
		SIMAPWSPASS VARCHAR(100),
		PRIMARY KEY (SYSCON))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3AZIENDAUFFICIO (
		ID NUMERIC(10) not null,
		AZIENDA_CF VARCHAR(16),
		AZIENDA_DENOM VARCHAR(250),
		INDEXCOLL VARCHAR(100),
		UFFICIO_DENOM VARCHAR(250),
		UFFICIO_ID VARCHAR(40),
		UFFICIO_PROFILO VARCHAR(50),
		PRIMARY KEY (ID))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3USRSYSCOLL (
		SYSCON NUMERIC(12) not null,
		W3AZIENDAUFFICIO_ID NUMERIC(10) not null,
		PRIMARY KEY (SYSCON,W3AZIENDAUFFICIO_ID))';
		EXECUTE immediate v_sql;

		SET v_sql = 'ALTER TABLE W3USRSYS ADD CONSTRAINT W3USRSYS_FK	FOREIGN KEY (SYSCON) REFERENCES USRSYS(SYSCON) ON DELETE CASCADE';
		EXECUTE immediate v_sql;
		SET v_sql = 'ALTER TABLE W3USRSYSCOLL ADD CONSTRAINT W3USRSYSCOLL_FK FOREIGN KEY (SYSCON) REFERENCES USRSYS(SYSCON) ON DELETE CASCADE';
		EXECUTE immediate v_sql;


		SET v_sql = 'Create table W3SMARTCIG (
		CODRICH NUMERIC(10) NOT NULL,
		CIG VARCHAR(10),
		STATO NUMERIC(7),
		FATTISPECIE VARCHAR(5),
		IMPORTO NUMERIC(24,5),
		OGGETTO VARCHAR(1024),
		ID_SCELTA_CONTRAENTE VARCHAR(5),
		TIPO_CONTRATTO VARCHAR(5),
		CIG_ACC_QUADRO VARCHAR(10),
		CUP VARCHAR(15),
		M_RICH_CIG_COMUNI VARCHAR(5),
		M_RICH_CIG VARCHAR(5),
		RUP VARCHAR(10),
		COLLABORAZIONE NUMERIC(10),
		DATA_OPERAZIONE TIMESTAMP,
		SYSCON NUMERIC(12),
		PRIMARY KEY (CODRICH))';
		EXECUTE immediate v_sql;

		SET v_sql = 'Create table W3SMARTCIGMERC (
		CODRICH NUMERIC(10) NOT NULL,
		NUMMERC NUMERIC(3) NOT NULL,
		CATEGORIA NUMERIC(7),
		PRIMARY KEY (CODRICH, NUMMERC))';
		EXECUTE immediate v_sql;


		--- View CIG e SMARTCIG
		SET v_sql = 'CREATE VIEW V_W3GARE AS
		SELECT ''G_'' || cast(INT(NUMGARA) as char(10)) AS CODICE, ''G'' AS TIPO_GARA, NUMGARA, ID_GARA, STATO_SIMOG, DATA_CONFERMA_GARA, OGGETTO, IMPORTO_GARA, SYSCON, RUP_CODTEC FROM W3GARA 
		UNION
		SELECT ''S_'' || cast(INT(CODRICH) as char(10)) AS CODICE, ''S'' AS TIPO_GARA, CODRICH AS NUMGARA, CIG AS ID_GARA, STATO AS STATO_SIMOG, DATA_OPERAZIONE AS DATA_CONFERMA_GARA, OGGETTO, IMPORTO AS IMPORTO_GARA, SYSCON, RUP AS RUP_CODTEC FROM W3SMARTCIG';
		EXECUTE immediate v_sql;


		Update ELDAVER set NUMVER='3.1.0', DATVET=CURRENT_TIMESTAMP where CODAPP='W9';		
	END IF;
end@

call aggiorna@
drop procedure aggiorna@

--------------------------------
-- AGGIORNAMENTO SITAT/VIGILANZA
-- Database: DB2
-- Versione: 3.1.0 --> 4.0.0
------------------------------

------ CARATTERE TERMINATORE ----------
--#SET TERMINATOR @

create procedure aggiorna ()
begin

	Declare v_sql varchar(10000);
	Declare v_max varchar(10);

	IF ( select count(*) from eldaver where codapp='W9' and (numver='3.1.0' or numver like '3.1.0%') ) = 1
	THEN


		------------------------------------------------------------------------------------------------
		------------------------		MODIFICA STRUTTURA TABELLE				------------------------
		------------------------------------------------------------------------------------------------

		SET v_sql=
			'CREATE TABLE TAB_CONTROLLI (
			CODAPP VARCHAR(5) NOT NULL,
			NUM NUMERIC(7) NOT NULL,
			ENTITA VARCHAR(50),
			SEZIONE VARCHAR(50),
			TITOLO VARCHAR(100),
			CONDIZIONE VARCHAR(2000),
			MSG VARCHAR(2000),
			TIPO VARCHAR(1),
			PRIMARY KEY (CODAPP,NUM))';
		EXECUTE immediate v_sql;


		SET v_sql=
			'CREATE TABLE ESITI_AGGIUDICATARI (
			CODGARA NUMERIC(10) NOT NULL,
			NUM_PUBB NUMERIC(5) NOT NULL,
			NUM_AGGI NUMERIC(3) NOT NULL,
			ID_TIPOAGG NUMERIC(7),
			RUOLO NUMERIC(7),
			CODICE_INPS VARCHAR(20),
			CODICE_INAIL VARCHAR(20),
			CODICE_CASSA VARCHAR(20),
			CODIMP VARCHAR(10),
			ID_GRUPPO NUMERIC(3),
			PRIMARY KEY (CODGARA, NUM_PUBB, NUM_AGGI))';
		EXECUTE immediate v_sql;
	
		SET v_sql=
			'CREATE TABLE W9DOCAVVISO (
			CODEIN VARCHAR(16) NOT NULL,
			IDAVVISO NUMERIC(10) NOT NULL,
			CODSISTEMA NUMERIC(7) NOT NULL,
			NUMDOC NUMERIC(4) NOT NULL,
			TITOLO VARCHAR(250),
			FILE_ALLEGATO BLOB (10 M),
			URL VARCHAR(2000),
			PRIMARY KEY (CODEIN,IDAVVISO,CODSISTEMA,NUMDOC))';
		EXECUTE immediate v_sql;
	
	
		SET v_sql= 'ALTER TABLE UFFICI ADD COLUMN CODICE_UFFICIO VARCHAR(6)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9APPA 	ADD COLUMN FIN_REGIONALE VARCHAR(1)
													ADD COLUMN FLAG_IMPORTI VARCHAR(1)
													ADD COLUMN FLAG_SICUREZZA VARCHAR(1)
													ADD COLUMN FLAG_LIVELLO_PROGETTUALE VARCHAR(100)
													ADD COLUMN VERIFICA_CAMPIONE VARCHAR(1)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9AVAN ADD COLUMN SUBAPPALTI VARCHAR(1)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9VARI ADD COLUMN FLAG_VARIANTE VARCHAR(1)
													ADD COLUMN QUINTO_OBBLIGO VARCHAR(1)
													ADD COLUMN FLAG_IMPORTI VARCHAR(1)
													ADD COLUMN FLAG_SICUREZZA VARCHAR(1)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9COLL ADD COLUMN FLAG_SINGOLO_COMMISSIONE VARCHAR(1)
													ADD COLUMN DATA_APPROVAZIONE TIMESTAMP
													ADD COLUMN FLAG_IMPORTI VARCHAR(1)
													ADD COLUMN FLAG_SICUREZZA VARCHAR(1)
													ADD COLUMN FLAG_SUBAPPALTATORI VARCHAR(1)
													ADD COLUMN DATA_INIZIO_AMM_RISERVE TIMESTAMP
													ADD COLUMN DATA_FINE_AMM_RISERVE  TIMESTAMP
													ADD COLUMN DATA_INIZIO_ARB_RISERVE TIMESTAMP
													ADD COLUMN DATA_FINE_ARB_RISERVE  TIMESTAMP
													ADD COLUMN DATA_INIZIO_GIU_RISERVE TIMESTAMP
													ADD COLUMN DATA_FINE_GIU_RISERVE TIMESTAMP
													ADD COLUMN DATA_INIZIO_TRA_RISERVE TIMESTAMP
													ADD COLUMN DATA_FINE_TRA_RISERVE TIMESTAMP';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9ACCO ADD COLUMN DATA_INIZIO_ACC TIMESTAMP
													ADD COLUMN DATA_FINE_ACC TIMESTAMP';
		EXECUTE immediate v_sql;
	
		IF NOT EXISTS (SELECT * FROM SYSCAT.COLUMNS where TABSCHEMA =CURRENT SCHEMA AND TABNAME='W3TABREQ' AND COLNAME ='INIZIALE') THEN 
			SET v_sql= 'ALTER TABLE W3TABREQ ADD COLUMN INIZIALE VARCHAR(1)
														ADD COLUMN DOCUMENTI_DEFAULT VARCHAR(40)';
			EXECUTE immediate v_sql;
		END IF;
	
	
		SET v_sql= 'ALTER TABLE W9PUBBLICAZIONI ADD COLUMN PERC_RIBASSO_AGG NUMERIC(13,9)
													ADD COLUMN PERC_OFF_AUMENTO NUMERIC(13,9)
													ADD COLUMN IMPORTO_AGGIUDICAZIONE NUMERIC(24,5)
													ADD COLUMN DATA_VERB_AGGIUDICAZIONE TIMESTAMP
													ADD COLUMN URL_COMMITTENTE VARCHAR(2000)
													ADD COLUMN URL_EPROC VARCHAR(2000)
													ADD COLUMN ID_GENERATO NUMERIC(10)
													ADD COLUMN ID_RICEVUTO NUMERIC(10)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE AVVISO ADD COLUMN DATASCADENZA TIMESTAMP
													ADD COLUMN CUP VARCHAR(15)
													ADD COLUMN CUIINT VARCHAR(20)
													ADD COLUMN RUP VARCHAR(10)
													ADD COLUMN ID_GENERATO NUMERIC(10)
													ADD COLUMN ID_RICEVUTO NUMERIC(10)
													ADD COLUMN ID_CLIENT VARCHAR(255)
													ADD COLUMN SYSCON NUMERIC(12)
													ADD COLUMN IDUFFICIO NUMERIC(10)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9LOTT ADD COLUMN CUIINT VARCHAR(25)
													ADD COLUMN URL_EPROC VARCHAR(2000)
													ADD COLUMN CUPESENTE VARCHAR(1)
													ADD COLUMN URL_COMMITTENTE VARCHAR(2000)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9GARA ADD COLUMN ID_GENERATO NUMERIC(10)
													ADD COLUMN ID_RICEVUTO NUMERIC(10)
													ADD COLUMN ID_CLIENT VARCHAR(255)
													ADD COLUMN SYSCON NUMERIC(12)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W9CF_PUBB ADD COLUMN TIPO VARCHAR(1)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'ALTER TABLE W3SMARTCIG ADD COLUMN GARA_UUID VARCHAR(40)';
		EXECUTE immediate v_sql;
	
		SET v_sql= 'DROP VIEW V_RUOLOTECNICO';
		EXECUTE immediate v_sql;
		SET v_sql= '
				CREATE VIEW V_RUOLOTECNICO as
				SELECT I.CODGARA, I.CODLOTT, I.ID_RUOLO, I.CODTEC, G.CODEIN,T.SYSCON
				FROM W9INCA I join TECNI T on I.CODTEC = T.CODTEC
				join W9GARA G on I.ID_RUOLO IN (15,16,17)
				WHERE T.CGENTEI = G.CODEIN AND I.CODGARA = G.CODGARA
				UNION ALL
				SELECT G.CODGARA, L.CODLOTT, 14 AS ID_RUOLO, G.RUP AS CODTEC, G.CODEIN,T.SYSCON
				FROM W9GARA G LEFT OUTER JOIN W9LOTT L on G.CODGARA = L.CODGARA
				JOIN TECNI T ON G.RUP = T.CODTEC AND G.CODEIN = T.CGENTEI
				WHERE G.RUP IS NOT NULL
				UNION ALL
				SELECT G.CODGARA, L.CODLOTT, 14 AS ID_RUOLO, CAST(null as VARCHAR(10)) AS CODTEC, G.CODEIN,G.SYSCON
				FROM W9GARA G LEFT OUTER JOIN W9LOTT L on G.CODGARA = L.CODGARA
				WHERE G.SYSCON IS NOT NULL';
		EXECUTE immediate v_sql;
	
	
		SET v_sql= '
			CREATE TABLE W_APPLICATION_KEYS (
				CLIENTID VARCHAR(255) NOT NULL,
				KEY VARCHAR(255),
				NOTE VARCHAR(2000),
				PRIMARY KEY (CLIENTID))';
		EXECUTE immediate v_sql;
		
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE AVVISO');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE UFFICI');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W3SMARTCIG');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W3TABREQ');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9ACCO');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9APPA');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9AVAN');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9CF_PUBB');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9COLL');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9GARA');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9LOTT');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9PUBBLICAZIONI');
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE W9VARI');

		------------------------------------------------------------------------------------------------
		----------------------------------------    MODIFICA DATI    -----------------------------------
		------------------------------------------------------------------------------------------------
		
	------------------------------------------------------------------------------------------------
	----------------------------------------    MODIFICA DATI    -----------------------------------
	------------------------------------------------------------------------------------------------
		------------------------------------------------------------------------------------------------
		----------------------------------------    MODIFICA DATI    -----------------------------------
		------------------------------------------------------------------------------------------------


		Update ELDAVER set NUMVER='4.0.0', DATVET=CURRENT_TIMESTAMP where CODAPP='W9';

	END IF;
end@

call aggiorna@
drop procedure aggiorna@
