-- 270 to 271 --
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_DETTMODSCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_DURC TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_EVENTISCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_GENPROMSCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_MODSCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_REFPROMSCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.G_SCADENZ TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.IMPAZI TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.V_CAIS_TIT TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W_NOTE TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9CODICI_AVCP TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9IMPRESE TO USER SITATORT;
