-- 271 to 272 --
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9CF_MACROFASI TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9CF_REGPERMESSI TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9CF_MODPERMESSI_SA TO USER SITATORT;
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9PERMESSI TO USER SITATORT;
GRANT SELECT ON TABLE SITATORT.V_W9PERMESSI TO USER SITATORT;
GRANT SELECT ON TABLE SITATORT.V_RUOLOTECNICO TO USER SITATORT;

GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9LOADER_APPALTO_USR TO USER SITATORT;