------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------
-- GENE 1.4.50
------------------------------


------------------------------
-- GENEWEB 2.0.0
------------------------------


------------------------------
-- SITATORT 2.6.1
--------------------------

CREATE TABLE SITATORT.W9CONTROLLI 
  (CODCONTROLLO NUMERIC(7) NOT NULL,
	DESCCONTROLLO VARCHAR(2000),
	MSGCONTROLLO VARCHAR(2000),
	TIPOCONTROLLO VARCHAR(1)) IN TBS_SITATORT_N0 INDEX IN TBS_SITATORT_N0;
ALTER TABLE SITATORT.W9CONTROLLI ADD CONSTRAINT W9CONTROLLI_PK PRIMARY KEY ( CODCONTROLLO );
GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9CONTROLLI TO USER SITATORT;




INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (1001,'valorizzazione codice fiscale stazione appaltante','valorizzazione codice fiscale stazione appaltante','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (1002,'Il C.F. della stazione appaltante deve essere un C.F. valido di persona giuridica','Il C.F. della stazione appaltante deve essere un C.F. valido di persona giuridica','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (2001,'Tipologia avviso obbligatoria','Tipologia avviso obbligatoria','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (2002,'Data avviso obbligatoria','Data avviso obbligatoria','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (2003,'Descrizione avviso obbligatoria','Descrizione avviso obbligatoria','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (2004,'File avviso obbligatorio','File avviso obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3001,'Oggetto della gara obbligatorio','Oggetto della gara obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3002,'Codice della gara obbligatorio','Codice della gara obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3003,'Importo gara obbligatorio','Importo gara obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3004,'Modalità indizione gara obbligatoria','Modalità indizione gara obbligatoria','W');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3005,'Modalità di realizzazione obbligatoria','Modalità di realizzazione obbligatoria','W');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3006,'Data pubblicazione sulla GURI obbligatoria','Data pubblicazione sulla GURI obbligatoria','W');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3007,'Data scadenza obbligatoria','Data scadenza obbligatoria','W');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3008,'<null>Inserire almeno un documento di gara','Inserire almeno un documento di gara','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3009,'Inserire almeno un lotto','Inserire almeno un lotto','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3010,'Oggetto del lotto obbligatorio','Oggetto del lotto obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3011,'Codice CIG obbligatorio','Codice CIG obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (3012,'Importo lotto obbligatorio','Importo lotto obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (4001,'Esito della procedura obbligatorio','Esito della procedura obbligatorio','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (4002,'Data aggiudicazione obbligatoria','Data aggiudicazione obbligatoria','E');
INSERT INTO SITATORT.W9CONTROLLI (CODCONTROLLO,DESCCONTROLLO,MSGCONTROLLO,TIPOCONTROLLO) VALUES (4003,'File esito obbligatorio','File esito obbligatorio','E');


INSERT INTO SITATORT.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ', 'ALT.W9.INVIIRM','Personalizzazione invii per Regione Marche',3420);
INSERT INTO SITATORT.W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) values ('FUNZ','ALT.W9.W9FLUSSI_XML','Visualizzazione allegato flussi',3430);

INSERT INTO SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) values ('FUNZ','VIS', 'ALT.W9.INVIIRM','Visualizza',0,1,1,2542046628);

UPDATE SITATORT.ELDAVER SET NUMVER='2.6.1' WHERE CODAPP='W9';

