------------------------------
-- AGGIORNAMENTO SITAT	
------------------------------
-- GENE 1.4.50
------------------------------

UPDATE SITATORT.ELDAVER SET NUMVER='1.4.50' WHERE CODAPP='G_';

------------------------------
-- GENEWEB 1.6.6
------------------------------

UPDATE SITATORT.ELDAVER SET NUMVER='1.6.6' WHERE CODAPP='W_';

------------------------------
-- SITATORT 2.4.2
--------------------------

-- W_PROAZI
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','SEZ','VIS','GENE.SchedaTeim.ALT',0,3279515167);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','SEZ','VIS','GENE.SchedaTeim.ALT',0,3279515167);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-G_IMPCOL',0,1319656519);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-G_IMPCOL',0,1319656519);

-- CANCELLAZIONE DELLE PERSONALIZZAZIONI PROFILI PER VISUALIZZARE IL CAMPO GENE.UFFINT.NATGIU
DELETE FROM SITATORT.W_PROAZI WHERE TIPO='COLS' AND AZIONE='VIS' AND OGGETTO = 'GENE.UFFINT.NATGIU' AND VALORE=1 AND CRC=61481610;

UPDATE SITATORT.ELDAVER SET NUMVER='2.4.2' WHERE CODAPP='W9';

