------------------------------
-- AGGIORNAMENTO TABELLE SITAT SA	
------------------------------
-- GENE 1.4.39
-- GENEWEB 1.5.5
-- SITAT 2.0.0
--------------------------

--GENE


ALTER TABLE SITATORT.G_PERMESSI ADD COLUMN CODANA VARCHAR(10);
ALTER TABLE SITATORT.G_PERMESSI ADD COLUMN CODPRA VARCHAR(16);

ALTER TABLE SITATORT.TEIM ADD COLUMN PRONAS VARCHAR(5);
ALTER TABLE SITATORT.TEIM ADD COLUMN EMAILPEC VARCHAR(1);
ALTER TABLE SITATORT.TEIM ADD COLUMN EMAI2IM VARCHAR(100);
ALTER TABLE SITATORT.TEIM ALTER COLUMN EMAIIM SET DATA TYPE VARCHAR(100);

ALTER TABLE SITATORT.UFFINT ADD COLUMN PRONAS VARCHAR(5);
ALTER TABLE SITATORT.UFFINT ADD COLUMN EMAILPEC VARCHAR(1);
ALTER TABLE SITATORT.UFFINT ADD COLUMN EMAI2IN VARCHAR(100);
ALTER TABLE SITATORT.UFFINT ALTER COLUMN EMAIIN SET DATA TYPE VARCHAR(100);

ALTER TABLE SITATORT.COMP_G ADD COLUMN EMAILPEC VARCHAR(1);
ALTER TABLE SITATORT.COMP_G ADD COLUMN EMAI2IN VARCHAR(100);
ALTER TABLE SITATORT.COMP_G ALTER COLUMN EMAIIN SET DATA TYPE VARCHAR(100);

ALTER TABLE SITATORT.IMPR ADD COLUMN EMAI2IP VARCHAR(100);

ALTER TABLE SITATORT.TECNI ADD COLUMN EMA2TEC VARCHAR(100);

ALTER TABLE SITATORT.UTENT ADD COLUMN EMAIL2 VARCHAR(100);


ALTER TABLE SITATORT.TAB2 ALTER COLUMN TAB2D1 SET DATA TYPE VARCHAR(100);


CREATE TABLE SITATORT.UTENTIND
  (CODUTE VARCHAR(10) NOT NULL,
	CON_FI NUMERIC(7) NOT NULL,
	TIPOIND NUMERIC(7),
	TOPIND VARCHAR(60),
	NCIVIND VARCHAR(30),
	CAPIND VARCHAR(5),
	COMIND VARCHAR(32),
	PROIND VARCHAR(2),
	NOTEIND VARCHAR(2000)
	   ) IN TBS_SITATORT_N0 INDEX IN TBS_SITATORT_N0;
 ALTER TABLE SITATORT.UTENTIND ADD CONSTRAINT UTENTIND_PK PRIMARY KEY (CODUTE,CON_FI);

GRANT SELECT,Insert,UPDATE,DELETE ON TABLE SITATORT.UTENTIND TO USER SITATORT;



Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('10544',1,'Indirizzo per Bollettazione');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('10544',2,'Indirizzo per Comunicazioni');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('10544',3,'Indirizzo di Residenza');
Insert into SITATORT.TAB4 (tab4cod,tab4tip,tab4desc) values('G__1','10544','Tipologie Indirizzi');


ALTER TABLE SITATORT.IMPR ADD COLUMN RINNOS VARCHAR(1);
ALTER TABLE SITATORT.IMPR ADD COLUMN DRINOS TIMESTAMP;
ALTER TABLE SITATORT.IMPR ADD COLUMN DANTIM TIMESTAMP;
ALTER TABLE SITATORT.IMPR ADD COLUMN INTERD VARCHAR(1);


CREATE TABLE SITATORT.IMPANTIMAFIA
  (CODIMP VARCHAR(10) NOT NULL,
  NUMANT NUMERIC(3) NOT NULL,
	ENTRIC NUMERIC(7),
	DRICAC TIMESTAMP,
	NGARA VARCHAR(20),
	CODCIG VARCHAR(20),
	NOT_GAR VARCHAR(2000),
	FORPOL NUMERIC(7),
	DRISFP TIMESTAMP,
	DRIUFP TIMESTAMP,
	ESTGIA VARCHAR(1),
	ATTGIA VARCHAR(100),
	DATGIA TIMESTAMP,
	TIPPRO NUMERIC(7),
	DATPRO TIMESTAMP,
	DRIESA TIMESTAMP,
	DRIEFP TIMESTAMP,
	DACCAT TIMESTAMP,
	DAUTAT TIMESTAMP,
	RICTAR VARCHAR(1),
	DATTAR TIMESTAMP,
	NUMTAR VARCHAR(10),
	DCDEDU TIMESTAMP,
	NCDEDU VARCHAR(10),
	DRICATT TIMESTAMP,
	DTRAATT TIMESTAMP,
	DPROTAR TIMESTAMP,
	PROTAR NUMERIC(7),
	ALTTAR VARCHAR(200),
	RICCON VARCHAR(1),
	DATCON TIMESTAMP,
	ATTCON NUMERIC(7),
	DPROCON TIMESTAMP,
	PROCON NUMERIC(7)
	   ) IN TBS_SITATORT_N0 INDEX IN TBS_SITATORT_N0;
 ALTER TABLE SITATORT.IMPANTIMAFIA ADD CONSTRAINT IMPANTIMAFIA_PK PRIMARY KEY (CODIMP,NUMANT);

GRANT SELECT,Insert,UPDATE,DELETE ON TABLE SITATORT.IMPANTIMAFIA TO USER SITATORT;


Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_032',1,'1    Nome utente (1) o Ufficio di appartenenza (2)');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_031',2,'Respinge');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_031',1,'Accoglie');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_030',2,'Prefettura');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_030',1,'Impresa');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_029',1,'Accoglie');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_029',2,'Respinge');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_029',3,'Altro');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_028',1,'Interdittivo');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_028',2,'Liberatorio');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_027',2,'Forza di polizia 2');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_027',1,'Forza di polizia 1');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_026',3,'Stazione appaltante 2');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_026',1,'SAUP');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('G_026',2,'Stazione appaltante 1');

Insert into SITATORT.TAB4 (TAB4COD,TAB4TIP,TAB4DESC) values ('G__1','G_032','Valore di default per il mittente delle comunicazioni (WEB)');

Insert into SITATORT.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_026','Ente richiedente accertamento antimafia (WEB)');
Insert into SITATORT.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_027','Forza di polizia per accertamento antimafia (WEB)');
Insert into SITATORT.TAB6 (TAB6COD,TAB6TIP,TAB6DESC) values ('G__1','G_030','Attore ricorso Consiglio di Stato per acc.antimafia (WEB)');

delete FROM SITATORT.TAB1 where tab1cod='G_017';

Update SITATORT.C0CAMPI set C0C_FS='A100' where C0C_MNE_BER='G_EMAIIM'; 
Update SITATORT.C0CAMPI set C0C_FS='A100' where C0C_MNE_BER='EMAIIN'; 
Update SITATORT.C0CAMPI set C0C_FS='A100' where C0C_MNE_BER='G_EMAIIN'; 
Update SITATORT.C0CAMPI set C0C_FS='A100' where C0C_MNE_BER='TAB2D1'; 



Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800102065,'E',NULL,'EMAI2IP.IMPR.GENE','G_EMAI2IP','Indirizzo PEC','PEC',NULL,'A100',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800102079,'E',NULL,'RINNOS.IMPR.GENE','G_RINNOS','Abilitazione preventiva in fase di rinnovo?','Rinnovo abil.prev.?','In fase di rinnovo?','A2',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800102080,'E',NULL,'DRINOS.IMPR.GENE','G_DRINOS','Data richiesta rinnovo abilitazione preventiva','Data rich.rinn.ab.pr','Data richiesta rinnovo','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800102081,'E',NULL,'DANTIM.IMPR.GENE','G_DANTIM','Data nulla osta antimafia rilasciato dalla C.C.I.A.A.','Data nullaosta antim','Data nulla osta antimafia','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800102082,'E',NULL,'INTERD.IMPR.GENE','G_INTERD','Impresa interdetta in seguito ad accertamento antimafia?','Interdetta?',NULL,'A2',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106214,'E',NULL,'CODIMP.IMPANTIMAFIA.GENE','G_CODIMP3','Codice impresa','Codice impresa',NULL,'A10',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106215,'E',NULL,'NUMANT.IMPANTIMAFIA.GENE','G_NUMANT','Numero progressivo dell''accertamento','Num. progressivo',NULL,'N3',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106216,'E',NULL,'ENTRIC.IMPANTIMAFIA.GENE','G_ENTRIC','Ente richiedente l''accertamento','Ente richiedente',NULL,'A100','G_026',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106217,'E',NULL,'DRICAC.IMPANTIMAFIA.GENE','G_DRICAC','Data lettera di richiesta accertamento','Data richiesta',NULL,'A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106218,'E',NULL,'NGARA.IMPANTIMAFIA.GENE','G_NGARA','Codice gara per cui Þ richiesto l''accertamento','Codice gara',NULL,'A20',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106219,'E',NULL,'CODCIG.IMPANTIMAFIA.GENE','G_CODCIG','Codice CIG della gara per cui Þ richiesto l''accertamento','Codice CIG gara',NULL,'A20',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106220,'E',NULL,'NOT_GAR.IMPANTIMAFIA.GENE','G_NOTGAR','Oggetto della gara','Oggetto gara',NULL,'A2000',NULL,'NOTE');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106221,'E',NULL,'FORPOL.IMPANTIMAFIA.GENE','G_FORPOL','Forza di polizia a cui Þ inviata la richiesta di accertam.','Forza di polizia',NULL,'A100','G_027',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106222,'E',NULL,'DRISFP.IMPANTIMAFIA.GENE','G_DRISFP','Data risposta delle forze di polizia','Data risposta f.pol.','Data risposta forze di polizia','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106223,'E',NULL,'DRIUFP.IMPANTIMAFIA.GENE','G_DRIUFP','Data riunione delle forze di polizia','Data riunione f.pol.','Data riunione forze di polizia','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106224,'E',NULL,'ESTGIA.IMPANTIMAFIA.GENE','G_ESTGIA','Estensione dell''accertamento al Gruppo Ispettivo Antimafia?','Estensione al GIA?',NULL,'A2',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106225,'E',NULL,'ATTGIA.IMPANTIMAFIA.GENE','G_ATTGIA','Attore della richiesta estensione al Gruppo Ispettivo Antim.','Att.rich.estens.GIA','Attore della richiesta estensione al GIA','A100',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106226,'E',NULL,'DATGIA.IMPANTIMAFIA.GENE','G_DATGIA','Data richiesta estensione al Gruppo Ispettivo Antimafia','Data rich.estens.GIA','Data richiesta estensione al GIA','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106227,'E',NULL,'TIPPRO.IMPANTIMAFIA.GENE','G_TIPPRO','Tipologia del provvedimento','Provvedimento',NULL,'A100','G_028',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106228,'E',NULL,'DATPRO.IMPANTIMAFIA.GENE','G_DATPRO','Data lettera del provvedimento','Data provvedimento',NULL,'A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106229,'E',NULL,'DRIESA.IMPANTIMAFIA.GENE','G_DRIESA','Data richiesta del riesame','Data rich. riesame','Data richiesta riesame','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106230,'E',NULL,'DRIEFP.IMPANTIMAFIA.GENE','G_DRIEFP','Data lettera alle forze di polizia per il riesame','Data riesame f.pol.','Data lettera alle forze di polizia','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106231,'E',NULL,'DACCAT.IMPANTIMAFIA.GENE','G_DACCAT','Data richiesta di accesso agli atti','Data rich.acces.atti','Data richiesta accesso agli atti','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106232,'E',NULL,'DAUTAT.IMPANTIMAFIA.GENE','G_DAUTAT','Data autorizzazione all''accesso agli atti','Data autor.acc.atti','Data autorizzazione accesso agli atti','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106233,'E',NULL,'RICTAR.IMPANTIMAFIA.GENE','G_RICTAR','Ricorso al TAR da parte dell''impresa?','Ricorso al TAR?',NULL,'A2',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106234,'E',NULL,'DATTAR.IMPANTIMAFIA.GENE','G_DATTAR','Data del ricorso al TAR','Data ricorso al TAR','Data ricorso','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106235,'E',NULL,'NUMTAR.IMPANTIMAFIA.GENE','G_NUMTAR','Numero del ricorso al TAR','Num. ricorso al TAR','Numero ricorso','A10',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106236,'E',NULL,'DCDEDU.IMPANTIMAFIA.GENE','G_DCDEDU','Data controdeduzioni','Data controdeduzioni',NULL,'A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106237,'E',NULL,'NCDEDU.IMPANTIMAFIA.GENE','G_NCDEDU','Numero protocollo controdeduzioni','N.prot.controdeduz.','N.protocollo controdeduzioni','A10',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106238,'E',NULL,'DRICATT.IMPANTIMAFIA.GENE','G_DRICATT','Data richiesta atti','Data rich.atti','Data richiesta atti','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106239,'E',NULL,'DTRAATT.IMPANTIMAFIA.GENE','G_DTRAATT','Data trasmissione atti','Data trasmis.atti','Data trasmissione atti','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106240,'E',NULL,'DPROTAR.IMPANTIMAFIA.GENE','G_DPROTAR','Data pronuncia del TAR','Data pronuncia TAR','Data pronuncia del TAR','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106241,'E',NULL,'PROTAR.IMPANTIMAFIA.GENE','G_PROTAR','Esito pronuncia del TAR','Esito pronuncia TAR','Esito pronuncia','A100','G_029',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106242,'E',NULL,'ALTTAR.IMPANTIMAFIA.GENE','G_ALTTAR','Altra pronuncia del TAR','Altra pronuncia TAR','Altra pronuncia','A200',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106243,'E',NULL,'RICCON.IMPANTIMAFIA.GENE','G_RICCON','Ricorso al Consiglio di Stato?','Ricorso a Cons.Stato','Ricorso al Consiglio di Stato?','A2',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106244,'E',NULL,'DATCON.IMPANTIMAFIA.GENE','G_DATCON','Data del ricorso al Consiglio di Stato','Data ricorso Cons.St','Data ricorso','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106245,'E',NULL,'ATTCON.IMPANTIMAFIA.GENE','G_ATTCON','Attore del ricorso al Consiglio di Stato','Att.ricorso Cons.St.','Attore del ricorso','A100','G_030',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106246,'E',NULL,'DPROCON.IMPANTIMAFIA.GENE','G_DPROCON','Data pronuncia del Consiglio di Stato','Data pronun.Cons.St.','Data pronuncia','A10',NULL,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800106247,'E',NULL,'PROCON.IMPANTIMAFIA.GENE','G_PROCON','Esito pronuncia del Consiglio di Stato','Esito pronun.Cons.St','Esito pronuncia','A100','G_031',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800107020,'E',NULL,'PRONAS.TEIM.GENE','G_PRONTEI','Provincia di nascita (sigla)','Provincia di nascita',NULL,'A40','Agx15',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800107027,'E',NULL,'EMAILPEC.TEIM.GENE','G_PECTEI','NON USATO','NON USATO',NULL,'A1',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800107028,'E',NULL,'EMAI2IM.TEIM.GENE','G_EMAI2IM','Indirizzo PEC','PEC',NULL,'A100',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800109052,'E',NULL,'EMA2TEC.TECNI.GENE','G_EMA2TECI','Indirizzo PEC','PEC',NULL,'A100',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (800110044,'E',NULL,'EMAIL2.UTENT.GENE','G_EMAI2UTE','Indirizzo PEC','PEC',NULL,'A100',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (880038149,'E',NULL,'CODANA.G_PERMESSI.GENE','G_CODANA','Codice anagrafica Modulo Professionisti','Cod.Anagraf.MP',NULL,'A10',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (880038150,'E',NULL,'CODPRA.G_PERMESSI.GENE','G_CODPRA','Codice domanda Modulo Professionisti','Codice Domanda MP',NULL,'A16',NULL,NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (880038164,'E',NULL,'PRONAS.UFFINT.GENE','G_PRONUFF','Provincia di nascita (sigla)','Provincia di nascita',NULL,'A40','Agx15',NULL);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (880038176,'E',NULL,'EMAILPEC.UFFINT.GENE','G_PECUFF','NON USATO','NON USATO',NULL,'A1',NULL,'SN');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (880038177,'E',NULL,'EMAI2IN.UFFINT.GENE','EMAI2IN','Indirizzo PEC','PEC',NULL,'A100',NULL,NULL);


Insert into SITATORT.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('IMPANTIMAFIA.GENE',80020430,'E','ANTIMAFIA','Accertamenti antimafia per l''impresa','CODIMP.IMPANTIMAFIA.GENE','IMPR.GENE','CODIMP.IMPR.GENE',null,null,'g_amaf0');

UPDATE SITATORT.ELDAVER Set numver='1.4.39' where codapp='G_';

--GENEWEB
ALTER TABLE SITATORT.W_INVCOM ADD COLUMN COMTIPMA NUMERIC(7);
ALTER TABLE SITATORT.W_INVCOMDES ALTER COLUMN DESMAIL SET DATA TYPE VARCHAR(100);


delete from SITATORT.w_oggetti where tipo='SEZ'  and (oggetto = 'GENE.ImprScheda.DATIGEN.IMPDTE' or oggetto = 'GENE.ImprScheda.DATIGEN.IMPLEG');
delete from SITATORT.w_oggetti where tipo='FUNZ' and (oggetto='INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' or oggetto='DEL.GENE.ImprScheda.DATIGEN.DEL-IMPDTE' or oggetto='INS.GENE.ImprScheda.DATIGEN.INS-IMPLEG' or oggetto='DEL.GENE.ImprScheda.DATIGEN.DEL-IMPLEG');

delete from SITATORT.W_OGGETTI where oggetto in( 'GENE.ImprScheda.RAGIMP' , 'GENE.ImprScheda.CASE','GENE.ImprScheda.DATIGEN.SOA');
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('PAGE', 'GENE.ImprScheda.IMPANTIMAFIA', 'Pagina "Accertamenti antimafia"', 936);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('MASC', 'GENE.IMPANTIMAFIA-scheda', 'Scheda Accertamento antimafia dell''impresa', 1361);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'MOD.GENE.IMPANTIMAFIA-scheda.SCHEDAMOD', 'Modifica accertamento antimafia', 1368);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'INS.GENE.IMPANTIMAFIA-scheda.SCHEDANUOVO', 'Nuovo accertamento antimafia', 1369);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'INS.GENE.ImprScheda.IMPANTIMAFIA.LISTANUOVO', 'Aggiungi accertamento antimafia', 1368);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'DEL.GENE.ImprScheda.IMPANTIMAFIA.LISTADELSEL', 'Elimina accertamenti antimafia selezionati', 1366);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'MOD.GENE.ImprScheda.IMPANTIMAFIA.MOD', 'Modifica accertamento antimafia', 1367);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'DEL.GENE.ImprScheda.IMPANTIMAFIA.DEL', 'Elimina accertamento antimafia', 1365);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.IMPANTIMAFIA-scheda.GEN', 'Dati generali', 1362);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.IMPANTIMAFIA-scheda.RIESAME', 'Riesame', 1363);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.IMPANTIMAFIA-scheda.TAR', 'Ricorso al TAR', 1364);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.IMPANTIMAFIA-scheda.CONS', 'Ricorso al Consiglio di Stato', 1365);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('PAGE', 'GENE.ImprScheda.LEGALI', 'Pagina "Legali e altri soggetti"', 932);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.LEGALI.IMPDTE', 'Direttori tecnici', 1330);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.LEGALI.IMPLEG', 'Legali rappresentanti', 1340);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'INS.GENE.ImprScheda.LEGALI.INS-IMPDTE', 'Aggiungi direttore tecnico', 1331);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'DEL.GENE.ImprScheda.LEGALI.DEL-IMPDTE', 'Elimina direttore tecnico', 1332);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'INS.GENE.ImprScheda.LEGALI.INS-IMPLEG', 'Aggiungi legale rappresentante', 1341);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'DEL.GENE.ImprScheda.LEGALI.DEL-IMPLEG', 'Elimina legale rappresentante', 1342);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.LEGALI.IMPAZI', 'Azionisti', 1345);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'INS.GENE.ImprScheda.LEGALI.INS-IMPAZI', 'Aggiungi azionista', 1346);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'DEL.GENE.ImprScheda.LEGALI.DEL-IMPAZI', 'Elimina azionista', 1347);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('FUNZ', 'MOD.GENE.ImprScheda.LEGALI.SCHEDAMOD', 'Modifica Legali e altri soggetti', 1348);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('PAGE', 'GENE.ImprScheda.RAGIMP', 'Pagina "Raggruppamento"', 934);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('PAGE', 'GENE.ImprScheda.CASE', 'Pagina "Casellario giudiziale"', 935);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.DATIGEN.SOA', 'Iscrizione S.O.A.', 1000);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.DATIGEN.ISO1', 'Certificazione ISO 9001', 1005);
Insert into SITATORT.W_OGGETTI (TIPO, OGGETTO, DESCR, ORD) Values ('SEZ', 'GENE.ImprScheda.DATIGEN.ABI', 'Abilitazione preventiva', 1010);


Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('PAGE', 'VIS', 'GENE.ImprScheda.IMPANTIMAFIA', 'Visualizza', 0, 1, 1, 4083652209);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.IMPR.INTERD', 'Visualizza', 0, 1, 1, 86908082);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.IMPR.MGSFLG', 'Visualizza', 0, 1, 1, 3386612920);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.IMPR.DABPRE', 'Visualizza', 0, 1, 1, 3270030576);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.TECNI.MGSFLG', 'Visualizza', 0, 1, 1, 4146220034);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.TECNI.WEBUSR', 'Visualizza', 0, 1, 1, 1299563297);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.TECNI.WEBPWD', 'Visualizza', 0, 1, 1, 2638937105);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.UTENT.WEBPWD', 'Visualizza', 0, 1, 1, 445361394);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.UTENT.WEBUSR', 'Visualizza', 0, 1, 1, 3400831938);
Insert into  SITATORT.W_AZIONI (TIPO, AZIONE, OGGETTO, DESCR, VALORE, INOR, VISELENCO, CRC) Values ('COLS', 'VIS', 'GENE.TEIM.MGSFLG', 'Visualizza', 0, 1, 1, 3996116098);


delete from SITATORT.TAB1  where tab1cod='G_023';
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('G_023',1,'Pubblica (consultazione libera da web)');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('G_023',2,'Riservata (invio mail e consultazione in area riservata)');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('W_003',1,'PEC e, in sua assenza, e-mail');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('W_003',2,'PEC');
Insert into SITATORT.TAB1 (tab1cod,tab1tip,tab1desc) values('W_003',3,'E-mail');

delete from SITATORT.TAB3 where TAB3COD='G_x10' and tab3tip in ('FS4','FS5');
Insert into SITATORT.TAB3 (tab3cod,tab3tip,tab3desc) values('G_x10','FS4','Aggiornamento dati iscrizione elenco');
Insert into SITATORT.TAB3 (tab3cod,tab3tip,tab3desc) values('G_x10','FS5','Notifica variazioni anagrafiche');


Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (100000121,'P',NULL,'COMTIPMA.W_INVCOM.GENEWEB','COMTIPMA','Tipo indirizzo del destinatario da utilizzare (PEC, e-mail)','PEC o e-mail?','Invio comunicazione a indirizzo PEC o e-mail?','A100','W_003',NULL);
Update SITATORT.C0CAMPI set C0C_FS='A100' where C0C_MNE_BER='DESMAIL'; 


Update SITATORT.ELDAVER Set numver='1.5.5' where codapp='W_';


-- SITAT

Update SITATORT.C0CAMPI set C0C_TAB1='W3z13' WHERE C0C_MNE_BER='FSTIPO';

Delete FROM SITATORT.Tab2 WHERE TAB2COD='W3z12';

Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LU','10','Lussemburgo');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NL','11','Olanda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PT','12','Portogallo');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GB','13','Regno Unito');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ES','14','Spagna');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SE','15','Svezia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AT','2','Austria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BE','3','Belgio');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DK','4','Danimarca');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FI','5','Finlandia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FR','6','Francia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DE','7','Germania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GR','8','Grecia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IE','9','Irlanda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AD','16','Andorra');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AE','17','Emirati Arabi Uniti');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AF','18','Afghanistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AG','19','Antigua e Barbuda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AI','20','Anguilla');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AL','21','Albania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AM','22','Armenia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AN','23','Antille Olandesi');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AO','24','Angola');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AQ','25','Antartico');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AR','26','Argentina');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AS','27','Samoa Americane');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AU','28','Australia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AW','29','Aruba');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AX','30','Isole Aland');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','AZ','31','Azerbaigian');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BA','32','Bosnia-Erzegovina');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BB','33','Barbados');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BD','34','Bangladesh');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BF','35','Burkina Faso');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BG','36','Bulgaria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BH','37','Bahrain');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BI','38','Burundi');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BJ','39','Benin');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BL','40','Saint-Barthelemy');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BM','41','Bermuda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BN','42','Brunei');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BO','43','Bolivia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BR','44','Brasile');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BS','45','Bahamas');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BT','46','Bhutan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BV','47','Isola Bouvet');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BW','48','Botswana');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BY','49','Bielorussia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','BZ','50','Belize');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CA','51','Canada');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CC','52','Isole Cocos');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CD','53','Repubblica Democratica del Congo');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CF','54','Repubblica Centrafricana');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CG','55','Repubblica del Congo');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CH','56','Svizzera');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CI','57','Costa d''Avorio');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CK','58','Isole Cook');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CL','59','Cile');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CM','60','Camerun');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CN','61','Cina');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CO','62','Colombia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CR','63','Costa Rica');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CU','64','Cuba');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CV','65','Capo Verde');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CX','66','Isola Christmas');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CY','67','Cipro');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','CZ','68','Repubblica Ceca');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DJ','69','Gibuti');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DM','70','Dominica');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DO','71','Repubblica Dominicana');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','DZ','72','Algeria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','EC','73','Ecuador');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','EE','74','Estonia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','EG','75','Egitto');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','EH','76','Sahara Occidentale');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ER','77','Eritrea');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ET','78','Etiopia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FJ','79','Figi');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FK','80','Isole Falkland');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FM','81','Stati Federati di Micronesia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','FO','82','Isole Faorer');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GA','83','Gabon');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GD','84','Grenada');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GE','85','Georgia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GF','86','Guyana Francese');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GG','87','Guernsey');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GH','88','Ghana');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GI','89','Gibilterra');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GL','90','Groenlandia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GM','91','Gambia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GN','92','Guinea');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GP','93','Guadalupa');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GQ','94','Guinea Equatoriale');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GS','95','Georgia del Sud e isole Sandwich meridionali');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GT','96','Guatemala');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GU','97','Guam');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GW','98','Guinea-Bissau');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','GY','99','Guyana');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HK','100','Hong Kong');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HM','101','Isole Heard e McDonald');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HN','102','Honduras');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HR','103','Croazia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HT','104','Haiti');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','HU','105','Ungheria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ID','106','Indonesia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IL','107','Israele');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IM','108','Isola di Man');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IN','109','India');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IO','110','Territori Britannici dell''Oceano Indiano');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IQ','111','Iraq');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IR','112','Iran');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','IS','113','Islanda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','JE','114','Jersey');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','JM','115','Giamaica');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','JO','116','Giordania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','JP','117','Giappone');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KE','118','Kenya');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KG','119','Kirghizistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KH','120','Cambogia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KI','121','Kiribati');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KM','122','Comore');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KN','123','Saint Kitts e Nevis');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KP','124','Corea del Nord');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KR','125','Corea del Sud');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KW','126','Kuwait');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KY','127','Isole Cayman');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','KZ','128','Kazakistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LA','129','Laos');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LB','130','Libano');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LC','131','Santa Lucia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LI','132','Liechtenstein');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LK','133','Sri Lanka');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LR','134','Liberia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LS','135','Lesotho');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LT','136','Lituania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LV','137','Lettonia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','LY','138','Libia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MA','139','Marocco');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MC','140','Monaco');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MD','141','Moldavia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ME','142','Montenegro');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MF','143','Saint-Martin');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MG','144','Madagascar');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MH','145','Isole Marshall');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MK','146','Macedonia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ML','147','Mali');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MM','148','Birmania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MN','149','Mongolia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MO','150','Macao');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MP','151','Isole Marianne Settentrionali');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MQ','152','Martinica');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MR','153','Mauritania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MS','154','Montserrat');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MT','155','Malta');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MU','156','Mauritius');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MV','157','Maldive');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MW','158','Malawi');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MX','159','Messico');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MY','160','Malesia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','MZ','161','Mozambico');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NA','162','Namibia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NC','163','Nuova Caledonia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NE','164','Niger');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NF','165','Isola Norfolk');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NG','166','Nigeria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NI','167','Nicaragua');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NO','168','Norvegia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NP','169','Nepal');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NR','170','Nauru');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NU','171','Niue');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','NZ','172','Nuova Zelanda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','OM','173','Oman');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PA','174','Panama');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PE','175','Peru''');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PF','176','Polinesia Francese');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PG','177','Papua Nuova Guinea');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PH','178','Filippine');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PK','179','Pakistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PL','180','Polonia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PM','181','Saint Pierre e Miquelon');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PN','182','Isole Pitcairn');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PR','183','Porto Rico');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PS','184','Territori Palestinesi Occupati');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PW','185','Palau');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','PY','186','Paraguay');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','QA','187','Qatar');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','RE','188','Reunion');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','RO','189','Romania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','RS','190','Serbia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','RU','191','Russia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','RW','192','Ruanda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SA','193','Arabia Saudita');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SB','194','Isole Salomone');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SC','195','Seychelles');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SD','196','Sudan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SG','197','Singapore');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SH','198','Sant''Elena');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SI','199','Slovenia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SJ','200','Svalbard');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SK','201','Slovacchia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SL','202','Sierra Leone');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SM','203','San Marino');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SN','204','Senegal');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SO','205','Somalia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SR','206','Suriname');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ST','207','Sao Tome''e Principe');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SV','208','El Salvador');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SY','209','Siria');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','SZ','210','Swaziland');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TC','211','Isole Turks e Caicos');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TD','212','Ciad');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TF','213','Territori Francesi del Sud');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TG','214','Togo');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TH','215','Thailandia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TJ','216','Tagikistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TK','217','Tokelau');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TL','218','Timor Est');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TM','219','Turkmenistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TN','220','Tunisia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TO','221','Tonga');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TR','222','Turchia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TT','223','Trinidad e Tobago');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TV','224','Tuvalu');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TW','225','Repubblica di Cina');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','TZ','226','Tanzania');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','UA','227','Ucraina');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','UG','228','Uganda');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','UM','229','Isole minori esterne degli Stati Uniti');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','US','230','Stati Uniti d''America');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','UY','231','Uruguay');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','UZ','232','Uzbekistan');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VA','233','Citta''del Vaticano');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VC','234','Saint Vincent e Grenadine');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VE','235','Venezuela');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VG','236','Isole Vergini Britanniche');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VI','237','Isole Vergini Americane');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VN','238','Vietnam');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','VU','239','Vanuatu');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','WF','240','Wallis e Futuna');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','WS','241','Samoa');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','YE','242','Yemen');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','YT','243','Mayotte');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ZA','244','Sudafrica');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ZM','245','Zambia');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values('W3z12','ZW','246','Zimbabwe');


Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) Values ('W3z13','L','L','Lavori');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) Values ('W3z13','F','F','Forniture');
Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) Values ('W3z13','S','S','Servizi');



ALTER TABLE SITATORT.W9FASI ADD COLUMN ID_SCHEDA_LOCALE VARCHAR(50);
ALTER TABLE SITATORT.W9FASI ADD COLUMN ID_SCHEDA_SIMOG VARCHAR(50);

ALTER TABLE SITATORT.W9GARA ADD COLUMN TIPOLOGIA_PROCEDURA NUMERIC(7);
ALTER TABLE SITATORT.W9GARA ADD COLUMN FLAG_CENTRALE_STIPULA VARCHAR(1);
ALTER TABLE SITATORT.W9GARA ADD COLUMN FLAG_ENTE_SPECIALE VARCHAR(5);
ALTER TABLE SITATORT.W9GARA ADD COLUMN ID_MODO_INDIZIONE NUMERIC(7);
ALTER TABLE SITATORT.W9GARA ADD COLUMN CIG_ACCQUADRO VARCHAR(10);

ALTER TABLE SITATORT.W9LOTT ADD COLUMN ID_SCHEDA_LOCALE VARCHAR(50);
ALTER TABLE SITATORT.W9LOTT ADD COLUMN ID_SCHEDA_SIMOG VARCHAR(50);
ALTER TABLE SITATORT.W9LOTT ADD COLUMN ESITO_PROCEDURA NUMERIC(7);
ALTER TABLE SITATORT.W9LOTT ADD COLUMN DAEXPORT VARCHAR(1);

ALTER TABLE SITATORT.W9LOTTCATE ADD COLUMN SCORPORABILE VARCHAR(50);
ALTER TABLE SITATORT.W9LOTTCATE ADD COLUMN SUBAPPALTABILE VARCHAR(50);

ALTER TABLE SITATORT.W9APPA ADD COLUMN DURATA_ACCQUADRO NUMERIC(5);
ALTER TABLE SITATORT.W9APPA ADD COLUMN OPERE_URBANIZ_SCOMPUTO VARCHAR(1);
ALTER TABLE SITATORT.W9APPA ADD COLUMN MODALITA_RIAGGIUDICAZIONE NUMERIC(7);
ALTER TABLE SITATORT.W9APPA ADD COLUMN DATA_STIPULA TIMESTAMP;
ALTER TABLE SITATORT.W9APPA ADD COLUMN DURATA_CON NUMERIC(4);
ALTER TABLE SITATORT.W9APPA ADD COLUMN DATA_TERMINE TIMESTAMP;

ALTER TABLE SITATORT.W9INIZ ADD COLUMN DATA_DECORRENZA TIMESTAMP;
ALTER TABLE SITATORT.W9INIZ ADD COLUMN DATA_SCADENZA TIMESTAMP;

ALTER TABLE SITATORT.W9CONC ADD COLUMN NUM_GIORNI_PROROGA NUMERIC(5);
ALTER TABLE SITATORT.W9CONC ADD COLUMN DATA_VERBALE_CONSEGNA TIMESTAMP;
ALTER TABLE SITATORT.W9CONC ADD COLUMN TERMINE_CONTRATTO_ULT TIMESTAMP;

ALTER TABLE SITATORT.W9SUBA ADD COLUMN CODIMP_AGGIUDICATRICE VARCHAR(10);

ALTER TABLE SITATORT.W9AVAN ADD COLUMN DENOM_AVANZAMENTO VARCHAR(250);

ALTER TABLE SITATORT.W9COLL ADD COLUMN LAVORI_ESTESI VARCHAR(1);

CREATE TABLE SITATORT.W9DOCGARA
  (CODGARA NUMERIC(10) NOT NULL,
	NUMDOC NUMERIC(4) NOT NULL,
	TITOLO VARCHAR(250),
	FILE_ALLEGATO BLOB (100 M ) LOGGED NOT COMPACT
	   ) IN TBS_SITATORT_N0 INDEX IN TBS_SITATORT_N0;
 ALTER TABLE SITATORT.W9DOCGARA ADD CONSTRAINT W9DOCGARA_PK PRIMARY KEY (CODGARA,NUMDOC);

GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE SITATORT.W9DOCGARA TO USER SITATORT;

Insert into SITATORT.W9DOCGARA (Select CODGARA,1,'Bando di gara',FILE_ALLEGATO FROM SITATORT.W9GARA WHERE FILE_ALLEGATO is not null);



REORG TABLE SITATORT.W9FASI;
REORG TABLE SITATORT.W9GARA;
REORG TABLE SITATORT.W9LOTT;
REORG TABLE SITATORT.W9LOTTCATE;
REORG TABLE SITATORT.W9APPA;
REORG TABLE SITATORT.W9INIZ;
REORG TABLE SITATORT.W9CONC;
REORG TABLE SITATORT.W9SUBA;
REORG TABLE SITATORT.W9AVAN;
REORG TABLE SITATORT.W9COLL;




Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ID_SCHEDA_LOCALE.W9FASI.W9','W9FASCHLOC','ID scheda locale','ID scheda locale','ID scheda locale','A50',NULL,NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ID_SCHEDA_SIMOG.W9FASI.W9','W9FASCHSIM','ID scheda SIMOG','ID scheda SIMOG','ID scheda SIMOG','A50',NULL,NULL );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'TIPOLOGIA_PROCEDURA.W9GARA.W9','W9GATIPROC','Tipologia procedura (nel caso agisca per conto di altri)','Tipologia procedura','Tipologia procedura','A100','W3024',NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'FLAG_CENTRALE_STIPULA.W9GARA.W9','W9GASTIPULA','La centrale di committenza provvede alla stipula?','Stipula?','La centrale di committenza provvede alla stipula?','A2',NULL,'SN' );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'FLAG_ENTE_SPECIALE.W9GARA.W9','W9GAFLAG_ENT','Tipo di settore','Tipo settore','Tipo di settore','A5','W3z08',null);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'ID_MODO_INDIZIONE.W9GARA.W9','W9GAMOD_IND','Modalita'' di indizione della gara','Mod. indizione?','Modalita'' di indizione della gara','A100','W3008',null);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'CIG_ACCQUADRO.W9GARA.W9','W9GACIGAQ','CIG accordo quadro/convenzione','CIG acc. quadro','CIG accordo quadro/convenzione','A10',null,null);

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ID_SCHEDA_LOCALE.W9LOTT.W9','W9LOSCHLOC','ID scheda locale','ID scheda locale','ID scheda locale','A50',NULL,NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ID_SCHEDA_SIMOG.W9LOTT.W9','W9LOSCHSIM','ID scheda SIMOG','ID scheda SIMOG','ID scheda SIMOG','A50',NULL,NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'ESITO_PROCEDURA.W9LOTT.W9','W9LOESIPROC','Esito procedura','Esito procedura','Esito procedura','A100','W3022',NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'DAEXPORT.W9LOTT.W9','W9LODAEXP','Lotto da esportare verso AVCP?','Da esportare?','Lotto da esportare verso AVCP?','A2',NULL,'SN' );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'SCORPORABILE.W9LOTTCATE.W9','W9LCSCORPORA','Categoria scorporabile?','Scorporabile?','A2',null,'SN','Categoria scorporabile?');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',null,'SUBAPPALTABILE.W9LOTTCATE.W9','W9LCSUBAPPAL','Categoria subappaltabile?','Subappaltabile?','A2',null,'SN','Categoria subappaltabile?');

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'DURATA_ACCQUADRO.W9APPA.W9','W9APDURACCQ','Durata accordo quadro','Durata acc.quadro','Durata accordo quadro','N5',NULL,NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'OPERE_URBANIZ_SCOMPUTO.W9APPA.W9','W9APOUSCOMP','Opere di urbanizzazione a scomputo?','Opere urb.scomputo?','Opere di urbanizzazione a scomputo?','A2',NULL,'SN' );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'MODALITA_RIAGGIUDICAZIONE.W9APPA.W9','W9APMODRIAG','Modalità di riaggiudicazione','Modal. riaggiudicaz.','Modalità di riaggiudicazione','A100','W3023',NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'DATA_STIPULA.W9APPA.W9','W9APDATA_STI','Data stipula contratto','Data stipula','Data stipula contratto','A10',null,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'DURATA_CON.W9APPA.W9','W9APDURCON','Durata contrattuale in giorni','Durata contratto','Durata contrattuale in giorni','N4',null,null);
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'DATA_TERMINE.W9APPA.W9','W9APDTERM1','Termine contrattuale per dare ultimazione lavori','Termine contrattuale','Termine contrattuale per dare ultimazione lavori','A10',null,'DATA_ELDA');

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'DATA_DECORRENZA.W9INIZ.W9','W9INDECO','Data decorrenza contrattuale','Data decorrenza','Data decorrenza contrattuale','A10',null,'DATA_ELDA');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) values (0,'E',null,'DATA_SCADENZA.W9INIZ.W9','W9INSCAD','Data scadenza contrattuale','Data scadenza','Data scadenza contrattuale','A10',null,'DATA_ELDA');

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'NUM_GIORNI_PROROGA.W9CONC.W9','W9COGGPROR','Numero di giorni di proroga','Giorni proroga','Numero di giorni di proroga','N5',NULL,NULL );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'DATA_VERBALE_CONSEGNA.W9CONC.W9','W9CODVERCON','Data verbale di consegna','Data consegna','Data verbale di consegna','A10',NULL,'DATA_ELDA' );
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'TERMINE_CONTRATTO_ULT.W9CONC.W9','W9COTERCONT','Data termine contrattuale ultimazione','Termine contr. ult.','Data termine contrattuale ultimazione','A10',NULL,'DATA_ELDA' );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'CODIMP_AGGIUDICATRICE.W9SUBA.W9','W9SUIMPAGG','Impresa aggiudicatrice nel caso di aggiudicatari multipli','Impresa aggiudicatr.','Impresa aggiudicatrice','A10',NULL,NULL );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'DENOM_AVANZAMENTO.W9AVAN.W9','W3AVANDENO','Denominazione dello stato di avanzamento','Denominazione S.A.L.','Denominazione stato di avanzamento','A250',NULL,NULL );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,COC_DES_WEB,C0C_FS,C0C_TAB1,COC_DOM) Values (0,'E',NULL,'LAVORI_ESTESI.W9COLL.W9','W3COLLLEST','Lavori estesi a più anni?','Lavori estesi?','Lavori estesi a più anni?','A2',NULL,'SN' );

Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','CODGARA.W9DOCGARA.W9','W9DGCODGARA','Codice della gara','Codice della gara','N10',null,null,'Codice della gara');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E','P','NUMDOC.W9DOCGARA.W9','W9DGNUMDOC','Numero progressivo documento','Numero documento','N4',null,null,'Numero documento');
Insert into SITATORT.C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) values (0,'E',NULL,'TITOLO.W9DOCGARA.W9','W9DGTITOLO','Titolo del documento','Titolo','A250',null,null,'Titolo');


Update SITATORT.C0CAMPI set COC_DES='Data interruzione anticipata', COC_DES_FRM='Data int. anticipata', COC_DES_WEB='Data interruzione anticipata' where C0C_MNE_BER='W3DATA_RIS';

Update SITATORT.C0CAMPI set C0C_MNE_BER='W3I_LOTTO' where C0C_MNE_BER='W9I_LOTTO';

Update SITATORT.C0CAMPI set COC_DES='Modalità di realizzazione',COC_DES_FRM='Mod. realizzazione',COC_DES_WEB='Modalità di realizzazione',COC_DOM='A100' where C0C_MNE_BER='W3TIPOAPP';



Insert into SITATORT.C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) values ('W9DOCGARA.W9',80011600,'P','DOCUM','Bando e documentazione di gara','CODGARA.W9DOCGARA.W9,NUMDOC.W9DOCGARA.W9',null,null,null,null,'w9_docg0');





-- Aggiornamento del campo W9GARA.TIPO_APP per effetto del cambiamento del tabellato W3999 
update SITATORT.W9GARA set TIPO_APP = cast (null as integer) where TIPO_APP = 2;
update SITATORT.W9GARA set TIPO_APP = 10 where TIPO_APP = 3;
update SITATORT.W9GARA set TIPO_APP = 11 where TIPO_APP = 6;
update SITATORT.W9GARA set TIPO_APP = 6 where TIPO_APP = 5;


-- Aggiornamento del campo W9LOTT.ID_SCELTA_CONTRAENTE per effetto del cambiamento del tabellato W3005
update SITATORT.W9LOTT set id_scelta_contraente = 10 where id_scelta_contraente = 9;
update SITATORT.W9LOTT set id_scelta_contraente = 9 where id_scelta_contraente = 3;
update SITATORT.W9LOTT set id_scelta_contraente = null where id_scelta_contraente = 5;

-- Aggiornamento del campo W9CONC.ID_MOTIVO_INTERR per effetto del cambiamento del tabellato W3013
update SITATORT.W9conc set id_motivo_interr = null where id_motivo_interr = 4;
update SITATORT.W9conc set id_motivo_interr = 4 where id_motivo_interr = 5;
update SITATORT.W9conc set id_motivo_interr = 5 where id_motivo_interr = 6;



delete from SITATORT.TAB1 where tab1cod = 'W3005';
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',1,'Procedura aperta');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',2,'Procedura ristretta');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',4,'Procedura negoziata senza previa pubblicazione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',6,'Sistema dinamico di acquisizione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',7,'Cottimo fiduciario');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',8,'Dialogo competitivo');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',9,'Procedura negoziata previa pubblicazione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',10,'Procedura negoziata senza previa indizione di gara (art. 221 D.Lgs. 163/2006)');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',11,'Procedura selettiva ex art. 238 c.7, D.Lgs. 163/2006');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',12,'Affidamento diretto ex art.5 della legge n.381/91');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',13,'Procedura ristretta derivante da avvisi con cui si indice una gara');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',14,'Procedura negoziata derivante da avvisi con cui si indice una gara');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',15,'Affidamento in economia - affidamento diretto');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',16,'Affidamento diretto a societa'' in house');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3005',17,'Affidamento diretto a societa'' raggruppate/consorziate o controllate nelle concessioni di LL.PP.');

Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3008',4,'Procedura che non prevede indizione');

delete from SITATORT.TAB1 where tab1cod = 'W3013';
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3013',1,'Revoca dell''aggiudicazione definitiva');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3013',2,'Risoluzione contrattuale');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3013',3,'Fallimento del soggetto aggiudicatario');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3013',4,'Recesso della stazione appaltante');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3013',5,'Recesso dell''appaltatore');

delete from SITATORT.TAB1 where tab1cod = 'W3022';
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3022',1,'Aggiudicata');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3022',2,'Annullata/Revocata successivamente alla pubblicazione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3022',3,'Deserta');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3022',4,'Senza esito a seguito di offerte irregolari/inammissibili, non congrue o non appropriate');

Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3023',1,'D. Lgs. 163/2006, art. 113 c. 4 e fattispecie consimili');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3023',2,'D. Lgs. 163/2006, art. 140 c. 1');

Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3024',1,'Accordo quadro');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3024',2,'Convenzione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3024',3,'Aggiudicazione di appalti pubblici destinati ad amministrazioni aggiudicatrici');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3024',4,'Aggiudicazione e realizzazione/acquisto di lavori/forniture/servizi');

delete from SITATORT.TAB1 where tab1cod = 'W3999';
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',1,'Contratto d''appalto');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',2,'Contratti d''appalto discendente da accordo quadro/convenzione con successivo confronto competitivo');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',3,'Contratti d''appalto discendente da accordo quadro/convenzione senza successivo confronto competitivo');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',4,'Contratto di concessione di lavori');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',5,'Contratto di concessione di servizi e/o forniture');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',6,'Finanza di progetto');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',7,'Affidamento unitario a contraente generale');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',8,'Acquisizione in economia');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',9,'Locazione finanziaria di opere pubbliche o di pubblica utilità');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',10,'Accordo quadro/convenzione');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('W3999',11,'Concorsi di progettazione/concorsi di idee');


delete from SITATORT.TAB1 where tab1cod = 'A2128';
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',1,'ORGANI COSTITUZIONALI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',2,'MINISTERI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',3,'ORGANI GIURISDIZIONALI E AVVOCATURA');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',4,'AMMINISTRAZIONI INDIPENDENTI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',5,'REGIONI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',6,'AZIENDE SPECIALI REGIONALIZZATE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',7,'PROVINCE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',8,'AZIENDE SPECIALI PROVINCIALIZZATE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',9,'COMUNI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',10,'ENTI DI PREVIDENZA E PREVENZIONE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',11,'ENTI PREPOSTI AD ATTIVITA'' SPORTIVE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',12,'ENTI SCIENTIFICI DI RICERCA E DI SPERIMENTAZIONE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',13,'ENTI DI PROMOZIONE CULTURALE E ARTISTICA');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',14,'AZIENDE SPECIALI MUNICIPALIZZATE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',15,'ISTITUTI AUTONOMI CASE POPOLARI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',16,'AZIENDE DEL SERVIZIO SANITARIO NAZIONALE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',17,'AUTORITA'' DI BACINO');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',18,'COMUNITA'' MONTANE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',19,'ENTI DI BONIFICA E DI SVILUPPO AGRICOLO');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',20,'CONSORZI DI INDUSTRIALIZZAZIONE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',21,'CONSORZI AUTONOMI DI REGIONI, PROVINCE E COMUNI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',22,'CONSORZI ENTI ED AUTORITA'' PORTUALI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',23,'UNIVERSITA'' ED ALTRI ENTI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',24,'ISTITUZIONI EUROPEE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',25,'ISTITUTI BANCARI E FINANZIARI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',26,'ENTI ED ISTITUTI RELIGIOSI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',27,'CONCESSIONARI E IMPRESE DI GESTIONE RETI E INFRASTRUTTURE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',28,'ASSOCIAZIONE DI IMPRESE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',29,'IMPRESE A PARTECIPAZIONE PUBBLICA');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',30,'CONSORZI DI IMPRESE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',31,'IMPRESE ED ALTRI SOGGETTI PRIVATI NON IN FORMA ASSOCIATA');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',32,'ASSOCIAZIONI DI CATEGORIA E ORGANIZZAZIONI SINDACALI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',33,'CAMERE DI COMMERCIO');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',34,'SOGGETTI ESTERI');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',35,'PROVVEDITORATO REGIONALE ALLE OPERE PUBBLICHE');
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC) values ('A2128',36,'ORGANISMI DI DIRITTO PUBBLICO');


Update SITATORT.TAB1 set TAB1NORD=7 WHERE TAB1COD='W3020' and TAB1TIP=1;
Update SITATORT.TAB1 set TAB1NORD=10 WHERE TAB1COD='W3020' and TAB1TIP=986;
Update SITATORT.TAB1 set TAB1NORD=11 WHERE TAB1COD='W3020' and TAB1TIP=2;
Update SITATORT.TAB1 set TAB1NORD=12 WHERE TAB1COD='W3020' and TAB1TIP=3;
Update SITATORT.TAB1 set TAB1NORD=13 WHERE TAB1COD='W3020' and TAB1TIP=985;
Update SITATORT.TAB1 set TAB1NORD=14 WHERE TAB1COD='W3020' and TAB1TIP=4;
Update SITATORT.TAB1 set TAB1NORD=15 WHERE TAB1COD='W3020' and TAB1TIP=999;
Update SITATORT.TAB1 set TAB1NORD=16 WHERE TAB1COD='W3020' and TAB1TIP=998;
Update SITATORT.TAB1 set TAB1NORD=17 WHERE TAB1COD='W3020' and TAB1TIP=5;

Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1NORD) values ('W3020',11,'Stipula accordo quadro/convenzione',9);
Insert into SITATORT.TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1NORD) values ('W3020',12,'Adesione accordo quadro/convenzione',8);



Insert into SITATORT.TAB2 (TAB2COD,TAB2TIP,TAB2D1,TAB2D2) values ('W3z09','3','3','Per i requisiti e l''attestazione');


Insert into SITATORT.tabsche (tabcod, tabcod1, tabcod2, tabdesc) values ('S2002','36','0','ORGANISMI DI DIRITTO PUBBLICO');



UPDATE SITATORT.W9FASI f set ID_SCHEDA_LOCALE=(select CIG from SITATORT.W9LOTT l WHERE f.CODGARA=l.CODGARA and f.CODLOTT=l.CODLOTT) || '_' || cast (FASE_ESECUZIONE as char(3)) || '_' || cast (cast(NUM as decimal(3)) as char(3));
UPDATE SITATORT.W9LOTT SET ID_SCHEDA_LOCALE=CIG ;
UPDATE SITATORT.W9LOTT SET DAEXPORT='1' ;

Delete from SITATORT.W_PROAZI WHERE COD_PROFILO='SA-APPA' AND TIPO='SEZ' AND AZIONE='VIS' AND OGGETTO='GENE.ImprScheda.DATIGEN.CCIAA';
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.DCCIAA',0,3154606715);
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.DCERCC',0,2246961577);
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.DISCIF',0,1402202500);
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.NCERCC',0,563984103);
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.PCCIAA',0,798409382);
Insert into SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('SA-APPA','COLS','VIS','GENE.IMPR.REGDIT',0,1344076067);


UPDATE SITATORT.ELDAVER Set numver='2.0.0' where codapp='W9';



----

DROP view SITATORT.V_PUBB_DOCUMENTI;
CREATE view SITATORT.V_PUBB_DOCUMENTI
(CODGARA,CODLOTT,NUM,TITOLO,FILE,NOMEFILE)
AS
SELECT CODGARA,CAST (NULL as INTEGER),NUMDOC,TITOLO,FILE_ALLEGATO,'Bando' || NUMDOC || '.pdf' FROM sitatort.w9docgara
UNION ALL
SELECT idbando + 1000000000,CAST (NULL as INTEGER),1,NomeAllegato1,DatiAllegato1,NomeAllegato1 from SITATORT.bandi WHERE NomeAllegato1 is not null
UNION ALL
SELECT idbando + 1000000000,CAST (NULL as INTEGER),2,NomeAllegato2,DatiAllegato2,NomeAllegato2 from SITATORT.bandi WHERE NomeAllegato2 is not null
UNION ALL
SELECT idbando + 1000000000,CAST (NULL as INTEGER),3,NomeAllegato3,DatiAllegato3,NomeAllegato3 from SITATORT.bandi WHERE NomeAllegato3 is not null
;

GRANT SELECT ON TABLE SITATORT.V_PUBB_DOCUMENTI  TO USER SITATORT,PUBBLEG;
