------ SCHEMA SITAT ORT ----------
SET SCHEMA = SITATORT;
SET CURRENT PATH = SITATORT;


UPDATE COMMAND OPTIONS USING s OFF;
DROP procedure aggiorna;
UPDATE COMMAND OPTIONS USING s ON;

------ CARATTERE TERMINATORE ----------
--#SET TERMINATOR @


--------------------------------------------------------------
-- AGGIORNAMENTO SITAT/VIGILANZA
-- Database: DB2
-- Versione: 3.0.0 - aggiornamento di PT alla versione 3.2.1
--------------------------------------------------------------

create procedure aggiorna ()
begin

	Declare v_sql varchar(5000);

	IF (select count(*) from eldaver where codapp='PT' and (numver='3.2.0' or numver like '3.2.0.%'))=1
	THEN
		
		SET v_sql= 'CREATE TABLE RIS_CAPITOLO (
			CONTRI NUMERIC(10) NOT NULL,
			CONINT NUMERIC(5) NOT NULL,
			NUMCB NUMERIC(5) NOT NULL,
			NCAPBIL VARCHAR(100),
			IMPSPE VARCHAR(100),
			RG1CB NUMERIC(24,5),
			IMPRFSCB NUMERIC(24,5),
			IMPALTCB NUMERIC(24,5),
			VERIFBIL NUMERIC(1),
			DV1CB NUMERIC(24,5),
			DV2CB NUMERIC(24,5),
			DV3CB NUMERIC(24,5),
			DV9CB NUMERIC(24,5),
			MU1CB NUMERIC(24,5),
			MU2CB NUMERIC(24,5),
			MU3CB NUMERIC(24,5),
			MU9CB NUMERIC(24,5),
			BI1CB NUMERIC(24,5),
			BI2CB NUMERIC(24,5),
			BI3CB NUMERIC(24,5),
			BI9CB NUMERIC(24,5),
			AP1CB NUMERIC(24,5),
			AP2CB NUMERIC(24,5),
			AP3CB NUMERIC(24,5),
			AP9CB NUMERIC(24,5),
			AL1CB NUMERIC(24,5),
			AL2CB NUMERIC(24,5),
			AL3CB NUMERIC(24,5),
			AL9CB NUMERIC(24,5),
			TO1CB NUMERIC(24,5),
			TO2CB NUMERIC(24,5),
			TO3CB NUMERIC(24,5),
			TO9CB NUMERIC(24,5),
			IV1CB NUMERIC(24,5),
			IV2CB NUMERIC(24,5),
			IV9CB NUMERIC(24,5),
			SPESESOST NUMERIC(24,5),
			PRIMARY KEY (CONTRI,CONINT,NUMCB)
		)';
		EXECUTE IMMEDIATE v_sql;
		
		SET v_sql = 'GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE RIS_CAPITOLO TO USER SitatSA, SSELDAS, LM07421';
		EXECUTE IMMEDIATE v_sql;
		
		SET v_sql = 'ALTER TABLE INTTRI ADD COLUMN VALUTAZIONE NUMERIC(1)';
		EXECUTE IMMEDIATE v_sql;
		SET v_sql = 'ALTER TABLE INTTRI DROP COLUMN IMPSPE';
		EXECUTE IMMEDIATE v_sql;
		SET v_sql = 'ALTER TABLE INTTRI DROP COLUMN NCAPBIL';
		EXECUTE IMMEDIATE v_sql;
		SET v_sql = 'ALTER TABLE INTTRI DROP COLUMN VERIFBIL';
		EXECUTE IMMEDIATE v_sql;
		SET v_sql = 'ALTER TABLE INTTRI ADD COLUMN SPESESOST NUMERIC(24,5)';
		EXECUTE IMMEDIATE v_sql;
		CALL SYSPROC.ADMIN_CMD ('REORG TABLE INTTRI');
		
		DELETE FROM C0CAMPI WHERE COC_MNE_UNI in ('IMPSPE.INTTRI.PIANI','NCAPBIL.INTTRI.PIANI','VERIFBIL.INTTRI.PIANI');
		
		INSERT INTO C0ENTIT (C0E_NOM,C0E_NUM,C0E_TIP,COE_ARG,C0E_DES,C0E_KEY,C0E_NOM_EX,COE_KEY_EX,C0E_FRM_RI,COE_FRM_CA,COE_FRM_RE) VALUES ('RIS_CAPITOLO.PIANI',80030500,'E','INTRISCAPI','Risorse capitolo di bilancio','CONTRI.RIS_CAPITOLO.PIANI,CONINT.RIS_CAPITOLO.PIANI,NCAPBIL.RIS_CAPITOLO.PIANI','INTTRI.PIANI','CONTRI.INTTRI.PIANI,CONINT.INTTRI.PIANI',null,null,'pt_riscap');

		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E','P','CONINT.RIS_CAPITOLO.PIANI','T2CONCB','Numero progressivo dell''intervento','N.progr.intervento','N5',null,null,'Numero progressivo dell''intervento');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E','P','CONTRI.RIS_CAPITOLO.PIANI','T2CONTRICB','Numero progressivo del programma','N.progr.piano trien.','N10',null,null,'Numero progressivo del programma');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E','P','NUMCB.RIS_CAPITOLO.PIANI','T2NUMCB','Numero progressivo capitolo','N.progr.ris.cap.','N10',null,null,'Numero progressivo del capitolo');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'NCAPBIL.RIS_CAPITOLO.PIANI','T2NCAPBILCB','Numero capitolo di bilancio','N.capitolo bilancio','A100',null,null,'Numero capitolo di bilancio');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IMPSPE.RIS_CAPITOLO.PIANI','T2IMPSPECB','Impegni di spesa sui capitoli','Impegni spesa capit.','A100',null,null,'Impegni di spesa sui capitoli');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'RG1CB.RIS_CAPITOLO.PIANI','RG1CB','Importo risorse finanziarie regionali','Imp.ris. finanz.reg.','F15',null,'MONEY','Importo risorse finanziarie regionali');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IMPRFSCB.RIS_CAPITOLO.PIANI','T2IMPRFSCB','Importo risorse finanziarie stato/UE','Imp.risorse finanz.','F15',null,'MONEY','Importo risorse finanziarie stato/UE');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IMPALTCB.RIS_CAPITOLO.PIANI','T2IMPALTCB','Importo risorse finanziarie altro','Imp.risorse.finan.al','F15',null,'MONEY','Importo risorse finanziarie altro');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'VERIFBIL.RIS_CAPITOLO.PIANI','T2VERBILCB','Esito positivo verifica coerenza con bilancio ufficio?','Coerente con bilanc?','A2',null,'SN','Esito positivo verifica coerenza con bilancio da parte dell''ufficio?');
																																																	   
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'DV1CB.RIS_CAPITOLO.PIANI','T2IDV1CB','Entrate aventi destinazione vincolata per legge (1'' anno)','Ris.dest.vinc. 1''','F15',null,'MONEY', 'Entrate aventi destinazione vincolata per legge (1''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'DV2CB.RIS_CAPITOLO.PIANI','T2IDV2CB','Entrate aventi destinazione vincolata per legge (2'' anno)','Ris.dest.vinc. 2''','F15',null,'MONEY', 'Entrate aventi destinazione vincolata per legge (2''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'DV3CB.RIS_CAPITOLO.PIANI','T2IDV3CB','Entrate aventi destinazione vincolata per legge (3'' anno)','Ris.dest.vinc. 3''','F15',null,'MONEY', 'Entrate aventi destinazione vincolata per legge (3''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'DV9CB.RIS_CAPITOLO.PIANI','T2DV9CB', 'Entrate aventi destinazione vincolata per legge (anni succ)','Ris.dest.vinc. suc','F15',null,'MONEY','Entrate aventi destinazione vincolata per legge (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'MU1CB.RIS_CAPITOLO.PIANI','T2IMU1CB','Entrate acquisite mediante contrazione di mutuo (1'' anno)','Ris.acquis.mutuo 1''','F15',null,'MONEY','Entrate acquisite mediante contrazione di mutuo (1''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'MU2CB.RIS_CAPITOLO.PIANI','T2IMU2CB','Entrate acquisite mediante contrazione di mutuo (2'' anno)','Ris.acquis.mutuo 2''','F15',null,'MONEY','Entrate acquisite mediante contrazione di mutuo (2''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'MU3CB.RIS_CAPITOLO.PIANI','T2IMU3CB','Entrate acquisite mediante contrazione di mutuo (3'' anno)','Ris.acquis.mutuo 3''','F15',null,'MONEY','Entrate acquisite mediante contrazione di mutuo (3''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'MU9CB.RIS_CAPITOLO.PIANI','T2MU9CB', 'Entrate acquisite mediante contrazione di mutuo (anni succ)','Ris.acquis.mutuo suc','F15',null,'MONEY','Entrate acquisite mediante contrazione di mutuo (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'BI1CB.RIS_CAPITOLO.PIANI','T2IBI1CB','Stanziamenti di bilancio (1'' anno)','Imp.stanz.bilanc. 1''','F15',null,'MONEY','Stanziamenti di bilancio (1'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'BI2CB.RIS_CAPITOLO.PIANI','T2IBI2CB','Stanziamenti di bilancio (2'' anno)','Imp.stanz.bilanc. 2''','F15',null,'MONEY','Stanziamenti di bilancio (2'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'BI3CB.RIS_CAPITOLO.PIANI','T2IBI3CB','Stanziamenti di bilancio (3'' anno)','Imp.stanz.bilanc. 3''','F15',null,'MONEY','Stanziamenti di bilancio (3'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'BI9CB.RIS_CAPITOLO.PIANI','T2BI9CB','Stanziamenti di bilancio (anni successivi)','Imp.stanz.bilan.succ','F15',null,'MONEY','Stanziamenti di bilancio anni successivi"');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AP1CB.RIS_CAPITOLO.PIANI','T2AP1CB','Finanziamenti art. 3 DL 310/1990 (1''anno)','Imp.finanz.1''anno','F15',null,'MONEY','Finanziamenti art. 3 DL 310/1990 (1''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AP2CB.RIS_CAPITOLO.PIANI','T2AP2CB','Finanziamenti art. 3 DL 310/1990 (2''anno)','Imp.finanz.2''anno','F15',null,'MONEY','Finanziamenti art. 3 DL 310/1990 (2''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AP3CB.RIS_CAPITOLO.PIANI','T2AP3CB','Finanziamenti art. 3 DL 310/1990 (3''anno)','Imp.finanz.3''anno','F15',null,'MONEY','Finanziamenti art. 3 DL 310/1990 (3''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AP9CB.RIS_CAPITOLO.PIANI','T2AP9CB','Finanziamenti art. 3 DL 310/1990 (anni successivi)','Imp.finanz. anni suc','F15',null,'MONEY','Finanziamenti art. 3 DL 310/1990 (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AL1CB.RIS_CAPITOLO.PIANI','T2IAL1CB','Altre risorse disponibili (1'' anno)','Imp.altre risors. 1''','F15',null,'MONEY','Altre risorse disponibili (1'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AL2CB.RIS_CAPITOLO.PIANI','T2IAL2CB','Altre risorse disponibili (2'' anno)','Imp.altre risors. 2''','F15',null,'MONEY','Altre risorse disponibili (2'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AL3CB.RIS_CAPITOLO.PIANI','T2IAL3CB','Altre risorse disponibili (3'' anno)','Imp.altre risors. 3''','F15',null,'MONEY','Altre risorse disponibili (3'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'AL9CB.RIS_CAPITOLO.PIANI','T2AL9CB','Altre risorse disponibili (anni successivi)','Imp.altre risors.suc','F15',null,'MONEY','Altre risorse disponibili (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'TO1CB.RIS_CAPITOLO.PIANI','T2ITO1CB','Importo complessivo (1'' anno)','Importo compless. 1''','F15',null,'MONEY','Importo complessivo (1'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'TO2CB.RIS_CAPITOLO.PIANI','T2ITO2CB','Importo complessivo (2'' anno)','Importo compless. 2''','F15',null,'MONEY','Importo complessivo (2'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'TO3CB.RIS_CAPITOLO.PIANI','T2ITO3CB','Importo complessivo (3'' anno)','Importo compless. 3''','F15',null,'MONEY','Importo complessivo (3'' anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'TO9CB.RIS_CAPITOLO.PIANI','T2TO9CB','Importo complessivo (anni successivi)','Importo comples .suc','F15',null,'MONEY','Importo complessivo disponibili (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IV1CB.RIS_CAPITOLO.PIANI','T2IV1CB','Importo IVA (1''anno)','Importo IVA 1''anno','F24.5',null,'MONEY','Importo IVA (1''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IV2CB.RIS_CAPITOLO.PIANI','T2IV2CB','Importo IVA (2''anno)','Importo IVA 2''anno','F24.5',null,'MONEY','Importo IVA (2''anno)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'IV9CB.RIS_CAPITOLO.PIANI','T2IV9CB','Importo IVA (anni successivi)','Importo IVA anni suc','F24.5',null,'MONEY','Importo IVA (anni successivi)');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'SPESESOST.RIS_CAPITOLO.PIANI','T2SPESECB','Spese già sostenute','Spese sostenute','F15',null,'MONEY','Spese già sostenute');
		
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'VALUTAZIONE.INTTRI.PIANI','T2VALUTAINT','Valutazione del responsabile dl programma','Valut. responsabile','T15','PT021',null,'Valutazione del responsabile dl programma');
		INSERT INTO C0CAMPI (COC_CONTA,C0C_TIP,C0C_CHI,COC_MNE_UNI,C0C_MNE_BER,COC_DES,COC_DES_FRM,C0C_FS,C0C_TAB1,COC_DOM,COC_DES_WEB) VALUES (0,'E',null,'SPESESOST.INTTRI.PIANI','T2SPESESOST','Spese già sostenute','Spese sostenute','F15',null,'MONEY','Spese già sostenute');
		
		UPDATE C0CAMPI set COC_DES='Annualità avvio procedura di affidamento', COC_DES_FRM='Anno avvio affidam.', COC_DES_WEB='Annualità avvio procedura di affidamento' where COC_MNE_UNI = 'ANNRIF.INTTRI.PIANI';
		
		INSERT INTO TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD,TAB1ARC) VALUES ('PT021',1,'Accolto',null,null,null);
		INSERT INTO TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD,TAB1ARC) VALUES ('PT021',2,'Sospeso',null,null,null);
		INSERT INTO TAB1 (TAB1COD,TAB1TIP,TAB1DESC,TAB1MOD,TAB1NORD,TAB1ARC) VALUES ('PT021',3,'Respinto',null,null,null);

		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('PAGE','PIANI.INTTRI-scheda.INTERVENTO','Pagina Intervento - Scheda intervento',6020);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('PAGE','PIANI.INTTRI-scheda.RISORSEBILANCIO','Pagina Intervento - Scheda Risorse per capitolo di bilancio',6025);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','PIANI.INTTRI-scheda.INTERVENTO.ACQVERDI','Pagina Intervento - Scheda Acquisti verdi',6030);
		INSERT INTO W_OGGETTI (TIPO,OGGETTO,DESCR,ORD) VALUES ('SEZ','PIANI.INTTRI-scheda.INTERVENTO.MATRIC','Pagina Intervento - Scheda Materiali riciclati',6035);
		
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.ACQVERDI','Visualizza',0,1,1,3378577521);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.DIRGEN','Visualizza',0,1,1,1662235308);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.IMPALT','Visualizza',0,1,1,1701084351);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.IMPRFS','Visualizza',0,1,1,927018130);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.MATRIC','Visualizza',0,1,1,453282956);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.QUANTIT','Visualizza',0,1,1,2133630041);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.REFERE','Visualizza',0,1,1,821971293);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.RESPUF','Visualizza',0,1,1,4137032418);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.RG1TRI','Visualizza',0,1,1,3645427203);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.STRUOP','Visualizza',0,1,1,4167311987);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.UNIMIS','Visualizza',0,1,1,1907123350);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('COLS','VIS','PIANI.INTTRI.VALUTAZIONE','Visualizza',0,1,1,451053860);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('PAGE','VIS','PIANI.INTTRI-scheda.RISORSEBILANCIO','Visualizza',0,1,1,792596830);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('SEZ','VIS','PIANI.INTTRI-scheda.INTERVENTO.ACQVERDI','Visualizza',0,1,1,2612833523);
		INSERT INTO W_AZIONI (TIPO,AZIONE,OGGETTO,DESCR,VALORE,INOR,VISELENCO,CRC) VALUES ('SEZ','VIS','PIANI.INTTRI-scheda.INTERVENTO.MATRIC','Visualizza',0,1,1,2239696433);

		UPDATE ELDAVER SET NUMVER = '3.2.1', DATVET=CURRENT_TIMESTAMP WHERE CODAPP='PT';
	
		COMMIT;
		
	END IF;
end@

call aggiorna@
drop procedure aggiorna@
