------------------------------
-- AGGIORNAMENTO TABELLE SITAT	
------------------------------
-- GENE 1.4.39
-- GENEWEB 1.5.5
-- SITATSA 2.0.3
--------------------------

-- SITAT


UPDATE SITATORT.C0CAMPI SET COC_DES='Codice gara Autorità alla richiesta del CIG',COC_DES_WEB='Codice gara restituito dall''AVCP' where C0C_MNE_BER='W3IDGARA';
UPDATE SITATORT.C0CAMPI SET COC_DES='Principali carenze dell''impresa', COC_DES_WEB='Principali carenze dell''impresa' where C0C_MNE_BER='W3TPDESCARE';
UPDATE SITATORT.C0CAMPI SET COC_DES='Messaggio di errore', COC_DES_WEB='Messaggio di errore',COC_DES_FRM='Messaggio errore' where C0C_MNE_BER='W9IBMSG';

UPDATE SITATORT.TAB1 SET TAB1DESC = 'Esito negativo idoneità tecnico-professionale impresa' where TAB1COD = 'W3020' and TAB1TIP = 997;

--Profilo: ORT-APPA
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','COLS','VIS','GENE.IMPR.DANTIM',0,160075319);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPAZI',0,147612543);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPDTE',0,2570711371);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','SEZ','VIS','GENE.ImprScheda.DATIGEN.ISO1',0,900991630);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPDTE',0,1526828649);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPAZI',0,3404995677);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-APPA','SEZ','VIS','GENE.ImprScheda.DATIGEN.ABI',0,4156912262);
DELETE FROM SITATORT.W_PROAZI WHERE COD_PROFILO = 'ORT-APPA' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATORT.W_PROAZI WHERE COD_PROFILO = 'ORT-APPA' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;

--Profilo: ORT-PIATRI
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','COLS','VIS','GENE.IMPR.DANTIM',0,160075319);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPAZI',0,147612543);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','FUNZ','VIS','INS.GENE.ImprScheda.LEGALI.INS-IMPDTE',0,2570711371);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','SEZ','VIS','GENE.ImprScheda.DATIGEN.ISO1',0,900991630);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPDTE',0,1526828649);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','SEZ','VIS','GENE.ImprScheda.LEGALI.IMPAZI',0,3404995677);
INSERT INTO SITATORT.W_PROAZI (COD_PROFILO,TIPO,AZIONE,OGGETTO,VALORE,CRC) VALUES ('ORT-PIATRI','SEZ','VIS','GENE.ImprScheda.DATIGEN.ABI',0,4156912262);
DELETE FROM SITATORT.W_PROAZI WHERE COD_PROFILO = 'ORT-PIATRI' AND TIPO = 'COLS' AND AZIONE = 'VIS' AND OGGETTO = 'GENE.IMPR.PIVIMP' AND VALORE = 0 AND CRC = 2093884230;
DELETE FROM SITATORT.W_PROAZI WHERE COD_PROFILO = 'ORT-PIATRI' AND TIPO = 'FUNZ' AND AZIONE = 'VIS' AND OGGETTO = 'INS.GENE.ImprScheda.DATIGEN.INS-IMPDTE' AND VALORE = 0 AND CRC = 3504095061;

UPDATE SITATORT.ELDAVER Set numver='2.0.3' where codapp='W9';